Repository scikit-image/scikit-image, pull requests merged in 2018-10, with the labels that each got.

#3368 Incompatible modes with anti-aliasing in skimage.transform.resize
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: status: mrg+1, type: bug

#3443 Remove code specific to python 2
  skimage/filters/thresholding.py
  skimage/io/manage_plugins.py
Labels: status: needs review, type: maintenance

#3442 Update instructions et al for releases after 0.14.1
  Makefile
  RELEASE.txt
  doc/release/release_0.14.rst
  requirements/docs.txt
  tools/upload_wheels.sh
Labels: type: maintenance

#3444 Fix default value of `methods` in `_try_all` to avoid exception
  skimage/filters/thresholding.py
Labels: status: needs review, type: bug

#3388 Show our data in the gallery
  doc/examples/data/README.txt
  doc/examples/data/plot_general.py
  doc/examples/data/plot_scientific.py
  doc/examples/data/plot_specific.py
Labels: status: mrg+1, type: documentation

#3398 Allow import/execution with -OO
  TODO.txt
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: status: mrg+1, type: enhancement, type: maintenance

#3454 TST: filter away novice deprecation warnings during testing
  TODO.txt
  conftest.py
Labels: status: mrg+1, type: maintenance

#3326 codecov: ignore build scripts in coverage and don't comment on PRs
  .codecov.yml
  tools/check_sdist.py
  tools/travis/before_install.sh
Labels: status: in progress, type: maintenance

#3453 MNT: handle a deprecation warning for np.linspace and floats for the num parameter
  skimage/measure/profile.py
Labels: status: mrg+1, type: maintenance

#3456 MNT: handle warning in scipy cdist for unused parameters
  skimage/feature/match.py
  skimage/feature/tests/test_match.py
Labels: status: needs review, type: maintenance

#3254 Remove cython md5 hashing since it breaks the build process
  .travis.yml
  MANIFEST.in
  skimage/_build.py
  skimage/_shared/setup.py
  skimage/feature/setup.py
  skimage/filters/setup.py
  skimage/graph/setup.py
  skimage/measure/setup.py
  skimage/morphology/setup.py
  skimage/restoration/setup.py
  skimage/segmentation/setup.py
  skimage/transform/setup.py
Labels: status: mrg+1, type: maintenance

#3470 DOC: Document that now PYTHONOPTMIZE build is blocked by SciPy
  TODO.txt
Labels: status: mrg+1, type: maintenance

#3474 FIX: making the plot_marching_cubes example visible.
  requirements/default.txt
Labels: status: needs review, type: bug, type: documentation

#3479 MAINT: Blacklist specific Cython versions
  requirements/README.md
  requirements/build.txt
Labels: type: maintenance

#3480 Fix typos
  RELEASE.txt
  doc/examples/color_exposure/plot_ihc_color_separation.py
  doc/examples/filters/plot_nonlocal_means.py
  doc/examples/segmentation/plot_chan_vese.py
  doc/release/release_0.14.rst
  doc/release/release_dev.rst
  doc/source/gitwash/development_workflow.rst
  doc/source/themes/scikit-image/static/css/custom.css
  doc/source/user_guide/video.rst
  skimage/_shared/_warnings.py
  skimage/draw/_draw.pyx
  skimage/exposure/exposure.py
  skimage/feature/_hog.py
  skimage/feature/peak.py
  skimage/feature/setup.py
  skimage/feature/tests/test_match.py
  skimage/future/graph/tests/test_rag.py
  skimage/graph/_mcp.pyx
  skimage/graph/heap.pyx
  skimage/graph/tests/test_flexible.py
  skimage/io/_plugins/gtk_plugin.py
  skimage/io/_plugins/pil_plugin.py
  skimage/io/_plugins/q_color_mixer.py
  skimage/io/_plugins/q_histogram.py
  skimage/io/_plugins/qt_plugin.py
  skimage/io/_plugins/skivi.py
  skimage/io/_plugins/util.py
  skimage/measure/_ccomp.pyx
  skimage/measure/_find_contours.py
  skimage/measure/_marching_cubes_lewiner_cy.pyx
  skimage/measure/_regionprops.py
  skimage/measure/mc_meta/createluts.py
  skimage/measure/profile.py
  skimage/morphology/misc.py
  skimage/restoration/deconvolution.py
  skimage/restoration/non_local_means.py
  skimage/restoration/tests/test_unwrap.py
  skimage/segmentation/_chan_vese.py
  skimage/segmentation/active_contour_model.py
  skimage/transform/_hough_transform.pyx
  skimage/transform/hough_transform.py
  skimage/util/noise.py
  skimage/viewer/viewers/core.py
Labels: backport: 0.14.x

#3481 Bugfix: erroneous use of cython wrap around
  skimage/restoration/_denoise_cy.pyx
  skimage/segmentation/_felzenszwalb_cy.pyx
Labels: action: mrg+1

#3334 Implementation of masked image translation registration
  CONTRIBUTORS.txt
  TODO.txt
  doc/examples/transform/plot_masked_register_translation.py
  doc/release/release_dev.rst
  skimage/feature/__init__.py
  skimage/feature/masked_register_translation.py
  skimage/feature/tests/test_masked_register_translation.py
Labels: action: mrg+1, type: new feature

#3495 Add "optional" indications to docstrings
  skimage/exposure/exposure.py
Labels: status: needs review, type: documentation, type: maintenance

#3459 MNT: don't use filter_warnings in test suite.
  skimage/restoration/tests/test_unwrap.py
  skimage/util/tests/test_dtype.py
Labels: action: mrg+1, type: maintenance

#3471 DOC: Replace broken links by webarchive equivalent links
  skimage/filters/_frangi.py
  skimage/filters/_gabor.py
Labels: status: needs review, type: documentation, type: maintenance

#3508 Various minor edits for active contour
  doc/examples/edges/plot_active_contours.py
  skimage/segmentation/active_contour_model.py
Labels: action: mrg+1, type: maintenance

#3514 BUGFIX: handle correctly the maximum number of lines in hough transform
  skimage/transform/_hough_transform.pyx
Labels: action: mrg+1, type: bug

#3503 MNT: Early stop rank kernel noise filter as intended
  skimage/filters/rank/generic_cy.pyx
Labels: action: mrg+1, type: maintenance

#2539 Add section on API discovery via `skimage.lookfor`
  doc/source/user_guide/getting_help.rst
Labels: action: mrg+1, type: documentation

#3518 Raise meaningful exception in warping when image is empty
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: type: enhancement
