Repository scikit-image/scikit-image, pull requests merged in 2018-02, with the labels that each got.

#2957 Raise warning when attempting to save boolean image
  skimage/io/_io.py
  skimage/io/_plugins/test_plugin.ini
  skimage/io/_plugins/test_plugin.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_plugin.py
Labels: status: needs review, type: enhancement

#2905 Add a subset of LFW dataset to `skimage.data`
  doc/release/release_dev.rst
  skimage/data/__init__.py
  skimage/data/lfw_subset.npy
  skimage/data/tests/test_data.py
Labels: status: mrg+2, type: new feature

#2937 Specify `gradient` parameter docstring in `compare_ssim`
  skimage/measure/_structural_similarity.py
Labels: type: documentation

#2854 Add 3D support to `blob_dog` and `blob_log`
  TODO.txt
  skimage/feature/blob.py
  skimage/feature/corner.py
  skimage/feature/tests/test_blob.py
  skimage/feature/tests/test_corner.py
  skimage/filters/_frangi.py
Labels: status: needs review, type: enhancement

#2971 Mark data_range as being a float
  skimage/measure/_structural_similarity.py
Labels: status: mrg+1, type: documentation
