Repository scikit-image/scikit-image, pull requests merged in 2018-05, with the labels that each got.

#3040 Fix examples not displaying figures
  doc/examples/filters/plot_frangi.py
  doc/examples/xx_applications/plot_coins_segmentation.py
  doc/examples/xx_applications/plot_geometric.py
  doc/examples/xx_applications/plot_morphology.py
  doc/examples/xx_applications/plot_rank_filters.py
Labels: status: mrg+1, type: documentation

#3050 Switch to basis numpy int dtypes in dtype_range
  skimage/measure/_structural_similarity.py
  skimage/util/_invert.py
  skimage/util/dtype.py
  skimage/util/tests/test_invert.py
Labels: status: needs review, type: bug

#3063 For sparse CG solver, provide atol=0 keyword for SciPy >= 1.1
  skimage/segmentation/random_walker_segmentation.py
Labels: type: maintenance

#2898 EXA example for haar like features
  doc/examples/xx_applications/plot_haar_extraction_selection_classification.py
  requirements/default.txt
  requirements/docs.txt
  skimage/feature/haar.py
Labels: type: documentation, type: new feature

#3074 Sanitizing marching_cubes_lewiner spacing input argument
  skimage/measure/_marching_cubes_lewiner.py
  skimage/measure/tests/test_marching_cubes.py
Labels: status: mrg+1, type: enhancement

#3076 Allow convex_hull_image on empty images
  skimage/morphology/convex_hull.py
  skimage/morphology/tests/test_convex_hull.py
Labels: status: mrg+1, type: enhancement

#3029 `draw.random_shapes` API improvements
  doc/examples/edges/plot_random_shapes.py
  doc/release/release_dev.rst
  skimage/draw/_random_shapes.py
  skimage/draw/tests/test_random_shapes.py
Labels: status: mrg+1, status: needs review, type: enhancement

#2893 Allow mixed dtypes in compare_ssim, compare_psnr, etc.
  skimage/measure/_structural_similarity.py
  skimage/measure/simple_metrics.py
  skimage/measure/tests/test_simple_metrics.py
  skimage/measure/tests/test_structural_similarity.py
Labels: status: needs review, type: enhancement

#2996 Return empty list on flat images with hough_ellipse #2820
  skimage/transform/_hough_transform.pyx
  skimage/transform/hough_transform.py
  skimage/transform/tests/test_hough_transform.py
Labels: status: in progress, type: enhancement

#3093 Force Appveyor to fail on failed tests
  .appveyor.yml
  skimage/morphology/_watershed.pyx
Labels: type: maintenance

#3056 speedup img_as_float by making division multiplication and avoiding unecessary allocation
  skimage/util/dtype.py
  skimage/util/tests/test_dtype.py
Labels: status: needs review, type: perfomance

#3098 Replace grey by gray where no deprecation is needed
  doc/examples/segmentation/plot_extrema.py
  doc/examples/xx_applications/plot_coins_segmentation.py
  skimage/feature/_canny.py
  skimage/feature/_daisy.py
  skimage/feature/_texture.pyx
  skimage/io/_io.py
Labels: status: mrg+1, type: documentation

#2838 Make `regionprops._slice` a user-facing property
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: status: mrg+1

#3109 Linking preserve_range parameter calls to docs
  skimage/_shared/utils.py
  skimage/filters/_gaussian.py
  skimage/filters/_unsharp_mask.py
  skimage/transform/_warps.py
Labels: status: mrg+1

#2940 Added small galleries in the API
  doc/source/conf.py
  doc/tools/apigen.py
Labels: status: needs review, type: documentation, type: new feature

#3130 Hide warnings in test_unsharp_mask
  skimage/filters/tests/test_unsharp_mask.py
Labels: status: mrg+1, type: maintenance
