Repository scikit-image/scikit-image, pull requests merged in 2018-12, with the labels that each got.

#3574 Add RGB to grayscale example to gallery
  doc/examples/color_exposure/plot_local_equalize.py
  doc/examples/color_exposure/plot_rgb_to_gray.py
Labels: action: mrg+1, type: documentation

#3549 TST: filter warning from `correct_mesh_orientation` in tests
  skimage/measure/tests/test_marching_cubes.py
Labels: action: mrg+1

#3452 MNT; handle deprecation warnings in tifffile
  skimage/external/tifffile/tifffile.py
Labels: action: mrg+1, type: maintenance

#3572 Filtered out DeprecationPendingWarning for matrix subclass
  skimage/segmentation/tests/test_random_walker.py
Labels: priority: critical, type: maintenance

#3554 DOC: Improve the RANSAC gallery example
  doc/examples/transform/plot_ransac.py
  doc/examples/transform/plot_ransac3D.py
Labels: action: mrg+1, type: documentation

#3589 Hyperlink DOIs to preferred resolver
  README.md
  skimage/_shared/fast_exp.h
Labels: action: mrg+1, type: documentation

#3500 Random walker bug fix: no error should be raised when there is nothing to do
  skimage/segmentation/random_walker_segmentation.py
  skimage/segmentation/tests/test_random_walker.py
Labels: priority: critical, status: needs review, type: bug

#3591 Missing parameter description in `morphology.reconstruction() docstring #3581
  skimage/morphology/greyreconstruct.py
  skimage/morphology/tests/test_reconstruction.py
Labels: status: needs review, type: documentation, type: maintenance

#3602 [MRG] update documentation for regionprops
  skimage/measure/_regionprops.py
Labels: action: mrg+1, type: documentation

#3582 Turn dask to an optional requirement
  requirements/default.txt
  requirements/docs.txt
  requirements/optional.txt
  skimage/restoration/_cycle_spin.py
  skimage/restoration/tests/test_denoise.py
Labels: action: mrg+1, type: maintenance

#3608 [MRG] Update documentation of `perimeter` and add input validation
  skimage/measure/_regionprops.py
Labels: action: mrg+1, type: documentation

#3596 EHN: allow tuple to define kernel in threshold_niblack and threshold_sauvola
  doc/source/api_changes.rst
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: status: needs review, type: enhancement

#3568 Add histogram matching
  CONTRIBUTORS.txt
  doc/examples/transform/plot_histogram_matching.py
  skimage/transform/__init__.py
  skimage/transform/histogram_matching.py
  skimage/transform/tests/test_histogram_matching.py
Labels: status: needs review, type: new feature

#3607 Add rgb to hsv example in the gallery
  doc/examples/color_exposure/plot_rgb_to_hsv.py
Labels: type: documentation

#3610 Additionnal mask option to clear_border
  skimage/segmentation/_clear_border.py
  skimage/segmentation/tests/test_clear_border.py
Labels: action: mrg+1

#3627 Add explicit ordering of gallery sections
  doc/source/conf.py
Labels: type: documentation

#3626 Added glossary to the doc
  doc/source/glossary.rst
  doc/source/index.rst
  doc/source/themes/scikit-image/static/css/custom.css
  doc/source/user_guide/numpy_images.rst
  doc/source/user_guide/transforming_image_data.rst
Labels: action: mrg+1, type: documentation, type: new feature

#3617 Update Travis-CI to xcode 10.1
  .travis.yml
Labels: type: maintenance
