Repository scikit-image/scikit-image, pull requests merged in 2018-08, with the labels that each got.

#3242 pytest: Numpy 1 15 warnings
  TODO.txt
  skimage/_shared/_warnings.py
  skimage/color/tests/test_colorconv.py
  skimage/filters/tests/test_lpi_filter.py
  skimage/io/tests/test_imageio.py
  skimage/measure/tests/test_simple_metrics.py
  skimage/restoration/tests/test_denoise.py
  skimage/segmentation/tests/test_random_walker.py
  skimage/util/tests/test_dtype.py
  tools/travis/install_qt.sh
Labels: status: mrg+1, type: maintenance

#3313 Remove deprecated `dynamic_range` in `measure.compare_psnr`
  doc/release/release_dev.rst
  skimage/measure/simple_metrics.py
  skimage/measure/tests/test_simple_metrics.py
Labels: type: maintenance

#2927 Credit Reviewers in Release Notes
  doc/release/contribs.py
Labels: status: mrg+1, status: needs review, type: enhancement, type: maintenance

#3320 Novice skip url test
  skimage/novice/_novice.py
Labels: status: mrg+1

#3321 Remove benchmarks from wheel
  setup.py
  tools/check_sdist.py
Labels: type: maintenance

#3303 Fix incorrect inertia tensor
  skimage/measure/_moments.py
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_moments.py
  skimage/measure/tests/test_regionprops.py
Labels: type: bug

#3234 BENCH: Add benchmarks for morphology.watershed
  benchmarks/benchmark_morphology.py
Labels: status: in progress, type: perfomance

#3322 Add license file to the wheel (binary) distribution
  setup.cfg
Labels: status: mrg+1, type: maintenance

#3340 Backport PR #3315 on branch v0.14.x
  .appveyor.yml
Labels: type: maintenance

#3348 Backport PR #3243 on branch v0.14.x
  skimage/io/_plugins/matplotlib_plugin.py
Labels: status: mrg+1, type: enhancement

#3349 Backport PR #3341 on branch v0.14.x
  skimage/transform/_warps.py
Labels: type: documentation

#3310 Backport of #3238
  doc/release/release_dev.rst
  skimage/data/_binary_blobs.py
  skimage/feature/template.py
  skimage/filters/lpi_filter.py
  skimage/morphology/greyreconstruct.py
  skimage/restoration/_denoise.py
  skimage/restoration/tests/test_denoise.py
  skimage/restoration/uft.py
  skimage/segmentation/_clear_border.py
  skimage/segmentation/boundaries.py
  skimage/util/_regular_grid.py
  skimage/util/arraycrop.py
  skimage/util/shape.py
Labels: status: mrg+1, type: maintenance

#3357 Allow @hmaarrfk to mention MeeseeksDev to backport.
  .meeseeksdev.yml
  tools/check_sdist.py
Labels: status: mrg+1

#3358 Merge pull request #3357 from Carreau/meeseeksdev-config
  tools/check_sdist.py
Labels: type: maintenance

#3364 Backport PR #3359 on branch v0.14.x
  .appveyor.yml
  .travis.yml
  TODO.txt
  requirements/optional.txt
Labels: type: maintenance

#3272 improve segmentation.felzenszwalb document #3264
  skimage/segmentation/_felzenszwalb.py
Labels: status: needs decision, type: documentation

#3336 Backport PR #3303 on branch v0.14.x
  skimage/measure/_moments.py
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_moments.py
  skimage/measure/tests/test_regionprops.py
Labels: type: bug

#3366 Fix deprecated keyword from dask
  doc/examples/xx_applications/plot_haar_extraction_selection_classification.py
Labels: backport: 0.14.x, type: documentation, type: maintenance

#3314 Remove deprecated `dynamic_range` in `measure.compare_psnr` (backport)
  doc/release/release_dev.rst
  skimage/measure/simple_metrics.py
  skimage/measure/tests/test_simple_metrics.py
Labels: type: maintenance

#3374 add comma to measure init
  skimage/measure/__init__.py
Labels: backport: 0.14.x

#3378 Speed up inner loop of GLCM
  benchmarks/benchmark_feature.py
  requirements/test.txt
  skimage/feature/_texture.pyx
Labels: status: mrg+1, type: perfomance

#3370 Missing cval parameter in threshold_local
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: backport: 0.14.x, status: needs review, type: bug

#3382 Backport PR #3370 on branch v0.14.x
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: type: bug
