Repository scikit-image/scikit-image, pull requests merged in 2018-06, with the labels that each got.

#3115 Release guidelines update
  RELEASE.txt
  doc/release/release_dev.rst
  doc/release/release_template.rst
Labels: type: documentation

#2830 Better document remove_small_objects behaviour: int vs bool
  skimage/morphology/misc.py
Labels: type: documentation

#3097 Use proper axis indexing in `adapt_rgb` `each_channel`
  skimage/color/adapt_rgb.py
  skimage/color/tests/test_adapt_rgb.py
Labels: type: bug

#3132 Process 0.15 deprecations
  TODO.txt
  doc/examples/filters/plot_denoise.py
  doc/examples/xx_applications/plot_thresholding.py
  doc/release/release_dev.rst
  skimage/filters/__init__.py
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
  skimage/restoration/_denoise.py
  skimage/restoration/non_local_means.py
  skimage/restoration/tests/test_denoise.py
  skimage/transform/_warps.py
  skimage/transform/radon_transform.py
  skimage/transform/tests/test_radon_transform.py
  skimage/transform/tests/test_warps.py
  skimage/util/__init__.py
  skimage/util/_montage.py
  skimage/util/dtype.py
  skimage/util/tests/test_montage.py
Labels: status: needs review, type: maintenance

#2902 Speedup 2D warping for affine transformations
  skimage/transform/_warps.py
  skimage/transform/_warps_cy.pyx
Labels: status: mrg+1, type: perfomance

#3164 Remove skimage.test as it was never used.
  doc/release/release_dev.rst
  skimage/__init__.py
Labels: type: maintenance

#3163 Normalized the package number to PEP440
  RELEASE.txt
  skimage/__init__.py
Labels: type: maintenance

#3161 moved data_dir to within `data/__init__.py`
  skimage/__init__.py
  skimage/data/__init__.py
Labels: type: maintenance

#3171 Set minimum cython version to `0.23.4`
  INSTALL.rst
  requirements/build.txt
  skimage/_build.py
Labels: type: maintenance

#3170 Regression fix: Travis should fail if tests fail
  INSTALL.rst
  skimage/filters/_unsharp_mask.py
  skimage/restoration/_denoise.py
  skimage/restoration/tests/test_denoise.py
  tools/travis/script.sh
Labels: status: mrg+1

#3194 Added instructions for meeseeksdev to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation

#3137 Add initial airspeed velocity (asv) framework
  .github/PULL_REQUEST_TEMPLATE.md
  asv.conf.json
  benchmarks/benchmarks.py
  doc/release/release_dev.rst
  tools/check_sdist.py
Labels: status: mrg+1, type: new feature

#3202 Big image labeling fix
  skimage/measure/_ccomp.pyx
Labels: type: enhancement

#3210 Fix Qt viewer painttool indexing
  skimage/viewer/canvastools/painttool.py
  viewer_examples/plugins/watershed_demo.py
Labels: type: bug

#3187 Speedup rgb2gray using matrix multiply
  skimage/color/colorconv.py
Labels: status: needs review, type: perfomance

#3162 Moved the definition of lookfor out of __init__.py
  skimage/__init__.py
  skimage/util/lookfor.py
Labels: status: in progress, type: maintenance

#3211 build_versions.py is no longer hard coded.
  .travis.yml
  requirements/build.txt
  requirements/test.txt
  tools/build_versions.py
Labels: type: maintenance

#3022 Replace morphology.local_maxima with faster flood-fill based Cython version
  CONTRIBUTORS.txt
  doc/release/release_dev.rst
  skimage/morphology/__init__.py
  skimage/morphology/_extrema_cy.pyx
  skimage/morphology/_queue_with_history.pxi
  skimage/morphology/extrema.py
  skimage/morphology/setup.py
  skimage/morphology/tests/test_extrema.py
  skimage/morphology/watershed.py
Labels: status: mrg+1, type: enhancement

#3215 Various updates to the ASV benchmarks
  .gitignore
  benchmarks/__init__.py
  benchmarks/benchmarks.py
Labels: type: maintenance, type: perfomance

#3197 Remove installation instructions for video packages
  doc/source/user_guide/video.rst
Labels: type: documentation
