Repository scikit-image/scikit-image, pull requests merged in 2018-04, with the labels that each got.

#2999 Add release notes for 0.13.1
  doc/release/release_0.13.rst
Labels: status: mrg+1, type: documentation

#3008 Ensure stdev is always nonnegative in _mean_std
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: type: bug

#2930 Ensure warning to provide bool array is warranted
  skimage/morphology/misc.py
  skimage/morphology/tests/test_misc.py
Labels: status: mrg+1, type: enhancement

#3013 Add citation information to README
  README.md
Labels: type: documentation

#2979 Bugfix LineModelND.residuals does not use the optional parameter `params`
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: status: mrg+1, type: bug

#2859 Add Computation of Image Moments to Coordinates
  skimage/measure/__init__.py
  skimage/measure/_moments.py
  skimage/measure/tests/test_moments.py
Labels: status: needs review, type: new feature

#3030 Type dependent inversion
  skimage/util/_invert.py
  skimage/util/tests/test_invert.py
Labels: type: enhancement

#3023 Minor style and documentation updates for #2859
  doc/release/release_dev.rst
  skimage/measure/_moments.py
Labels: status: mrg+1, type: documentation

#2955 Add `alignment` parameter to `feature.plot_matches`
  doc/release/release_dev.rst
  skimage/feature/tests/test_util.py
  skimage/feature/util.py
Labels: status: mrg+1, type: enhancement

#3038 Fix RuntimeError: generator raised StopIteration on Python 3.7
  skimage/measure/_find_contours.py
Labels: type: maintenance

#3042 Correct reference for the coins sample image
  skimage/data/__init__.py
Labels: status: mrg+1, type: documentation
