Repository scikit-image/scikit-image, pull requests merged in 2019-02, with the labels that each got.

#3648 Delay matplotlib import in skimage/future/manual_segmentation.py
  skimage/future/manual_segmentation.py
Labels: action: mrg+1

#3708 Enable the faulthandler module during testing
  requirements/test.txt
Labels: backport: 0.14.x

#3695 Numerous backports to 0.14.x to avoid warnings in tests and python 3.7
  .travis.yml
  requirements/README.md
  requirements/build.txt
  requirements/docs.txt
  requirements/optional.txt
  requirements/test.txt
  skimage/exposure/tests/test_exposure.py
  skimage/external/tifffile/tifffile.py
  skimage/feature/_texture.pyx
  skimage/feature/match.py
  skimage/feature/tests/test_peak.py
  skimage/filters/_gaussian.py
  skimage/graph/heap.pyx
  skimage/graph/tests/test_heap.py
  skimage/measure/mc_meta/visual_test.py
  skimage/measure/profile.py
  skimage/measure/tests/test_marching_cubes.py
  skimage/morphology/extrema.py
  skimage/restoration/tests/test_denoise.py
  skimage/viewer/tests/test_plugins.py
  tools/travis/before_install.sh
Labels: action: mrg+1

#3690 Add support for anisotropic blob detection in blob_log and blob_dog
  skimage/feature/blob.py
  skimage/feature/tests/test_blob.py
Labels: action: mrg+1, status: needs review, type: enhancement

#3710 Replace np.einsum with np.tensordot in _upsampled_dft
  CONTRIBUTORS.txt
  benchmarks/benchmark_feature.py
  skimage/feature/register_translation.py
  skimage/feature/tests/test_register_translation.py
Labels: action: mrg+1, type: perfomance

#3472 DOC: Add notes on setting up the build environment
  CONTRIBUTING.txt
Labels: action: mrg+1, type: documentation

#3656 Correctly ignore release notes auto-generated for docs
  .gitignore
Labels: action: mrg+1, backport: 0.14.x

#3748 Add image of retina to our data
  doc/examples/data/plot_scientific.py
  skimage/data/__init__.py
  skimage/data/retina.jpg
Labels: status: needs review, type: enhancement

#3749 Make local_maxima return a boolean array
  doc/release/release_dev.rst
  skimage/morphology/extrema.py
  skimage/morphology/tests/test_extrema.py
Labels: action: mrg+1, status: needs review, type: bug, type: maintenance

#3744 Fix matplotlib + qt 5.12 the same way upstream does it
  .travis.yml
  tools/travis/install_qt.sh
Labels: backport: 0.14.x

#2680 Attribute operators
  TODO.txt
  doc/examples/filters/plot_attribute_operators.py
  doc/examples/yy_dev/README.txt
  doc/examples/yy_dev/plot_max_tree.py
  doc/source/conf.py
  requirements/build.txt
  skimage/data/__init__.py
  skimage/data/microaneurysms.png
  skimage/morphology/__init__.py
  skimage/morphology/_max_tree.pyx
  skimage/morphology/max_tree.py
  skimage/morphology/setup.py
  skimage/morphology/tests/test_max_tree.py
Labels: status: needs review, type: new feature

#3761 gallery: remove xx or yy sorted directory names
  doc/examples/applications/README.txt
  doc/examples/applications/plot_coins_segmentation.py
  doc/examples/applications/plot_face_detection.py
  doc/examples/applications/plot_geometric.py
  doc/examples/applications/plot_haar_extraction_selection_classification.py
  doc/examples/applications/plot_morphology.py
  doc/examples/applications/plot_rank_filters.py
  doc/examples/applications/plot_thresholding.py
  doc/examples/developers/README.txt
  doc/examples/developers/plot_max_tree.py
  doc/examples/segmentation/plot_thresholding.py
  doc/source/conf.py
  doc/source/user_guide/tutorial_segmentation.rst
  skimage/feature/haar.py
Labels: action: mrg+1, type: maintenance

#3319 Add benchmark suite for hough_line()
  benchmarks/benchmark_transform.py
Labels: type: perfomance

#3765 Add microaneurysms() to gallery
  doc/examples/data/plot_scientific.py
Labels: status: needs review, type: documentation, type: maintenance

#3762 Allow for f-contiguous 2D arrays in convex_hull_image
  skimage/morphology/convex_hull.py
  skimage/morphology/tests/test_convex_hull.py
Labels: type: enhancement

#3245 FEAT: Flood fill in n-dimensions
  doc/examples/segmentation/plot_floodfill.py
  doc/release/release_dev.rst
  skimage/morphology/__init__.py
  skimage/morphology/_flood_fill.py
  skimage/morphology/_flood_fill_cy.pyx
  skimage/morphology/extrema.py
  skimage/morphology/setup.py
  skimage/morphology/tests/test_flood_fill.py
  skimage/morphology/watershed.py
  skimage/segmentation/__init__.py
  skimage/util/__init__.py
Labels: status: needs review, type: new feature

#3766 Add urllib.request again
  requirements/test.txt
  skimage/io/tests/test_io.py
  skimage/io/util.py
Labels: priority: critical

#3645 optional dependencies on pip
  .travis.yml
  requirements/README.md
  requirements/extras.txt
  requirements/optional.txt
  setup.py
Labels: priority: critical
