Repository scikit-image/scikit-image, pull requests merged in 2019-08, with the labels that each got.

#4069 MNT: remove unused import `deprecated` from filters.threasholding
  skimage/filters/thresholding.py
Labels: action: mrg+1

#3996 DOC: various enhancements (cross links, gallery, ref...), mainly for corner detection
  doc/examples/features_detection/plot_corner.py
  doc/examples/features_detection/plot_shape_index.py
  doc/examples/filters/plot_phase_unwrap.py
  skimage/feature/corner.py
  skimage/feature/peak.py
Labels: action: mrg+1, type: documentation

#4084 Make use of FFTs more consistent across the library
  TODO.txt
  skimage/_shared/fft.py
  skimage/feature/masked_register_translation.py
  skimage/feature/register_translation.py
  skimage/feature/tests/test_masked_register_translation.py
  skimage/feature/tests/test_register_translation.py
  skimage/filters/lpi_filter.py
  skimage/restoration/uft.py
  skimage/transform/radon_transform.py
Labels: type: maintenance

#4089 Visual image comparison
  doc/examples/applications/plot_image_comparison.py
  skimage/util/__init__.py
  skimage/util/compare.py
  skimage/util/tests/test_compare.py
Labels: action: mrg+1, type: new feature

#4101 Add cell dataset to docs
  skimage/data/__init__.py
  skimage/data/tests/test_data.py
Labels: action: mrg+1, type: documentation, type: maintenance

#3934 MAINT: cleanup regionprop add PYTHONOPTIMIZE=2 to travis array
  .travis.yml
  TODO.txt
  skimage/measure/_regionprops.py
Labels: action: mrg+1, status: needs review, type: infrastructure

#4007 fix URL encoding for wikipedia references in filters.rank.entropy and filters.rank.shannon_entropy docstring
  skimage/filters/rank/generic.py
  skimage/measure/entropy.py
Labels: action: mrg+1, type: documentation

#4097 Log polar
  doc/examples/transform/plot_register_rotation.py
  skimage/transform/__init__.py
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: action: mrg+1, status: needs review, type: new feature

#4102 Drop Python 3.5 support
  .appveyor.yml
  .travis.yml
  TODO.txt
  azure-pipelines.yml
  doc/release/release_dev.rst
  requirements/default.txt
  setup.py
Labels: type: maintenance

#4110 Gallery: use fstrings for better readability
  doc/examples/edges/plot_random_shapes.py
  doc/examples/filters/plot_denoise.py
  doc/examples/filters/plot_denoise_wavelet.py
  doc/examples/filters/plot_nonlocal_means.py
  doc/examples/segmentation/plot_metrics.py
  doc/examples/segmentation/plot_segmentations.py
  doc/examples/transform/plot_fundamental_matrix.py
  doc/examples/transform/plot_masked_register_translation.py
  doc/examples/transform/plot_radon_transform.py
  doc/examples/transform/plot_register_rotation.py
  doc/examples/transform/plot_register_translation.py
Labels: type: documentation

#4109 DOC: enhance the result display in ransac gallery example
  doc/examples/transform/plot_matching.py
Labels: type: documentation

#4114 Rename docstring section in data.__init__
  skimage/data/__init__.py
Labels: type: maintenance

#4115 Deprecate neighbors parameter in convex_hull_object
  TODO.txt
  doc/release/release_dev.rst
  skimage/measure/_label.py
  skimage/morphology/convex_hull.py
  skimage/morphology/tests/test_convex_hull.py
Labels: type: maintenance

#4118 Update the links the installation guide
  doc/source/_templates/navbar.html
  setup.py
Labels: type: maintenance
