Repository scikit-image/scikit-image, pull requests merged in 2019-05, with the labels that each got.

#3869 Fix doc for denoise guassian
  skimage/filters/rank/bilateral.py
  skimage/segmentation/tests/test_random_walker.py
Labels: action: mrg+1, type: maintenance

#3881 Maintenance backports #3870 and #3869
  skimage/filters/rank/bilateral.py
  skimage/segmentation/tests/test_random_walker.py
Labels: action: mrg+1, type: maintenance

#3067 transform: fix filter bias
  skimage/transform/radon_transform.py
  skimage/transform/tests/test_radon_transform.py
Labels: action: mrg+1

#3897 Remove matplotlib agg warning when using the sphinx gallery.
  doc/source/conf.py
Labels: action: mrg+1, type: maintenance

#3901 RANSAC: don't pick duplicate samples
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: backport: 0.14.x, type: bug

#3793 Add skimage 0.14.3 release notes
  doc/release/release_0.14.rst
Labels: action: mrg+1

#3873 Build and test the docs in Azure
  azure-pipelines.yml
  doc/examples/applications/plot_haar_extraction_selection_classification.py
  doc/examples/features_detection/plot_haar.py
  doc/source/random_gallery.py
Labels: status: needs review, type: infrastructure

#3917 Fix docstring for Threshold Niblack
  skimage/filters/thresholding.py
Labels: action: mrg+1, type: documentation

#3851 Followup deprecations for 0.16
  TODO.txt
  doc/release/release_dev.rst
  skimage/draw/tests/test_draw.py
  skimage/feature/corner.py
  skimage/feature/tests/test_corner.py
  skimage/filters/_median.py
  skimage/filters/tests/test_median.py
  skimage/io/_io.py
  skimage/io/tests/test_imageio.py
  skimage/io/tests/test_imread.py
  skimage/io/tests/test_io.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_simpleitk.py
  skimage/measure/_moments.py
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_moments.py
  skimage/measure/tests/test_regionprops.py
  skimage/transform/tests/test_warps.py
Labels: action: mrg+1, status: needs review, type: maintenance

#3920 MIN: docstring improvements in canny functions
  skimage/feature/_canny.py
Labels: action: mrg+1, type: documentation

#3872 Adding `threshold_multiotsu`.
  benchmarks/benchmark_filters.py
  doc/examples/segmentation/plot_multiotsu.py
  skimage/filters/__init__.py
  skimage/filters/_multiotsu.pyx
  skimage/filters/setup.py
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: status: needs review, type: new feature

#3932 Add warning for future dtype kwarg removal
  TODO.txt
  skimage/io/_plugins/fits_plugin.py
  skimage/io/_plugins/gdal_plugin.py
  skimage/io/_plugins/tifffile_plugin.py
Labels: type: maintenance

#3930 Replacing pyfits with Astropy to read FITS
  skimage/io/_plugins/fits_plugin.py
  skimage/io/tests/test_fits.py
Labels: action: mrg+1, type: maintenance

#3775 Implement Farid & Simoncelli derivatives
  doc/examples/edges/plot_edge_filter.py
  skimage/filters/__init__.py
  skimage/filters/edges.py
  skimage/filters/tests/test_edges.py
Labels: action: mrg+1, type: new feature
