Repository scikit-image/scikit-image, pull requests merged in 2019-06, with the labels that each got.

#3943 Update the joblib link in tutorial_parallelization.rst
  doc/source/user_guide/tutorial_parallelization.rst
Labels: backport: 0.14.x

#3935 Adding complexity and new tests for filters.threshold_multiotsu
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: status: in progress

#3525 Add detail to ProjectiveTransform repr and str
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: status: in progress, type: discussion, type: enhancement

#3970 Add missing argument to docstring of PaintTool
  skimage/viewer/canvastools/painttool.py
Labels: part: viewer

#3971 Add poly2mask to convert a polygon to a mask.
  .gitignore
  skimage/draw/__init__.py
  skimage/draw/_polygon2mask.py
  skimage/draw/tests/test_polygon2mask.py
Labels: action: mrg+1, type: new feature

#3977 Minor fixes to new polygon2mask module
  skimage/draw/_polygon2mask.py
Labels: type: maintenance
