Repository scikit-image/scikit-image, pull requests merged in 2019-07, with the labels that each got.

#3312 Add benchmark suite for exposure module
  benchmarks/benchmark_exposure.py
Labels: type: perfomance

#3933 ENH: doc of ridge functions
  doc/examples/edges/plot_ridge_filter.py
  skimage/filters/ridges.py
Labels: type: documentation

#3900 Fix CSS styling of Sphinx 2.0.1 + numpydoc 0.9 rendered docs
  doc/source/themes/scikit-image/static/css/custom.css
  requirements/docs.txt
Labels: action: mrg+1, priority: critical, type: documentation

#3958 Add shepp_logan_phantom, colorwheel, brick, grass, roughwall to the data module
  TODO.txt
  doc/examples/applications/plot_morphology.py
  doc/examples/data/plot_general.py
  doc/examples/data/plot_scientific.py
  doc/examples/features_detection/plot_gabor.py
  doc/examples/features_detection/plot_local_binary_pattern.py
  doc/examples/transform/plot_radon_transform.py
  skimage/data/__init__.py
  skimage/data/brick.png
  skimage/data/grass.png
  skimage/data/gravel.png
  skimage/data/rough-wall.png
Labels: action: mrg+1

#4002 matplotlib: remove interpolation=nearest, none in our examples
  doc/examples/applications/plot_coins_segmentation.py
  doc/examples/applications/plot_rank_filters.py
  doc/examples/edges/plot_contours.py
  doc/examples/edges/plot_convex_hull.py
  doc/examples/edges/plot_shapes.py
  doc/examples/edges/plot_skeleton.py
  doc/examples/features_detection/plot_blob.py
  doc/examples/features_detection/plot_corner.py
  doc/examples/features_detection/plot_gabor.py
  doc/examples/features_detection/plot_gabors_from_astronaut.py
  doc/examples/features_detection/plot_glcm.py
  doc/examples/features_detection/plot_multiblock_local_binary_pattern.py
  doc/examples/numpy_operations/plot_camera_numpy.py
  doc/examples/numpy_operations/plot_view_as_blocks.py
  doc/examples/segmentation/plot_extrema.py
  doc/examples/segmentation/plot_floodfill.py
  doc/examples/segmentation/plot_marked_watershed.py
  doc/examples/segmentation/plot_random_walker_segmentation.py
  doc/examples/segmentation/plot_watershed.py
  doc/examples/transform/plot_edge_modes.py
  doc/examples/transform/plot_swirl.py
  skimage/feature/util.py
Labels: type: documentation

#3711 Simplify benchmarks pinnings
  asv.conf.json
Labels: status: needs decision, type: infrastructure

#4006 MAINT: Do not use assert in code, raise an exception instead.
  skimage/feature/texture.py
  skimage/io/_plugins/pil_plugin.py
  skimage/io/_plugins/util.py
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
  skimage/transform/_geometric.py
  skimage/transform/radon_transform.py
Labels: status: needs review, type: maintenance

#4001 MAINT: remove dead code
  skimage/filters/_gaussian.py
Labels: action: mrg+1, type: maintenance

#2835 Corrected error with scales attribute in ORB.detect_and_extract
  skimage/feature/orb.py
  skimage/feature/tests/test_orb.py
Labels: status: needs review

#3966 Fix threshold_li (again) and add developer example
  doc/examples/data/plot_scientific.py
  doc/examples/developers/plot_threshold_li.py
  skimage/data/__init__.py
  skimage/data/cell.png
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: type: bug, type: maintenance

#4019 Suppress warnings in test_rank due to type conversion
  skimage/filters/rank/tests/test_rank.py
Labels: action: mrg+1

#4033 Import Iterable from collections.abc
  skimage/segmentation/slic_superpixels.py
Labels: action: mrg+1, type: maintenance

#4034 Import Iterable from collections.abc in vendored tifffile code
  skimage/external/tifffile/tifffile.py
Labels: action: mrg+1, type: maintenance

#4032 Fixup integer division in examples
  doc/examples/transform/plot_rescale.py
Labels: action: mrg+1, type: bug, type: documentation

#4016 [DOC] How to test and write benchmarks
  CONTRIBUTING.txt
  README.md
  benchmarks/benchmark_transform.py
Labels: action: mrg+1, type: documentation

#4036 Correction of typos after #4025
  skimage/measure/simple_metrics.py
  skimage/metrics/simple_metrics.py
  skimage/morphology/selem.py
  skimage/restoration/_denoise_cy.pyx
Labels: priority: critical

#4031 Turn guess_spatial_dimensions to a private function
  TODO.txt
  skimage/color/colorconv.py
  skimage/color/tests/test_colorconv.py
  skimage/filters/__init__.py
  skimage/filters/_gaussian.py
  skimage/filters/tests/test_gaussian.py
Labels: action: mrg+1, type: maintenance

#4045 Remove .meeseeksdev.yml, Mark is a core-dev.
  .meeseeksdev.yml
  tools/check_sdist.py
Labels: type: maintenance

#4049 Fix mpl deprecation on grid()
  doc/examples/filters/plot_cycle_spinning.py
Labels: type: documentation, type: maintenance

#4050 Fix gallery after deprecation from #4025
  doc/examples/filters/plot_cycle_spinning.py
  doc/examples/filters/plot_denoise_wavelet.py
  doc/examples/filters/plot_nonlocal_means.py
  doc/examples/transform/plot_ssim.py
Labels: priority: critical

#4047 Add shape= to circle perimeter in hough_circle example
  doc/examples/edges/plot_circular_elliptical_hough_transform.py
Labels: action: mrg+1, type: documentation

#4053 fix mpl future deprecation normed -> density
  doc/examples/features_detection/plot_local_binary_pattern.py
Labels: type: maintenance

#4055 Raise ValueError if kind is incorrect in label2rgb
  skimage/color/colorlabel.py
  skimage/color/tests/test_colorlabel.py
Labels: action: mrg+1, type: maintenance

#4037 Rename internal function called assert_* -> check_*
  skimage/_shared/testing.py
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/feature/_canny.py
  skimage/feature/_daisy.py
  skimage/feature/blob.py
  skimage/feature/brief.py
  skimage/feature/censure.py
  skimage/feature/orb.py
  skimage/feature/template.py
  skimage/feature/texture.py
  skimage/feature/util.py
  skimage/filters/_gabor.py
  skimage/filters/edges.py
  skimage/filters/lpi_filter.py
  skimage/filters/rank/_percentile.py
  skimage/filters/rank/bilateral.py
  skimage/filters/rank/generic.py
  skimage/filters/ridges.py
  skimage/filters/thresholding.py
  skimage/measure/_moments.py
  skimage/metrics/_adapted_rand_error.py
  skimage/metrics/_structural_similarity.py
  skimage/metrics/_variation_of_information.py
  skimage/metrics/simple_metrics.py
  skimage/morphology/_skeletonize.py
  skimage/segmentation/morphsnakes.py
Labels: action: mrg+1, type: maintenance

#3984 Speed up skimage.feature.peak_local_max
  benchmarks/benchmark_peak_local_max.py
  skimage/feature/peak.py
  skimage/feature/tests/test_peak.py
Labels: action: mrg+1, type: perfomance

#4061 data.load() must be private
  TODO.txt
  skimage/data/__init__.py
Labels: status: needs review, type: maintenance

#4021 Enable packagers to disable failures on warnings.
  INSTALL.rst
  skimage/_shared/_warnings.py
  skimage/_shared/tests/test_warnings.py
Labels: status: needs review

#4060 Fix 3861: Bad indentation on medial_axis (internal cython function)
  skimage/morphology/_skeletonize_cy.pyx
  skimage/morphology/tests/test_skeletonize.py
Labels: 0.15.1, status: needs review, type: bug
