Repository scikit-image/scikit-image, pull requests merged in 2019-04, with the labels that each got.

#3405 Build tool: Generate the release notes programatically by taking all the information from the pull request titles
  doc/release/contribs.py
  requirements/_release_tools.txt
  tools/generate_release_notes.py
Labels: type: maintenance

#3837 Force imageio reader to return NumPy arrays
  skimage/io/_plugins/imageio_plugin.py
  skimage/io/tests/test_imageio.py
Labels: priority: critical, type: bug

#3650 Use user-installed tifffile if available
  skimage/io/_plugins/tifffile_plugin.py
Labels: action: mrg+1

#3841 Address deprecations for 0.16 release
  .gitignore
  TODO.txt
  doc/release/release_dev.rst
  skimage/__init__.py
  skimage/conftest.py
  skimage/data/__init__.py
  skimage/feature/_hog.py
  skimage/io/_io.py
  skimage/morphology/misc.py
  skimage/novice/__init__.py
  skimage/novice/_novice.py
  skimage/novice/tests/__init__.py
  skimage/novice/tests/test_novice.py
  skimage/transform/__init__.py
  skimage/transform/_warps.py
  skimage/transform/pyramids.py
  skimage/transform/seam_carving.py
  skimage/transform/tests/test_pyramids.py
  skimage/transform/tests/test_seam_carving.py
  skimage/transform/tests/test_warps.py
  viewer_examples/viewers/collection_viewer.py
Labels: status: needs review, type: maintenance

#3523 Remove deprecated `skimage.measure.correct_mesh_orientation`
  doc/release/release_dev.rst
  skimage/measure/__init__.py
  skimage/measure/_marching_cubes_classic.py
  skimage/measure/tests/test_marching_cubes.py
Labels: status: needs review, type: maintenance

#3860 Fix `full` parameter description in compare_ssim
  skimage/measure/_structural_similarity.py
Labels: backport: 0.14.x, status: needs review
