Repository scikit-image/scikit-image, pull requests merged in 2020-12, with the labels that each got.

#5099 disable Travis-CI builds
  .travis.yml
Labels: type: infrastructure

#4924 OpenMP support in MSVC
  setup.py
Labels: action: needs review, type: enhancement

#5090 BUG: random_walker: fix import path for umfpack
  skimage/segmentation/random_walker_segmentation.py
  skimage/segmentation/tests/test_random_walker.py
Labels: type: bug

#2815 Restandardize handling of Multi-Image files
  CONTRIBUTORS.txt
  skimage/io/collection.py
  skimage/io/tests/test_collection.py
  skimage/io/tests/test_multi_image.py
Labels: action: mrg+1, type: enhancement

#5131 consistent zoom boundary behavior across SciPy versions
  skimage/segmentation/boundaries.py
Labels: type: bug fix

#5062 Optimize ensure_spacing
  skimage/_shared/coord.py
  skimage/_shared/tests/test_coord.py
Labels: type: perfomance

#5143 Fix large arrays labelling
  skimage/measure/_ccomp.pyx
Labels: type: bug fix

#5145 label2rgb performance fix
  skimage/color/colorlabel.py
Labels: type: perfomance
