Repository scikit-image/scikit-image, pull requests merged in 2020-04, with the labels that each got.

#4543 Documentation: add binder to gallery examples
  .binder/postBuild
  .binder/requirements.txt
  RELEASE.txt
  doc/source/conf.py
Labels: type: documentation, type: new feature

#4556 Fix morphology.flood for F-ordered images
  skimage/morphology/_flood_fill.py
  skimage/morphology/extrema.py
  skimage/morphology/tests/test_flood_fill.py
Labels: action: mrg+1, type: bug fix

#4561 Remove "backport to 0.14" in github template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: infrastructure

#4416 Fix profile_line interpolation errors
  TODO.txt
  skimage/measure/profile.py
  skimage/measure/tests/test_profile.py
Labels: action: mrg+1, type: bug fix, type: involves deprecation

#4565 Disable key check for texlive in travis-mac as a temporary workaround
  TODO.txt
  tools/travis/osx_install.sh
Labels: action: mrg+1, type: infrastructure

#4562 Fix inconsistency in docstring (filters.median)
  skimage/filters/_median.py
Labels: type: documentation

#4424 Add gray2rgba and deprecate RGBA support in gray2rgb
  skimage/color/__init__.py
  skimage/color/colorconv.py
  skimage/color/tests/test_colorconv.py
Labels: action: mrg+1, type: involves deprecation, type: new feature

#4209 Refactor/move neighborhood utility functions in morphology
  TODO.txt
  skimage/morphology/_flood_fill.py
  skimage/morphology/_util.py
  skimage/morphology/extrema.py
  skimage/morphology/tests/test_util.py
Labels: action: mrg+1, type: bug fix, type: maintenance

#4438 Deprecate gray scale image support for rgb2gray
  TODO.txt
  skimage/color/colorconv.py
  skimage/color/tests/test_colorconv.py
Labels: action: mrg+1, type: involves deprecation

#4385 Document geometrical transformations in user guide
  doc/examples/transform/plot_fundamental_matrix.py
  doc/examples/transform/plot_geometric.py
  doc/examples/transform/plot_transform_types.py
  doc/source/conf.py
  doc/source/user_guide.rst
  doc/source/user_guide/geometrical_transform.rst
Labels: action: mrg+1, type: documentation

#4512 Fix bool array save with imageio plugin
  skimage/_shared/testing.py
  skimage/io/_io.py
  skimage/io/tests/test_imageio.py
  skimage/io/tests/test_pil.py
Labels: action: mrg+1, type: bug fix

#4470 Fix bool array warping
  TODO.txt
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/measure/profile.py
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: action: mrg+1, type: bug fix, type: involves deprecation

#4575 section on registration in gallery
  doc/examples/registration/README.txt
  doc/examples/registration/plot_opticalflow.py
  doc/source/conf.py
Labels: type: documentation

#4582 Sort naturally peaks coordinates of same amplitude in peak_local_max
  skimage/feature/corner.py
  skimage/feature/peak.py
Labels: action: mrg+1, type: bug fix

#4591 Do not overwrite data module in plot_skeleton.py
  doc/examples/edges/plot_skeleton.py
Labels: type: documentation

#4578 Add note to remove option in doc config when numpydoc will be patched
  TODO.txt
  doc/source/conf.py
Labels: type: maintenance

#4589 [MRG] Fix Negative eigenvalue in inertia_tensor_eigvals due to floating point precision
  skimage/measure/_moments.py
  skimage/measure/tests/test_moments.py
Labels: type: bug fix

#4593 Recommend cnp.import_array in contribution guide
  CONTRIBUTING.txt
Labels: action: mrg+1, type: documentation

#4467 Complete deprecation of circle in morphsnakes
  TODO.txt
  skimage/draw/_random_shapes.py
  skimage/filters/tests/test_thresholding.py
  skimage/segmentation/morphsnakes.py
  skimage/segmentation/tests/test_morphsnakes.py
Labels: type: maintenance

#4528 Add example code for generating structuring elements.
  doc/examples/numpy_operations/plot_structuring_elements.py
Labels: type: documentation

#4599 Add example of natsort usage in documentation
  doc/source/user_guide/getting_started.rst
Labels: type: documentation

#4502 Move register_translation from skimage.feature to skimage.registration
  TODO.txt
  doc/examples/registration/plot_register_rotation.py
  doc/examples/registration/plot_register_translation.py
  doc/source/user_guide/geometrical_transform.rst
  skimage/feature/__init__.py
  skimage/feature/tests/test_masked_register_translation.py
  skimage/registration/__init__.py
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: action: mrg+1, type: involves deprecation, type: maintenance

#4604 Update min required sphinx version for sphinx-copybutton
  requirements/docs.txt
Labels: priority: critical, type: maintenance

#4496 Fix h_maxima/minima strange behaviors on floating point image input
  skimage/morphology/extrema.py
  skimage/morphology/tests/test_extrema.py
Labels: type: bug fix

#4609 Fix register_translation warning message
  skimage/feature/__init__.py
Labels: priority: critical

#4610 Add notes on deprecation warnings in marching_cube_* and gray2rgb
  TODO.txt
Labels: type: maintenance

#4607 Clarify error message when montaging multichannel nD images and multichannel=False
  skimage/util/_montage.py
Labels: type: maintenance

#4585 Update rescale_intensity to prevent under/overflow and produce proper output dtype
  doc/release/release_dev.rst
  skimage/exposure/_adapthist.py
  skimage/exposure/exposure.py
  skimage/exposure/tests/test_exposure.py
Labels: action: mrg+1, type: bug fix

#4613 Improve loading speed of our gallery by reducing the thumbnail size
  doc/source/conf.py
Labels: type: documentation

#4614 Change label2rgb default background value from -1 to 0
  TODO.txt
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/color/colorlabel.py
  skimage/color/tests/test_colorlabel.py
Labels: type: involves deprecation, type: maintenance

#4628 Fix deprecation warnings due to invalid escape sequences.
  doc/examples/filters/plot_denoise_wavelet.py
  doc/examples/filters/plot_nonlocal_means.py
  doc/ext/plot2rst.py
Labels: type: documentation

#4503 Move masked_register_translation from feature to registration
  TODO.txt
  doc/examples/registration/plot_masked_register_translation.py
  doc/examples/registration/plot_register_translation.py
  skimage/feature/__init__.py
  skimage/registration/_masked_phase_cross_correlation.py
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/data/OriginalX-130Y130.png
  skimage/registration/tests/data/OriginalX130Y130.png
  skimage/registration/tests/data/OriginalX75Y75.png
  skimage/registration/tests/data/TransformedX-130Y130.png
  skimage/registration/tests/data/TransformedX130Y130.png
  skimage/registration/tests/data/TransformedX75Y75.png
  skimage/registration/tests/test_masked_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: action: mrg+1, type: involves deprecation, type: maintenance
