Repository scikit-image/scikit-image, pull requests merged in 2020-11, with the labels that each got.

#4760 Refactor and fix peak_local_max
  doc/release/release_dev.rst
  skimage/_shared/coord.py
  skimage/_shared/tests/test_coord.py
  skimage/feature/peak.py
  skimage/feature/tests/test_corner.py
  skimage/feature/tests/test_peak.py
Labels: action: mrg+1, type: bug fix

#5067 reduce OSX build time so that Travis is happy
  doc/examples/segmentation/plot_rolling_ball.py
  skimage/measure/tests/test_label.py
  skimage/registration/tests/test_ilk.py
  skimage/registration/tests/test_tvl1.py
  tools/travis/osx_install.sh
Labels: action: mrg+1, type: maintenance

#5076 DOC: document the normalized kernel in prewitt_h, prewitt_v
  skimage/filters/edges.py
Labels: type: documentation

#5083 Fix default level computation for find_contours
  .github/workflows/tests.yml
  skimage/measure/_find_contours.py
  skimage/measure/tests/test_find_contours.py
Labels: type: bug
