Repository scikit-image/scikit-image, pull requests merged in 2020-09, with the labels that each got.

#4912 Use sparse cross-correlation to accelerate local thresholding functions
  benchmarks/benchmark_filters.py
  skimage/filters/__init__.py
  skimage/filters/_sparse.py
  skimage/filters/_sparse_cy.pyx
  skimage/filters/setup.py
  skimage/filters/tests/test_correlate.py
  skimage/filters/thresholding.py
Labels: action: needs decision, type: enhancement

#4939 Add fluorescence microscopy images to data registry.
  doc/examples/data/plot_scientific.py
  skimage/data/__init__.py
  skimage/data/_registry.py
  skimage/data/tests/test_data.py
Labels: type: new feature

#4956 CI: Add verbose option to avoid travis timeout for OSX install script
  tools/travis/osx_install.sh
Labels: type: infrastructure

#4927 Fixes to apply_parallel for functions working with multichannel data
  skimage/util/apply_parallel.py
  skimage/util/tests/test_apply_parallel.py
Labels: action: mrg+1, action: needs review, type: enhancement

#4929 Improve description of h_maxima and h_minima functions (#4928)
  skimage/morphology/extrema.py
Labels: action: mrg+1, type: documentation

#4871 Alternative wording for install guide PR #4750
  CONTRIBUTING.txt
  INSTALL.rst
  doc/source/index.rst
  doc/source/release_notes.rst
Labels: action: needs review, type: documentation

#4960 Fix CI: ban sphinx-gallery 0.8.0
  requirements/README.md
  requirements/docs.txt
Labels: type: infrastructure

#4954 Deprecate viewer and skivi script, will be removed in 0.20
  TODO.txt
  doc/source/user_guide/viewer.rst
  skimage/scripts/skivi.py
  skimage/viewer/viewers/core.py
Labels: action: mrg+1, type: involves deprecation, type: maintenance

#4948 Fix corrupt floodfill
  doc/release/release_dev.rst
  skimage/morphology/_flood_fill.py
  skimage/morphology/tests/test_flood_fill.py
Labels: action: mrg+1, type: bug fix

#4965 CI: Use Travis wait improved to avoid timeout for OSX builds
  .travis.yml
  tools/travis/osx_install.sh
Labels: action: mrg+1, type: infrastructure

#4968 MAINT: remove unused imports
  skimage/filters/thresholding.py
  skimage/measure/mc_meta/createluts.py
  skimage/morphology/tests/test_skeletonize_3d.py
  skimage/segmentation/_join.py
  skimage/segmentation/slic_superpixels.py
  skimage/setup.py
  skimage/transform/integral.py
  skimage/util/shape.py
Labels: type: maintenance

#4970 MAINT: Remove conditional import on networkx
  skimage/future/graph/_ncut.py
  skimage/future/graph/graph_cut.py
  skimage/future/graph/tests/test_rag.py
Labels: type: maintenance

#4903 accelerate the masked slic superpixels algorithm
  benchmarks/benchmark_segmentation.py
  doc/release/release_dev.rst
  skimage/segmentation/slic_superpixels.py
Labels: action: mrg+1, type: perfomance

#4966 Accelerate gamma_adjust for uint8 images
  benchmarks/benchmark_exposure.py
  skimage/exposure/exposure.py
Labels: type: perfomance

#4974 Remove warnings/explicit settings on feature, restoration
  TODO.txt
  doc/release/release_dev.rst
  skimage/feature/brief.py
  skimage/feature/corner.py
  skimage/feature/orb.py
  skimage/feature/tests/test_corner.py
  skimage/restoration/_cycle_spin.py
  skimage/restoration/_denoise.py
  skimage/restoration/tests/test_denoise.py
Labels: type: documentation, type: maintenance

#4920 Declare build dependencies
  .circleci/config.yml
  MANIFEST.in
  doc/release/release_dev.rst
  pyproject.toml
  setup.py
Labels: action: mrg+1, type: infrastructure

#4380 Euler number and Crofton perimeter
  doc/examples/segmentation/plot_euler_number.py
  doc/examples/segmentation/plot_perimeters.py
  doc/release/release_dev.rst
  skimage/measure/__init__.py
  skimage/measure/_regionprops.py
  skimage/measure/_regionprops_utils.py
  skimage/measure/tests/test_regionprops.py
Labels: type: new feature

#4984 Add instructions to download the entire dataset
  INSTALL.rst
Labels: type: documentation
