Repository scikit-image/scikit-image, pull requests merged in 2020-07, with the labels that each got.

#4752 Deprecate indices in peak_local_max
  TODO.txt
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/feature/peak.py
  skimage/feature/tests/test_peak.py
Labels: type: involves deprecation, type: maintenance

#4619 added one example to flood fill tutorial
  doc/examples/segmentation/plot_floodfill.py
Labels: action: mrg+1

#4723 Improving register rotation example with notes and references
  doc/examples/registration/plot_register_rotation.py
Labels: type: documentation

#4834 MAINT: import Iterable from collections.abc (Python 3.9 compatibility)
  skimage/segmentation/slic_superpixels.py
Labels: type: maintenance

#4825 DOC: update subpackage descriptions
  skimage/__init__.py
Labels: type: documentation

#4826 style: be explicit when stacking arrays
  skimage/color/adapt_rgb.py
  skimage/color/colorconv.py
  skimage/color/colorlabel.py
  skimage/feature/blob.py
  skimage/feature/corner.py
  skimage/feature/peak.py
  skimage/feature/tests/test_peak.py
  skimage/graph/mcp.py
  skimage/measure/_moments.py
  skimage/measure/fit.py
  skimage/measure/profile.py
  skimage/morphology/_util.py
  skimage/registration/_masked_phase_cross_correlation.py
  skimage/registration/_optical_flow.py
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_tvl1.py
  skimage/restoration/inpaint.py
  skimage/segmentation/morphsnakes.py
Labels: type: maintenance

#4838 Silence a few RuntimeWarnings in the test suite
  skimage/filters/tests/test_thresholding.py
  skimage/restoration/tests/test_denoise.py
Labels: type: maintenance

#4837 Silence several warnings in the test suite
  skimage/color/tests/test_colorconv.py
  skimage/feature/corner.py
  skimage/future/graph/tests/test_rag.py
  skimage/measure/tests/test_profile.py
  skimage/morphology/tests/test_extrema.py
  skimage/viewer/plugins/lineprofile.py
  skimage/viewer/widgets/core.py
Labels: type: maintenance

#4845 DOC: Autoformat docstrings in io.*.py
  skimage/io/__init__.py
  skimage/io/_io.py
  skimage/io/_plugins/fits_plugin.py
  skimage/io/_plugins/gdal_plugin.py
  skimage/io/_plugins/pil_plugin.py
  skimage/io/_plugins/tifffile_plugin.py
  skimage/io/_plugins/util.py
  skimage/io/manage_plugins.py
  skimage/io/sift.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_simpleitk.py
Labels: type: documentation

#4658 Add example for 3D adaptive histogram equalization (AHE)
  doc/examples/color_exposure/plot_adapt_hist_eq_3d.py
Labels: action: mrg+1, type: documentation

#4857 Document how to contribute a gallery example.
  CONTRIBUTING.txt
Labels: type: documentation
