Repository scikit-image/scikit-image, pull requests merged in 2020-05, with the labels that each got.

#4627 Userguide: add a visualization chapter
  doc/source/user_guide.rst
  doc/source/user_guide/visualization.rst
Labels: type: documentation

#4632 add docstring examples for moments_hu and centroid
  skimage/measure/_moments.py
Labels: type: documentation

#4218 Add Minkowski distance metric support to corner_peak
  skimage/feature/corner.py
  skimage/feature/tests/test_brief.py
  skimage/feature/tests/test_corner.py
  skimage/feature/tests/test_match.py
  skimage/feature/tests/test_orb.py
Labels: action: mrg+1, type: new feature

#4418 Add nD support to colorconv module
  skimage/color/colorconv.py
  skimage/color/colorlabel.py
  skimage/color/tests/test_colorconv.py
  skimage/color/tests/test_colorlabel.py
Labels: action: mrg+1, type: enhancement, type: involves deprecation

#4638 Misleading "ValueError: Input array has to be either 3- or 4-dimensional" in montage
  skimage/util/_montage.py
Labels: priority: critical

#4639 Fix broken link
  skimage/color/colorconv.py
Labels: type: maintenance

#3824 J-invariant denoising
  doc/examples/filters/plot_j_invariant.py
  doc/examples/filters/plot_j_invariant_tutorial.py
  skimage/restoration/__init__.py
  skimage/restoration/j_invariant.py
  skimage/restoration/tests/test_j_invariant.py
Labels: status: needs review, type: new feature

#3850 Add mask support for slic
  TODO.txt
  benchmarks/benchmark_segmentation.py
  doc/examples/segmentation/plot_mask_slic.py
  skimage/segmentation/_slic.pyx
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_random_walker.py
  skimage/segmentation/tests/test_slic.py
Labels: action: mrg+1, type: involves deprecation, type: new feature

#4653 DOC: fix broken DOI links
  doc/examples/edges/plot_active_contours.py
  skimage/morphology/max_tree.py
Labels: type: documentation

#4228 MAINT+DOC update RELEASE.txt
  RELEASE.txt
Labels: type: documentation

#4641 DOC: docstring enhancements for Marching cube and find_contours
  skimage/measure/_find_contours.py
  skimage/measure/_marching_cubes_lewiner.py
Labels: type: documentation

#4676 Adding new default values to functions on doc/examples/segmentation/plot_ncut
  doc/examples/segmentation/plot_ncut.py
Labels: type: documentation

#4683 Fix slic float32 support regression
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_slic.py
Labels: priority: critical, type: bug fix

#4685 Add BRIEF float32 support
  skimage/feature/brief_cy.pyx
  skimage/feature/tests/test_brief.py
Labels: type: bug fix

#4684 Add ORB float32 support
  skimage/feature/corner_cy.pyx
  skimage/feature/orb.py
  skimage/feature/tests/test_orb.py
Labels: type: bug fix

#4691 Perform todo tasks for 0.17!
  TODO.txt
  skimage/data/__init__.py
  skimage/filters/_median.py
  skimage/filters/ridges.py
  skimage/filters/tests/test_median.py
  skimage/io/_plugins/fits_plugin.py
  skimage/io/_plugins/gdal_plugin.py
  skimage/io/_plugins/tifffile_plugin.py
  skimage/io/collection.py
  skimage/morphology/_skeletonize.py
Labels: status: needs review

#4713 Specify the encoding of files opened in the setup phase
  setup.py
Labels: backport: 0.17.x

#4724 Remove duplicate fused type definition
  skimage/_shared/transform.pxd
  skimage/_shared/transform.pyx
  skimage/feature/_cascade.pyx
  skimage/feature/_haar.pxd
  skimage/feature/_haar.pyx
  skimage/feature/_texture.pxd
  skimage/feature/_texture.pyx
Labels: type: maintenance

#4690 Perform some todo tasks for 0.18
  TODO.txt
  doc/examples/edges/plot_active_contours.py
  skimage/color/__init__.py
  skimage/color/colorconv.py
  skimage/data/__init__.py
  skimage/measure/__init__.py
  skimage/measure/_structural_similarity.py
  skimage/measure/simple_metrics.py
  skimage/measure/tests/test_simple_metrics.py
  skimage/morphology/convex_hull.py
  skimage/morphology/tests/test_convex_hull.py
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/tests/test_active_contour_model.py
  skimage/transform/__init__.py
  skimage/transform/histogram_matching.py
  skimage/transform/radon_transform.py
Labels: action: mrg+1, status: needs review

#4631 random walker: Display a warning when the probability is outsite [0,1] for a given tol
  skimage/segmentation/random_walker_segmentation.py
  skimage/segmentation/tests/test_random_walker.py
Labels: action: mrg+1, type: enhancement

#4730 Blacklist cython version 0.29.18
  requirements/README.md
  requirements/build.txt
Labels: type: maintenance

#4731 Fix CI failures related to conversion of np.floating to dtype
  skimage/util/dtype.py
Labels: type: maintenance

#4735 Fix Ci failures related to array ragged input numpy deprecation
  skimage/transform/radon_transform.py
Labels: action: mrg+1, type: maintenance

#4733 Add versionadded for new scalar type support for "scale" param in transform.AffineTransform
  skimage/transform/_geometric.py
Labels: type: documentation

#4740 Unwrap decorators before resolving link to source (sphinx.ext.linkcode)
  doc/source/conf.py
Labels: type: bug fix, type: documentation

#4725 Fixing color/colorconv/separate_stains
  skimage/color/colorconv.py
Labels: action: mrg+1, type: bug fix

#4746 Highlight all source lines with HTML doc "source" links (sphinx.ext.linkcode)
  doc/source/conf.py
Labels: type: documentation

#4745 Backport NumPy deprecation fixes to v0.17.x
  skimage/transform/radon_transform.py
  skimage/util/dtype.py
Labels: backport: 0.17.x, type: maintenance
