Repository scikit-image/scikit-image, pull requests merged in 2020-06, with the labels that each got.

#4771 Fix random_walker regression
  skimage/segmentation/random_walker_segmentation.py
  skimage/segmentation/tests/test_random_walker.py
Labels: type: bug fix

#4747 Turn checklist boxes into bullet points inside the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: infrastructure

#4798 Remove additional "::" to make plot directive work.
  doc/source/user_guide/numpy_images.rst
Labels: type: bug fix, type: documentation
