Repository scikit-image/scikit-image, pull requests merged in 2020-10, with the labels that each got.

#4913 Replacing data/camera.png due to copyright
  doc/examples/color_exposure/plot_tinting_grayscale_images.py
  doc/examples/features_detection/plot_glcm.py
  skimage/data/__init__.py
  skimage/data/_registry.py
  skimage/data/camera.png
  skimage/exposure/exposure.py
  skimage/exposure/tests/test_exposure.py
  skimage/exposure/tests/test_histogram_matching.py
  skimage/feature/tests/test_canny.py
  skimage/filters/tests/test_ridges.py
  skimage/filters/tests/test_thresholding.py
  skimage/io/tests/test_collection.py
  skimage/measure/entropy.py
  skimage/measure/tests/test_structural_similarity.py
  skimage/metrics/tests/test_simple_metrics.py
  skimage/metrics/tests/test_structural_similarity.py
  skimage/restoration/tests/camera_rl.npy
  skimage/restoration/tests/camera_unsup.npy
  skimage/restoration/tests/camera_unsup2.npy
  skimage/restoration/tests/camera_wiener.npy
  skimage/restoration/tests/test_restoration.py
  skimage/util/tests/test_random_noise.py
  skimage/viewer/tests/test_plugins.py
Labels: action: work in progress, priority: critical, type: involves deprecation, type: maintenance

#4997 Let tifffile.imread handle additional keyword arguments
  skimage/io/_plugins/tifffile_plugin.py
Labels: action: mrg+1, type: enhancement

#4161 Add the iterative Lucas-Kanade (iLK) optical flow method
  benchmarks/benchmark_registration.py
  doc/examples/registration/plot_opticalflow.py
  skimage/registration/__init__.py
  skimage/registration/_optical_flow.py
  skimage/registration/_optical_flow_utils.py
  skimage/registration/tests/test_ilk.py
Labels: action: mrg+1, action: needs review, type: new feature

#5003 Update sphinx mapping for sklearn and numpy
  doc/source/conf.py
Labels: type: maintenance

#4898 Changelog back-log
  doc/release/release_dev.rst
Labels: action: monitor, type: documentation

#4298 Manage iradon input and output data type
  skimage/transform/radon_transform.py
  skimage/transform/tests/test_radon_transform.py
Labels: action: mrg+1, type: involves deprecation

#5029 Fix point_in_polygon
  skimage/_shared/geometry.pxd
  skimage/_shared/geometry.pyx
  skimage/draw/_draw.pyx
  skimage/draw/_random_shapes.py
  skimage/draw/draw.py
  skimage/draw/tests/test_draw.py
  skimage/draw/tests/test_polygon2mask.py
  skimage/measure/_pnpoly.pyx
  skimage/measure/tests/test_regionprops.py
  skimage/morphology/tests/test_convex_hull.py
  skimage/viewer/tests/test_plugins.py
Labels: action: mrg+1, type: bug fix

#3329 Fix #3327: Add functionality for benchmark coverage
  Makefile
  setup.cfg
Labels: action: needs review, type: maintenance

#4739 trainable segmentation (algorithm + gallery example)
  doc/examples/segmentation/plot_trainable_segmentation.py
  skimage/data/__init__.py
  skimage/data/_registry.py
  skimage/data/tests/test_data.py
  skimage/feature/__init__.py
  skimage/feature/_basic_features.py
  skimage/feature/tests/test_basic_features.py
  skimage/future/__init__.py
  skimage/future/tests/test_trainable_segmentation.py
  skimage/future/trainable_segmentation.py
Labels: type: discussion, type: documentation

#4753 Deprecate (min_distance < 1) and (footprint.size < 2) in peak_local_max
  skimage/feature/peak.py
  skimage/feature/tests/test_peak.py
Labels: type: maintenance

#4828 Fix equalize_adapthist (CLAHE) for clip value 1.0, fix docstrings
  skimage/exposure/_adapthist.py
  skimage/exposure/tests/test_exposure.py
Labels: type: enhancement

#4851 Add rolling ball algorithm for background substraction
  CONTRIBUTORS.txt
  benchmarks/benchmark_restoration.py
  doc/examples/segmentation/plot_rolling_ball.py
  skimage/morphology/__init__.py
  skimage/morphology/setup.py
  skimage/restoration/__init__.py
  skimage/restoration/_rolling_ball_cy.pyx
  skimage/restoration/rolling_ball.py
  skimage/restoration/setup.py
  skimage/restoration/tests/test_rolling_ball.py
Labels: type: new feature
