Repository scikit-image/scikit-image, pull requests merged in 2020-02, with the labels that each got.

#4395 _adapthist module refactoring and memory use reduction
  TODO.txt
  skimage/exposure/_adapthist.py
Labels: action: mrg+1, type: enhancement

#3609 Document tophat in the gallery
  doc/examples/filters/plot_tophat.py
  skimage/morphology/grey.py
Labels: type: documentation

#4437 Fix use_quantiles behavior in canny
  skimage/feature/_canny.py
  skimage/feature/tests/test_canny.py
Labels: action: mrg+1, type: bug fix

#4439 Deprecate non RGB image conversion in rgb2gray
  TODO.txt
  skimage/color/colorconv.py
  skimage/color/tests/test_colorconv.py
Labels: action: mrg+1, type: involves deprecation

#4441 Remove redundant checks for threshold values in Canny
  skimage/feature/_canny.py
Labels: type: maintenance

#4423 Deprecate rank.tophat and rank.bottomhat
  TODO.txt
  skimage/filters/rank/generic.py
  skimage/filters/rank/tests/test_rank.py
Labels: type: involves deprecation

#4440 Deprecate non gray scale image conversion in gray2rgb
  skimage/color/colorconv.py
  skimage/color/tests/test_colorconv.py
Labels: type: involves deprecation

#4322 Fix denoise_nl_means data type management
  benchmarks/benchmark_restoration.py
  skimage/_shared/fast_exp.h
  skimage/_shared/fast_exp.pxd
  skimage/_shared/fast_exp.pyx
  skimage/_shared/setup.py
  skimage/_shared/tests/test_fast_exp.py
  skimage/restoration/_nl_means_denoising.pyx
  skimage/restoration/non_local_means.py
  skimage/restoration/setup.py
  skimage/restoration/tests/test_denoise.py
Labels: action: mrg+1

#4443 Move watershed from morphology to segmentation
  doc/examples/segmentation/plot_compact_watershed.py
  doc/examples/segmentation/plot_join_segmentations.py
  doc/examples/segmentation/plot_marked_watershed.py
  doc/examples/segmentation/plot_watershed.py
  doc/source/user_guide/tutorial_segmentation.rst
  skimage/morphology/__init__.py
  skimage/morphology/_deprecated.py
  skimage/morphology/setup.py
  skimage/segmentation/__init__.py
  skimage/segmentation/_watershed.py
  skimage/segmentation/_watershed_cy.pyx
  skimage/segmentation/heap_general.pxi
  skimage/segmentation/heap_watershed.pxi
  skimage/segmentation/setup.py
  skimage/segmentation/tests/test_watershed.py
Labels: action: mrg+1, type: involves deprecation, type: maintenance

#4449 Standardize colon usage in docstrings
  skimage/color/colorconv.py
  skimage/data/__init__.py
  skimage/draw/draw.py
  skimage/filters/_unsharp_mask.py
  skimage/filters/thresholding.py
  skimage/graph/spath.py
  skimage/morphology/_deprecated.py
  skimage/morphology/max_tree.py
  skimage/segmentation/_clear_border.py
  skimage/segmentation/_watershed.py
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/boundaries.py
  skimage/segmentation/slic_superpixels.py
  skimage/transform/hough_transform.py
Labels: type: documentation

#4446 Multichannel support for denoise_tv_bregman (#4427)
  skimage/restoration/_denoise.py
  skimage/restoration/tests/test_denoise.py
Labels: action: mrg+1

#4158 Deprecate filter argument in iradon due to clash with python keyword
  TODO.txt
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/transform/radon_transform.py
  skimage/transform/tests/test_radon_transform.py
Labels: action: mrg+1, type: involves deprecation, type: maintenance

#4453 Set minimum tifffile version to fix numpy incompatibility
  requirements/optional.txt
Labels: action: mrg+1, type: maintenance

#4452 Bump numpy version to 1.15.1
  TODO.txt
  requirements/build.txt
  requirements/default.txt
  skimage/filters/tests/test_lpi_filter.py
  skimage/restoration/tests/test_denoise.py
  skimage/segmentation/tests/test_random_walker.py
Labels: action: mrg+1, type: maintenance

#4471 Fix bool array profile_line
  TODO.txt
  skimage/measure/profile.py
  skimage/measure/tests/test_profile.py
Labels: action: mrg+1, type: bug fix, type: involves deprecation

#4480 reduce runtime of non-local means tests
  skimage/restoration/tests/test_denoise.py
Labels: type: maintenance
