Repository scikit-image/scikit-image, pull requests merged in 2021-03, with the labels that each got.

#5207 Add hausdorff points
  benchmarks/benchmark_metrics.py
  doc/examples/segmentation/plot_hausdorff_distance.py
  skimage/metrics/__init__.py
  skimage/metrics/set_metrics.py
  skimage/metrics/tests/test_set_metrics.py
Labels: action: mrg+1, type: new feature

#5245 updated regionprops_table test for iterable properties
  skimage/measure/tests/test_regionprops.py
Labels: action: mrg+1

#5256 Fix rescale using small scale factor
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: action: mrg+1, type: bug fix

#5196 Update structure_tensor docstring to include per-axis sigma.
  skimage/feature/corner.py
  skimage/feature/tests/test_corner.py
Labels: action: mrg+1

#5265 Deprecate input kwarg in label
  TODO.txt
  skimage/measure/_label.py
Labels: action: mrg+1, type: involves deprecation

#5264 Fix skimage.measure.label segfault
  skimage/measure/_ccomp.pyx
  skimage/measure/tests/test_label.py
Labels: action: mrg+1, type: bug fix

#5271 Watershed: consider connectivity when calculating markers.
  skimage/segmentation/_watershed.py
  skimage/segmentation/tests/test_watershed.py
Labels: action: mrg+1, type: bug fix

#5200 Add float32 support to moments_hu
  skimage/measure/_moments.py
  skimage/measure/_moments_cy.pyx
  skimage/measure/tests/test_moments.py
Labels: action: mrg+1, type: enhancement

#5280 Fix dtype info in documentation for watershed.
  skimage/segmentation/_watershed.py
Labels: type: documentation

#5283 Fixup test for INSTALL_FROM_SDIST
  .github/workflows/tests.yml
Labels: action: mrg+1

#5269 Mention possible filters in radon_transform -> filtered-back-projection
  doc/examples/transform/plot_radon_transform.py
Labels: action: mrg+1, type: documentation

#5293 MAINT: use internal function for noise + clarify code in canny example
  doc/examples/edges/plot_canny.py
Labels: type: documentation

#5257 Improve salt and pepper noise performance
  benchmarks/benchmark_util.py
  skimage/util/noise.py
  skimage/util/tests/test_random_noise.py
Labels: action: mrg+1, type: perfomance

#5306 Doc: make more comprehensive "see also" sections in filters + fix
  skimage/filters/edges.py
Labels: type: documentation
