Repository scikit-image/scikit-image, pull requests merged in 2021-05, with the labels that each got.

#5367 DOC: remove entries that are duplicate with release_0.18.rst
  doc/release/release_dev.rst
Labels: type: documentation

#5340 MAINT: update minimal NumPy version
  TODO.txt
  pyproject.toml
  requirements/build.txt
  requirements/default.txt
  skimage/draw/draw_nd.py
  skimage/exposure/tests/test_exposure.py
Labels: type: maintenance

#5373 single precision support in skimage.segmentation
  skimage/segmentation/_chan_vese.py
  skimage/segmentation/_quickshift.py
  skimage/segmentation/_quickshift_cy.pyx
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/boundaries.py
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_active_contour_model.py
  skimage/segmentation/tests/test_boundaries.py
  skimage/segmentation/tests/test_chan_vese.py
  skimage/segmentation/tests/test_quickshift.py
  skimage/segmentation/tests/test_random_walker.py
  skimage/segmentation/tests/test_slic.py
Labels: action: mrg+1, type: enhancement

#5378 Update pip during dev environment installation
  INSTALL.rst
Labels: type: documentation, type: installation

#5287 multichannel to channel_axis (4 of 6): metrics and measure
  skimage/_shared/utils.py
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_structural_similarity.py
  skimage/metrics/_structural_similarity.py
  skimage/metrics/tests/test_structural_similarity.py
Labels: action: mrg+1, api

#5385 rename greycomatrix and greycoprops. prefer "gray" in documentation
  doc/examples/applications/plot_human_mitosis.py
  doc/examples/applications/plot_morphology.py
  doc/examples/color_exposure/plot_adapt_hist_eq_3d.py
  doc/examples/features_detection/plot_glcm.py
  doc/examples/features_detection/plot_windowed_histogram.py
  doc/source/user_guide/tutorial_segmentation.rst
  skimage/feature/__init__.py
  skimage/feature/tests/test_texture.py
  skimage/feature/texture.py
  skimage/filters/rank/_percentile.py
  skimage/filters/rank/bilateral.py
  skimage/filters/thresholding.py
  skimage/io/_plugins/fits_plugin.py
  skimage/io/_plugins/matplotlib_plugin.py
  skimage/io/tests/test_plugin_util.py
  skimage/morphology/binary.py
  skimage/morphology/extrema.py
  skimage/morphology/grey.py
Labels: action: mrg+1, api, type: involves deprecation, type: maintenance

#5394 Speed up find_local_max when given a finite num_peaks
  skimage/_shared/coord.py
  skimage/feature/peak.py
Labels: action: mrg+1

#5386 morphology: rename files with "grey" in filename
  skimage/filters/rank/tests/test_rank.py
  skimage/morphology/__init__.py
  skimage/morphology/_grayreconstruct.pyx
  skimage/morphology/extrema.py
  skimage/morphology/gray.py
  skimage/morphology/grayreconstruct.py
  skimage/morphology/grey.py
  skimage/morphology/greyreconstruct.py
  skimage/morphology/setup.py
  skimage/morphology/tests/test_binary.py
  skimage/morphology/tests/test_gray.py
  skimage/morphology/tests/test_reconstruction.py
Labels: action: mrg+1, api, type: involves deprecation, type: maintenance

#5399 Allow rank filters to work with nogil
  skimage/filters/rank/core_cy.pyx
  skimage/filters/rank/core_cy_3d.pyx
Labels: performance

#5400 release the GIL in denoise_tv_bregman and denoise_bilateral
  skimage/restoration/_denoise_cy.pyx
Labels: performance

#5393 update sigma_color description in denoise_bilateral
  skimage/restoration/_denoise.py
Labels: action: mrg+1

#5219 single precision support in skimage.restoration module
  TODO.txt
  skimage/restoration/_denoise.py
  skimage/restoration/deconvolution.py
  skimage/restoration/inpaint.py
  skimage/restoration/j_invariant.py
  skimage/restoration/non_local_means.py
  skimage/restoration/rolling_ball.py
  skimage/restoration/tests/test_denoise.py
  skimage/restoration/tests/test_inpaint.py
  skimage/restoration/tests/test_j_invariant.py
  skimage/restoration/tests/test_restoration.py
  skimage/restoration/tests/test_rolling_ball.py
  skimage/restoration/uft.py
Labels: action: mrg+1, type: enhancement
