Repository scikit-image/scikit-image, pull requests merged in 2021-09, with the labels that each got.

#5461 Fix computation of the correlation in register.phase_cross_correlation
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: action: mrg+1, type: bug fix

#5546 Fix io.imread behavior with pathlib.Path inputs
  skimage/io/_io.py
  skimage/io/tests/test_io.py
Labels: action: mrg+1, type: bug fix

#5521 fix wheels for macOS 10.13
  .github/workflows/wheel_tests_and_release.yml
Labels: type: infrastructure

#5543 Support user-supplied histogram in threshold_multiotsu
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: type: enhancement, action: mrg+1

#5190 Fix floating point rounding in CircleModel.estimate
  TODO.txt
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: action: mrg+1, type: bug fix

#5050 threshold_li: fast, histogram-based code path for integer images
  benchmarks/benchmark_filters.py
  skimage/filters/thresholding.py
Labels: action: mrg+1, type: perfomance

#5551 Fix hidden attribute 'offsets' in skimage.graph.MCP
  skimage/graph/_mcp.pxd
  skimage/graph/tests/test_mcp.py
Labels: type: bug fix

#5354 single precision support in skimage.filters
  TODO.txt
  skimage/filters/_fft_based.py
  skimage/filters/_gabor.py
  skimage/filters/_gaussian.py
  skimage/filters/_sparse.py
  skimage/filters/_unsharp_mask.py
  skimage/filters/_window.py
  skimage/filters/edges.py
  skimage/filters/lpi_filter.py
  skimage/filters/rank/tests/test_rank.py
  skimage/filters/ridges.py
  skimage/filters/tests/test_correlate.py
  skimage/filters/tests/test_edges.py
  skimage/filters/tests/test_fft_based.py
  skimage/filters/tests/test_gabor.py
  skimage/filters/tests/test_gaussian.py
  skimage/filters/tests/test_lpi_filter.py
  skimage/filters/tests/test_median.py
  skimage/filters/tests/test_ridges.py
  skimage/filters/tests/test_thresholding.py
  skimage/filters/tests/test_unsharp_mask.py
  skimage/filters/tests/test_window.py
  skimage/filters/thresholding.py
  skimage/measure/tests/test_moments.py
  skimage/segmentation/_chan_vese.py
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/boundaries.py
  skimage/transform/integral.py
Labels: type: enhancement, action: mrg+1, api

#5556 Update the user guide to use channel_axis rather than multichannel
  doc/source/glossary.md
  doc/source/user_guide/data_types.rst
  doc/source/user_guide/numpy_images.rst
  doc/source/user_guide/tutorial_parallelization.rst
  doc/source/user_guide/visualization.rst
Labels: type: documentation

#5526 Add fixture enforcing SimpleITK I/O in test_simpleitk.py
  skimage/io/tests/test_simpleitk.py
Labels: type: maintenance, action: mrg+1

#5365 Add stitching gallery example
  doc/examples/registration/plot_stitching.py
Labels: type: documentation, action: mrg+1

#5560 Add hyperlinks to referenced documentation places.
  doc/examples/registration/plot_stitching.py
Labels: type: documentation

#5450 prefer use of new-style NumPy random API in tests
  doc/examples/filters/plot_inpaint.py
  skimage/future/graph/graph_cut.py
  skimage/measure/tests/test_fit.py
  skimage/metrics/tests/test_structural_similarity.py
  skimage/registration/tests/test_ilk.py
  skimage/registration/tests/test_tvl1.py
  skimage/restoration/tests/test_denoise.py
  skimage/restoration/tests/test_inpaint.py
  skimage/restoration/tests/test_restoration.py
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_quickshift.py
  skimage/segmentation/tests/test_slic.py
  skimage/transform/tests/test_integral.py
Labels: type: maintenance, action: mrg+1

#5504 Mention commit messages in the contribution guidelines.
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.txt
  doc/source/core_developer.md
Labels: type: documentation, action: mrg+1

#5559 fix phase_cross_correlation for 3D with reference masks
  skimage/registration/_masked_phase_cross_correlation.py
  skimage/registration/tests/test_masked_phase_cross_correlation.py
Labels: type: bug fix

#5550 Support nD images and labels in label2rgb
  skimage/color/colorlabel.py
  skimage/color/tests/test_colorlabel.py
Labels: type: enhancement, action: mrg+1

#5565 Update branching instructions to change the location of the pooch repo
  RELEASE.txt
Labels: type: documentation

#5475 Add draft SKIP3: transition to scikit-image 1.0
  doc/source/skips/3-transition-to-v1.rst
  doc/source/skips/index.md
Labels: type: discussion

#5569 Clarify 2D vs nD in skimage.feature.corner docstrings
  skimage/feature/corner.py
Labels: type: documentation

#5582 refactor gabor_kernel for efficiency
  skimage/filters/_gabor.py
Labels: action: mrg+1, type: perfomance

#5580 remove use of apply_along_axes from greycomatrix & greycoprops
  skimage/feature/texture.py
Labels: type: maintenance, action: mrg+1
