Repository scikit-image/scikit-image, pull requests merged in 2021-04, with the labels that each got.

#5303 Use manylinux2010 for python 3.9+
  .github/workflows/cibuildwheel.yml
Labels: type: infrastructure

#5315 allow either SyntaxError or OSError for truncated JPG
  skimage/io/tests/test_imageio.py
Labels: type: bug fix, type: maintenance

#5319 Fix sphinx: role already being registered
  doc/ext/doi_role.py
Labels: action: mrg+1, type: bug fix, type: documentation

#5317 DOC: Attempt at autoformatting docstrings in morphology/*
  skimage/morphology/_deprecated.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/_util.py
  skimage/morphology/binary.py
  skimage/morphology/extrema.py
  skimage/morphology/grey.py
  skimage/morphology/greyreconstruct.py
  skimage/morphology/max_tree.py
  skimage/morphology/selem.py
Labels: type: documentation

#5284 multichannel to channel_axis (1 of 6): features and draw
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/draw/_random_shapes.py
  skimage/draw/tests/test_random_shapes.py
  skimage/exposure/tests/test_histogram_matching.py
  skimage/feature/_basic_features.py
  skimage/feature/_hog.py
  skimage/feature/tests/test_basic_features.py
  skimage/feature/tests/test_censure.py
  skimage/feature/tests/test_hog.py
  skimage/util/tests/test_apply_parallel.py
  skimage/util/tests/test_montage.py
Labels: api

#5322 avoid importing or calling functions from ndimage submodules
  skimage/filters/_unsharp_mask.py
  skimage/morphology/selem.py
  skimage/registration/_optical_flow.py
  skimage/restoration/inpaint.py
Labels: type: maintenance

#5329 fix multichannel intensity_image extra_properties, addresses #5324
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: action: mrg+1, type: enhancement

#5313 Re-enable skipped Qt tests
  skimage/viewer/tests/test_utils.py
  skimage/viewer/tests/test_widgets.py
Labels: module: viewer, type: infrastructure

#5327 Fix warp output dtype when order=0
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: action: mrg+1, type: bug fix

#5344 single precision support in moments functions
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/measure/_moments.py
  skimage/measure/tests/test_moments.py
Labels: action: mrg+1, api, type: enhancement

#5347 Display plotly figures from gallery example even when running script at CLI.
  doc/examples/applications/plot_3d_interaction.py
  doc/source/conf.py
Labels: action: mrg+1

#5343 enable pip and skimage.data caching on Azure
  azure-pipelines.yml
Labels: action: mrg+1, type: infrastructure

#5351 Azure CI caching fix (v2)
  azure-pipelines.yml
Labels: type: infrastructure

#5355 Fix cython warnings
  skimage/_shared/fast_exp.h
  skimage/_shared/fast_exp.pxd
  skimage/_shared/fast_exp.pyx
  skimage/filters/rank/core_cy_3d.pyx
Labels: action: mrg+1, type: maintenance, type: perfomance

#5348 channel_as_last_axis decorator fix
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
Labels: type: bug

#5338 run face classification gallery example with a single thread
  doc/examples/applications/plot_haar_extraction_selection_classification.py
Labels: action: mrg+1, type: documentation, type: maintenance

#5320 Fix sphinx layout to make the search engine working for latest sphinx versions
  doc/source/themes/scikit-image/layout.html
  doc/source/themes/scikit-image/search.html
  requirements/docs.txt
Labels: action: mrg+1, type: documentation, type: maintenance

#5350 DEV: fix CircleCI caching
  .circleci/config.yml
Labels: type: maintenance

#5356 Draw node IDs in RAG example
  doc/examples/segmentation/plot_rag.py
Labels: type: bug fix

#5240 Fast biharmonic inpainting
  benchmarks/benchmark_restoration.py
  doc/examples/filters/plot_inpaint.py
  skimage/restoration/_inpaint.pyx
  skimage/restoration/inpaint.py
  skimage/restoration/setup.py
  skimage/restoration/tests/test_inpaint.py
Labels: type: perfomance

#5358 Upgrading Pillow version to 6.1.0
  TODO.txt
  requirements/default.txt
  skimage/io/_plugins/pil_plugin.py
  skimage/io/collection.py
Labels: type: discussion, type: maintenance
