Repository scikit-image/scikit-image, pull requests merged in 2021-07, with the labels that each got.

#3541 HOG returns incorrect features if pixels_per_cell is odd
  skimage/feature/_hoghistogram.pyx
  skimage/feature/tests/test_hog.py
Labels: action: needs review, type: bug fix

#5424 Add benchmark checks to CI
  .github/workflows/benchmarks.yml
  .github/workflows/tests.yml
  asv.conf.json
  azure-pipelines.yml
  benchmarks/README_CI.md
  benchmarks/__init__.py
  benchmarks/benchmark_registration.py
  benchmarks/benchmark_restoration.py
  benchmarks/benchmark_transform_warp.py
  benchmarks/benchmark_util.py
  requirements/test.txt
Labels: run-benchmark, type: infrastructure, type: perfomance

#5444 standardize on num_iter and max_num_iter keyword names
  doc/examples/edges/plot_skeleton.py
  doc/examples/filters/plot_deconvolution.py
  doc/examples/segmentation/plot_chan_vese.py
  doc/examples/segmentation/plot_join_segmentations.py
  doc/examples/segmentation/plot_metrics.py
  doc/examples/segmentation/plot_morphsnakes.py
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/tests/test_skeletonize.py
  skimage/restoration/_denoise.py
  skimage/restoration/_denoise_cy.pyx
  skimage/restoration/deconvolution.py
  skimage/restoration/tests/test_denoise.py
  skimage/restoration/tests/test_restoration.py
  skimage/segmentation/_chan_vese.py
  skimage/segmentation/_slic.pyx
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/morphsnakes.py
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_active_contour_model.py
  skimage/segmentation/tests/test_chan_vese.py
  skimage/segmentation/tests/test_morphsnakes.py
  skimage/segmentation/tests/test_slic.py
Labels: action: mrg+1, api, type: maintenance

#5466 readd gallery testing condition
  azure-pipelines.yml
Labels: type: infrastructure

#5446 disable calls to plotly.io.show when running on Azure
  azure-pipelines.yml
  doc/examples/applications/plot_3d_structure_tensor.py
Labels: type: infrastructure

#4342 Refactor canny edge detector
  benchmarks/benchmark_feature.py
  skimage/feature/_canny.py
  skimage/feature/tests/test_canny.py
Labels: action: mrg+1, type: maintenance

#5220 single precision support in skimage.metrics module
  skimage/metrics/_structural_similarity.py
  skimage/metrics/simple_metrics.py
  skimage/metrics/tests/test_set_metrics.py
  skimage/metrics/tests/test_simple_metrics.py
  skimage/metrics/tests/test_structural_similarity.py
Labels: action: mrg+1, type: enhancement

#5395 fix wrong error for metric.structural_similarity when image is too small
  skimage/metrics/_structural_similarity.py
  skimage/metrics/tests/test_structural_similarity.py
Labels: action: mrg+1

#5467 Fix behavior of is_low_contrast for boolean inputs
  skimage/exposure/exposure.py
  skimage/exposure/tests/test_exposure.py
Labels: action: mrg+1, type: bug fix

#5480 Fix wrong syntax for the string argument to ValueError
  skimage/metrics/_structural_similarity.py
Labels: action: mrg+1, sprint

#5479 .format() coverted to f-strings in segmentation subpackage
  skimage/segmentation/_clear_border.py
  skimage/segmentation/_watershed.py
  skimage/segmentation/random_walker_segmentation.py
Labels: sprint, type: maintenance

#5443 support single precision in skimage.color
  skimage/color/colorconv.py
  skimage/color/colorlabel.py
  skimage/color/delta_e.py
  skimage/color/tests/test_colorconv.py
  skimage/color/tests/test_colorlabel.py
  skimage/color/tests/test_delta_e.py
Labels: action: mrg+1, api, type: enhancement

#5485 remove _fast_pad utility (now that we require NumPy >= 1.17)
  TODO.txt
  skimage/morphology/_flood_fill.py
  skimage/morphology/_util.py
  skimage/morphology/extrema.py
Labels: action: mrg+1, type: maintenance

#5305 Precompute histogram to speed up try_all_threshold
  skimage/filters/thresholding.py
Labels: action: mrg+1, type: perfomance
