Repository scikit-image/scikit-image, pull requests merged in 2021-06, with the labels that each got.

#5392 Integral_image: promote floating point inputs to double by default
  skimage/transform/integral.py
  skimage/transform/tests/test_integral.py
Labels: type: enhancement

#5353 single precision support in skimage.features
  skimage/feature/_daisy.py
  skimage/feature/_hessian_det_appx.pyx
  skimage/feature/_hog.py
  skimage/feature/_hoghistogram.pyx
  skimage/feature/blob.py
  skimage/feature/corner.py
  skimage/feature/corner_cy.pyx
  skimage/feature/setup.py
  skimage/feature/template.py
  skimage/feature/tests/test_basic_features.py
  skimage/feature/tests/test_blob.py
  skimage/feature/tests/test_canny.py
  skimage/feature/tests/test_cascade.py
  skimage/feature/tests/test_corner.py
  skimage/feature/tests/test_daisy.py
  skimage/feature/tests/test_haar.py
  skimage/feature/tests/test_hog.py
  skimage/feature/tests/test_orb.py
  skimage/feature/tests/test_peak.py
  skimage/feature/tests/test_template.py
  skimage/feature/tests/test_texture.py
  skimage/feature/texture.py
  skimage/feature/util.py
Labels: action: mrg+1, api, type: enhancement

#5372 improved single precision support in skimage.transform
  skimage/_shared/utils.py
  skimage/transform/_warps.py
  skimage/transform/tests/test_geometric.py
  skimage/transform/tests/test_hough_transform.py
  skimage/transform/tests/test_integral.py
  skimage/transform/tests/test_pyramids.py
  skimage/transform/tests/test_radon_transform.py
  skimage/transform/tests/test_warps.py
Labels: action: mrg+1, type: enhancement

#5357 MAINT/ENH: refactor np.random.x to use np.random.Generator
  doc/examples/applications/plot_rank_filters.py
  doc/examples/features_detection/plot_gabors_from_astronaut.py
  doc/examples/features_detection/plot_shape_index.py
  doc/examples/filters/plot_deconvolution.py
  doc/examples/filters/plot_entropy.py
  doc/examples/filters/plot_restoration.py
  doc/examples/registration/plot_masked_register_translation.py
  doc/examples/segmentation/plot_random_walker_segmentation.py
  doc/examples/transform/plot_fundamental_matrix.py
  doc/examples/transform/plot_ransac.py
  doc/examples/transform/plot_ssim.py
  doc/release/release_dev.rst
  doc/source/conf.py
  doc/source/plots/hough_tf.py
  doc/source/user_guide/numpy_images.rst
  skimage/_shared/_warnings.py
  skimage/_shared/utils.py
  skimage/data/_binary_blobs.py
  skimage/data/_blobs_3d_fiji_skeleton.tif
  skimage/data/_registry.py
  skimage/draw/_random_shapes.py
  skimage/feature/_canny.py
  skimage/feature/brief.py
  skimage/feature/haar.py
  skimage/feature/orb.py
  skimage/feature/tests/test_brief.py
  skimage/feature/tests/test_haar.py
  skimage/feature/tests/test_match.py
  skimage/feature/util.py
  skimage/filters/edges.py
  skimage/filters/rank/generic.py
  skimage/future/graph/graph_cut.py
  skimage/io/_io.py
  skimage/measure/_regionprops.py
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/tests/test_skeletonize_3d.py
  skimage/restoration/_denoise.py
  skimage/restoration/deconvolution.py
  skimage/restoration/j_invariant.py
  skimage/restoration/non_local_means.py
  skimage/restoration/tests/camera_unsup.npy
  skimage/restoration/tests/camera_unsup2.npy
  skimage/restoration/tests/test_restoration.py
  skimage/segmentation/_quickshift_cy.pyx
  skimage/segmentation/random_walker_segmentation.py
  skimage/segmentation/tests/test_quickshift.py
  skimage/transform/_hough_transform.pyx
  skimage/transform/_warps.py
  skimage/transform/hough_transform.py
  skimage/transform/tests/test_hough_transform.py
  skimage/util/noise.py
  skimage/util/tests/test_random_noise.py
Labels: action: mrg+1, type: enhancement, type: maintenance

#5412 Extended rolling ball example with ECG data (1D)
  doc/examples/segmentation/plot_rolling_ball.py
Labels: type: documentation

#5419 Check for Integral ABC instead of `int` in `crop`
  skimage/util/arraycrop.py
  skimage/util/tests/test_arraycrop.py
Labels: action: mrg+1, type: bug fix

#5425 Fix duplicate test function names in test_unsharp_mask.py
  skimage/filters/tests/test_unsharp_mask.py
Labels: action: mrg+1, type: maintenance

#5433 Rename `label` variable to circumvent link issue in docs.
  doc/examples/segmentation/plot_regionprops.py
Labels: type: documentation

#5434 avoid duplicate API documentation for ImageViewer, CollectionViewer
  doc/tools/build_modref_templates.py
Labels: type: documentation, type: maintenance

#5437 avoid warnings about use of deprecated `scipy.linalg.pinv2`
  skimage/segmentation/random_walker_segmentation.py
Labels: type: maintenance

#5382 Added ND butterworth filter
  setup.cfg
  skimage/filters/__init__.py
  skimage/filters/_fft_based.py
  skimage/filters/tests/astronaut_butter.npy
  skimage/filters/tests/coins_butter.npy
  skimage/filters/tests/test_fft_based.py
Labels: type: new feature

#5427 residual multichannel->channel_axis fixes
  benchmarks/__init__.py
  benchmarks/benchmark_restoration.py
  benchmarks/benchmark_segmentation.py
  skimage/feature/_hog.py
  skimage/feature/orb.py
  skimage/filters/_gaussian.py
  skimage/future/tests/test_trainable_segmentation.py
  skimage/restoration/_denoise.py
  skimage/segmentation/random_walker_segmentation.py
  skimage/transform/_warps.py
  skimage/transform/tests/test_radon_transform.py
  skimage/viewer/tests/test_viewer.py
Labels: action: mrg+1, type: maintenance

#5204 single precision support in skimage.registration module
  TODO.txt
  benchmarks/benchmark_registration.py
  skimage/_shared/fft.py
  skimage/registration/_masked_phase_cross_correlation.py
  skimage/registration/_optical_flow.py
  skimage/registration/_optical_flow_utils.py
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_ilk.py
  skimage/registration/tests/test_masked_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
  skimage/registration/tests/test_tvl1.py
Labels: action: mrg+1, type: enhancement, type: perfomance

#5438 Document the multichannel->channel_axis transition in the release notes
  doc/release/release_dev.rst
Labels: type: documentation

#5431 Update RELEASE.txt
  .github/workflows/wheel_tests_and_release.yml
  RELEASE.txt
Labels: type: documentation

#5447 Do not mark image edges in 'subpixel' mode of find_boundaries
  doc/release/release_dev.rst
  skimage/segmentation/boundaries.py
  skimage/segmentation/tests/test_boundaries.py
Labels: type: bug fix

#5445 rename selem to footprint everywhere
  doc/examples/applications/plot_morphology.py
  doc/examples/applications/plot_rank_filters.py
  doc/examples/applications/plot_thresholding.py
  doc/examples/color_exposure/plot_local_equalize.py
  doc/examples/features_detection/plot_windowed_histogram.py
  doc/examples/filters/plot_rank_mean.py
  doc/examples/filters/plot_tophat.py
  skimage/filters/_median.py
  skimage/filters/edges.py
  skimage/filters/rank/_percentile.py
  skimage/filters/rank/bilateral.py
  skimage/filters/rank/bilateral_cy.pyx
  skimage/filters/rank/core_cy.pxd
  skimage/filters/rank/core_cy.pyx
  skimage/filters/rank/core_cy_3d.pxd
  skimage/filters/rank/core_cy_3d.pyx
  skimage/filters/rank/generic.py
  skimage/filters/rank/generic_cy.pyx
  skimage/filters/rank/percentile_cy.pyx
  skimage/filters/rank/tests/test_rank.py
  skimage/filters/tests/test_median.py
  skimage/measure/_label.py
  skimage/morphology/__init__.py
  skimage/morphology/_flood_fill.py
  skimage/morphology/_util.py
  skimage/morphology/binary.py
  skimage/morphology/extrema.py
  skimage/morphology/footprints.py
  skimage/morphology/gray.py
  skimage/morphology/grayreconstruct.py
  skimage/morphology/max_tree.py
  skimage/morphology/misc.py
  skimage/morphology/selem.py
  skimage/morphology/tests/test_binary.py
  skimage/morphology/tests/test_extrema.py
  skimage/morphology/tests/test_flood_fill.py
  skimage/morphology/tests/test_footprints.py
  skimage/morphology/tests/test_gray.py
  skimage/morphology/tests/test_reconstruction.py
  skimage/morphology/tests/test_util.py
  skimage/segmentation/boundaries.py
  skimage/viewer/tests/test_plugins.py
Labels: api, type: maintenance

#5420 Add no-reference perceptual blur metric.
  doc/examples/filters/plot_blur_effect.py
  skimage/filters/__init__.py
  skimage/measure/__init__.py
  skimage/measure/_blur_effect.py
  skimage/measure/tests/test_blur_effect.py
Labels: action: mrg+1, type: new feature
