Repository scikit-image/scikit-image, pull requests merged in 2021-11, with the labels that each got.

#5600 trainable_segmentation: re-raise in error case
  skimage/future/tests/test_trainable_segmentation.py
  skimage/future/trainable_segmentation.py
Labels: type: bug fix

#5976 Add small regularization to avoid zero-division in richardson_lucy
  skimage/restoration/deconvolution.py
Labels: action: mrg+1, type: bug fix

#5990 Make matplotlib an optional dependency
  requirements/default.txt
  requirements/optional.txt
  requirements/test.txt
  skimage/_shared/__init__.py
  skimage/_shared/_geometry.py
  skimage/_shared/tests/test_geometry.py
  skimage/draw/draw.py
  skimage/draw/tests/test_draw.py
  skimage/feature/tests/test_util.py
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
  skimage/future/graph/rag.py
  skimage/future/manual_segmentation.py
  skimage/io/tests/test_mpl_imshow.py
  skimage/io/tests/test_plugin.py
  skimage/transform/tests/test_radon_transform.py
  skimage/viewer/__init__.py
  skimage/viewer/tests/test_plugins.py
  skimage/viewer/tests/test_tools.py
  skimage/viewer/tests/test_utils.py
  skimage/viewer/tests/test_viewer.py
  skimage/viewer/tests/test_widgets.py
Labels: type: maintenance, action: mrg+1

#6007 Prefer importing build_py and sdist from setuptools
  setup.py
Labels: type: bug fix

#6013 Fix the estimation of ellipsoid axis lengths in the 3D case
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: type: bug fix

#5589 Restore integer image rescaling for edge filters
  skimage/filters/_gabor.py
  skimage/filters/edges.py
  skimage/filters/tests/test_edges.py
  skimage/filters/tests/test_gabor.py
Labels: action: mrg+1, type: bug fix

#6000 add property getters for all deprecated regionprops names
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: type: bug fix

#5999 Update scipy requirement to 1.4.1 and use scipy.fft instead of scipy.fftpack
  TODO.txt
  doc/examples/filters/plot_dog.py
  doc/examples/filters/plot_window.py
  doc/examples/registration/plot_register_rotation.py
  requirements/default.txt
  skimage/_shared/fft.py
  skimage/filters/_fft_based.py
  skimage/filters/lpi_filter.py
  skimage/filters/tests/test_fft_based.py
  skimage/registration/_masked_phase_cross_correlation.py
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_masked_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
  skimage/restoration/deconvolution.py
  skimage/restoration/uft.py
  skimage/transform/radon_transform.py
Labels: action: mrg+1

#6022 update pyproject.toml to handle Python 3.10 and Apple arm64
  pyproject.toml
Labels: type: infrastructure

#6027 Add python 3.10 test runs on GitHub Actions and Appveyor
  .appveyor.yml
  .github/workflows/tests.yml
Labels: type: infrastructure

#6031 Relax a couple of equality tests causing i686 test failures on cibuildwheel
  skimage/restoration/tests/test_denoise.py
  skimage/segmentation/tests/test_slic.py
Labels: type: maintenance, type: infrastructure

#5601 Weighted estimation of geometric transform matrices
  doc/examples/transform/plot_geometric.py
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: type: enhancement, action: mrg+1

#6032 Avoid matplotlib import overhead during 'import skimage'
  skimage/_shared/__init__.py
  skimage/_shared/_dependency_checks.py
  skimage/draw/tests/test_draw.py
  skimage/feature/tests/test_util.py
  skimage/filters/tests/test_thresholding.py
  skimage/io/tests/test_plugin.py
  skimage/transform/tests/test_radon_transform.py
  skimage/viewer/__init__.py
Labels: type: maintenance, type: perfomance

#3226 Add Pythran support to build, convert two functions
  .appveyor.yml
  .github/workflows/benchmarks.yml
  asv.conf.json
  azure-pipelines.yml
  benchmarks/benchmark_feature.py
  pyproject.toml
  requirements/build.txt
  setup.py
  skimage/feature/_hessian_det_appx.pyx
  skimage/feature/_hessian_det_appx_pythran.py
  skimage/feature/brief.py
  skimage/feature/brief_cy.pyx
  skimage/feature/brief_pythran.py
  skimage/feature/setup.py
Labels: run-benchmark

#5563 improve single precision support in skimage.exposure
  skimage/exposure/_adapthist.py
  skimage/exposure/exposure.py
  skimage/exposure/histogram_matching.py
  skimage/exposure/tests/test_exposure.py
  skimage/exposure/tests/test_histogram_matching.py
Labels: type: enhancement, action: mrg+1

#5472 Implement SIFT feature detector and descriptor
  doc/examples/features_detection/plot_sift.py
  skimage/feature/__init__.py
  skimage/feature/_sift.pyx
  skimage/feature/setup.py
  skimage/feature/sift.py
  skimage/feature/tests/test_sift.py
Labels: type: enhancement, action: mrg+1

#6042 Avoid circular import errors when EAGER_IMPORT=1
  .github/workflows/tests.yml
  skimage/exposure/exposure.py
  skimage/feature/sift.py
Labels: type: bug fix

#6019 reduce memory required by test_masked_registration_3d_contiguous_mask
  skimage/registration/tests/test_masked_phase_cross_correlation.py
Labels: type: maintenance

#6021 Update wheel builds to include Python 3.10
  .github/workflows/wheel_tests_and_release.yml
  skimage/segmentation/tests/test_slic.py
Labels: type: infrastructure

#6044 remove all use of the deprecated distutils package
  pyproject.toml
  requirements/build.txt
  requirements/default.txt
  setup.py
  skimage/_build.py
  skimage/_shared/version_requirements.py
  skimage/data/_fetchers.py
  skimage/io/_plugins/pil_plugin.py
  skimage/io/collection.py
  skimage/segmentation/tests/test_random_walker.py
Labels: type: maintenance

#5585 Remove use of channel_as_last_axis from apply_parallel
  skimage/util/apply_parallel.py
  skimage/util/tests/test_apply_parallel.py
Labels: type: enhancement, action: mrg+1, type: bug fix

#5209 fix clip bug in resize when anti_aliasing is applied (#5202)
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: action: mrg+1, type: bug fix

#5557 update release_dev.txt with recently merged PRs
  doc/release/release_dev.rst
Labels: type: documentation

#6035 Fix peak local max segfault
  skimage/_shared/coord.py
  skimage/_shared/tests/test_coord.py
Labels: type: bug fix

#6049 Azure: disable caching as a temporary workaround to #6048
  azure-pipelines.yml
Labels: type: infrastructure

#6055 add Python 3.10 classifier in setup.py
  setup.py
Labels: type: maintenance

#6061 remove use of deprecated np.int in SIFT
  skimage/feature/sift.py
Labels: type: bug fix

#6062 Backport PR #6061 on branch v0.19.x (remove use of deprecated np.int in SIFT)
  skimage/feature/sift.py
Labels: type: bug fix

#6060 Fix test failures observed with numpy 1.22rc0
  skimage/filters/_rank_order.py
  skimage/measure/tests/test_regionprops.py
Labels: type: bug fix

#6063 Backport PR #6060 on branch v0.19.x (Fix test failures observed with numpy 1.22rc0)
  skimage/filters/_rank_order.py
  skimage/measure/tests/test_regionprops.py
Labels: type: bug fix

#6057 Use math.prod instead of np.prod where possible
  .appveyor.yml
  .github/workflows/benchmarks.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
  asv.conf.json
  azure-pipelines.yml
  pyproject.toml
  requirements/build.txt
  requirements/default.txt
  setup.py
  skimage/exposure/_adapthist.py
  skimage/feature/template.py
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
  skimage/restoration/_rolling_ball_cy.pyx
  skimage/segmentation/slic_superpixels.py
Labels: type: maintenance
