Repository scikit-image/scikit-image, pull requests merged in 2021-08, with the labels that each got.

#5486 Remove legacy Travis-CI scripts and update contributor documentation accordingly
  CONTRIBUTING.txt
  TODO.txt
  tools/github/before_install.sh
  tools/travis/before_install.sh
  tools/travis/install_qt.sh
  tools/travis/notes.txt
  tools/travis/osx_install.sh
  tools/travis/script.sh
Labels: action: mrg+1, type: maintenance

#5497 Fixed NaN issue in threshold_otsu
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: type: bug fix

#4482 fixed DoG function for correct scaling
  skimage/feature/blob.py
  skimage/feature/tests/test_blob.py
Labels: action: mrg+1, type: bug fix

#5488 non-local means: support 3d+multichannel, 4d and 4d+multichannel
  skimage/restoration/_nl_means_denoising.pyx
  skimage/restoration/non_local_means.py
  skimage/restoration/tests/test_denoise.py
Labels: type: enhancement

#5463 Remove deprecated functions and arguments for the 0.19 release
  TODO.txt
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/color/__init__.py
  skimage/color/colorconv.py
  skimage/color/colorlabel.py
  skimage/color/tests/test_colorconv.py
  skimage/color/tests/test_colorlabel.py
  skimage/draw/__init__.py
  skimage/draw/draw.py
  skimage/draw/tests/test_draw.py
  skimage/feature/__init__.py
  skimage/filters/ridges.py
  skimage/filters/tests/test_ridges.py
  skimage/measure/__init__.py
  skimage/measure/_marching_cubes_classic.py
  skimage/measure/_marching_cubes_lewiner.py
  skimage/measure/tests/test_marching_cubes.py
  skimage/measure/tests/test_profile.py
  skimage/morphology/__init__.py
  skimage/morphology/_deprecated.py
  skimage/morphology/_flood_fill.py
  skimage/morphology/tests/test_flood_fill.py
  skimage/registration/tests/test_masked_phase_cross_correlation.py
  skimage/restoration/non_local_means.py
  skimage/restoration/tests/test_denoise.py
  skimage/segmentation/__init__.py
  skimage/segmentation/morphsnakes.py
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_morphsnakes.py
  skimage/transform/_warps.py
  skimage/transform/radon_transform.py
  skimage/transform/tests/test_radon_transform.py
  skimage/transform/tests/test_warps.py
  skimage/util/__init__.py
  skimage/util/tests/test_arraypad.py
Labels: type: maintenance, action: mrg+1

#5462 Add a channel_axis argument to functions in the skimage.color module
  skimage/_shared/utils.py
  skimage/color/adapt_rgb.py
  skimage/color/colorconv.py
  skimage/color/colorlabel.py
  skimage/color/delta_e.py
  skimage/color/tests/test_colorconv.py
  skimage/color/tests/test_colorlabel.py
  skimage/color/tests/test_delta_e.py
Labels: type: enhancement, action: mrg+1, api

#5507 Fix uint8 overflow in exposure.adjust_gamma
  skimage/exposure/exposure.py
  skimage/exposure/tests/test_exposure.py
Labels: action: mrg+1, type: bug fix

#5487 simplify blob_log using vectorized linspace and logspace
  TODO.txt
  skimage/feature/blob.py
Labels: type: maintenance, action: mrg+1

#5336 Test setup and teardown
  .github/workflows/tests.yml
  skimage/_shared/testing.py
  skimage/_shared/tests/__init__.py
  skimage/color/tests/__init__.py
  skimage/color/tests/test_colorlabel.py
  skimage/conftest.py
  skimage/data/tests/__init__.py
  skimage/draw/tests/__init__.py
  skimage/exposure/tests/__init__.py
  skimage/feature/tests/__init__.py
  skimage/feature/tests/test_corner.py
  skimage/filters/rank/generic.py
  skimage/filters/tests/__init__.py
  skimage/future/tests/test_trainable_segmentation.py
  skimage/graph/tests/__init__.py
  skimage/io/tests/__init__.py
  skimage/measure/tests/__init__.py
  skimage/measure/tests/test_fit.py
  skimage/metrics/tests/__init__.py
  skimage/metrics/tests/test_set_metrics.py
  skimage/morphology/misc.py
  skimage/morphology/tests/__init__.py
  skimage/morphology/tests/test_misc.py
  skimage/restoration/tests/__init__.py
  skimage/segmentation/tests/__init__.py
  skimage/transform/tests/__init__.py
  skimage/util/tests/__init__.py
  skimage/viewer/tests/__init__.py
  skimage/viewer/tests/test_widgets.py
Labels: type: maintenance

#5503 Fix blob dog docstring example and normalization
  skimage/feature/blob.py
  skimage/feature/peak.py
  skimage/feature/tests/test_blob.py
Labels: type: bug

#5254 Introduce a consistent naming scheme for measure.regionprops
  doc/examples/segmentation/plot_regionprops.py
  skimage/feature/peak.py
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: action: mrg+1, api

#5513 Enable pytest skipping at module level
  skimage/_shared/testing.py
Labels: type: infrastructure

#3772 Compute histograms for multichannel images
  skimage/exposure/exposure.py
  skimage/exposure/tests/test_exposure.py
Labels: type: enhancement, action: mrg+1

#5505 Fix doctests and restore doctesting on CI
  skimage/_shared/testing.py
  skimage/_shared/utils.py
  skimage/feature/corner.py
  skimage/measure/profile.py
  skimage/morphology/footprints.py
  skimage/morphology/tests/test_gray.py
  skimage/morphology/tests/test_reconstruction.py
  skimage/segmentation/_watershed.py
  skimage/util/lookfor.py
  tools/github/before_install.sh
  tools/github/script.sh
Labels: type: documentation, type: infrastructure, type: bug fix

#5510 .format() coverted to f-strings in registration & restoration subpackage
  skimage/registration/_masked_phase_cross_correlation.py
  skimage/registration/tests/test_masked_phase_cross_correlation.py
  skimage/restoration/_denoise.py
Labels: type: maintenance

#5522 fix histogram and regionprops_table doctests
  skimage/exposure/exposure.py
  skimage/measure/_regionprops.py
Labels: type: documentation, type: bug fix

#5514 Allow rank filters to output data as float32 instead of float64
  skimage/filters/rank/core_cy.pxd
  skimage/filters/rank/core_cy_3d.pxd
  skimage/filters/rank/tests/test_rank.py
Labels: type: enhancement, action: mrg+1

#5531 Backports for 0.18.3 (pooch 1.5 fix, deprecated `scipy.linalg.pinv2` fix)
  doc/release/release_0.18.rst
  doc/release/release_dev.rst
  skimage/__init__.py
  skimage/data/__init__.py
  skimage/segmentation/random_walker_segmentation.py
Labels: type: bug

#5534 Backport PR#5397 on branch v0.18.x (Increase automation in release process)
  .github/workflows/wheel_tests_and_release.yml
Labels: type: infrastructure

#5535 Revert "Backport PR#5397 on branch v0.18.x (Increase automation in release process)"
  .github/workflows/cibuildwheel.yml
Labels: type: infrastructure

#5539 Replaced .format() with f-string
  .github/ISSUE_TEMPLATE.md
  doc/examples/applications/plot_3d_image_processing.py
  doc/examples/applications/plot_haar_extraction_selection_classification.py
  doc/examples/edges/plot_random_shapes.py
  doc/examples/filters/plot_cycle_spinning.py
  doc/examples/filters/plot_denoise.py
  doc/examples/filters/plot_denoise_wavelet.py
  doc/examples/filters/plot_nonlocal_means.py
  doc/examples/registration/plot_masked_register_translation.py
  doc/examples/registration/plot_register_rotation.py
  doc/examples/registration/plot_register_translation.py
  doc/examples/segmentation/plot_chan_vese.py
  doc/examples/segmentation/plot_euler_number.py
  doc/examples/segmentation/plot_floodfill.py
  doc/examples/segmentation/plot_metrics.py
  doc/examples/segmentation/plot_segmentations.py
  doc/examples/transform/plot_fundamental_matrix.py
  doc/examples/transform/plot_matching.py
  doc/examples/transform/plot_radon_transform.py
  doc/examples/transform/plot_ssim.py
  doc/ext/plot2rst.py
  doc/source/conf.py
  doc/tools/apigen.py
  skimage/_shared/utils.py
  skimage/color/colorconv.py
  skimage/color/colorlabel.py
  skimage/color/tests/test_colorconv.py
  skimage/data/__init__.py
  skimage/exposure/exposure.py
  skimage/feature/blob.py
  skimage/filters/_gaussian.py
  skimage/measure/_regionprops.py
  skimage/measure/mc_meta/visual_test.py
  skimage/metrics/simple_metrics.py
  skimage/restoration/deconvolution.py
  skimage/segmentation/random_walker_segmentation.py
  skimage/transform/_warps.py
  skimage/util/arraycrop.py
  skimage/util/dtype.py
  tools/generate_release_notes.py
  tools/mailmap.py
Labels: type: maintenance

#5547 Fix and standardize docstrings for blob detection functions.
  skimage/feature/blob.py
Labels: type: documentation

#5527 Allow denoise_bilateral to work on images with negative values
  skimage/restoration/_denoise.py
  skimage/restoration/tests/test_denoise.py
Labels: type: enhancement, action: mrg+1

#5540 Forward-port of v0.18.3 release notes
  doc/release/release_0.18.rst
Labels: type: documentation

#5518 Rescale image consistently during SLIC superpixel segmentation
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_slic.py
Labels: action: mrg+1, type: bug fix

#5454 Add default values for denoise_tv_bregman / block_reduce / threshold_local method
  skimage/filters/thresholding.py
  skimage/measure/block.py
  skimage/measure/tests/test_block.py
  skimage/restoration/_denoise.py
Labels: action: mrg+1
