Repository scikit-image/scikit-image, pull requests merged in 2021-12, with the labels that each got.

#6068 add MacOS arm64 wheels
  .github/workflows/wheel_tests_and_release.yml
Labels: type: infrastructure

#6073 Handle autoupdate of docstrings to mention deprecated parameters in deprecate_kwarg
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/filters/_median.py
  skimage/filters/rank/_percentile.py
  skimage/filters/rank/bilateral.py
  skimage/filters/rank/generic.py
  skimage/filters/thresholding.py
  skimage/measure/_find_contours.py
  skimage/measure/_label.py
  skimage/morphology/_flood_fill.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/binary.py
  skimage/morphology/extrema.py
  skimage/morphology/footprints.py
  skimage/morphology/gray.py
  skimage/morphology/grayreconstruct.py
  skimage/restoration/_denoise.py
  skimage/restoration/deconvolution.py
  skimage/restoration/non_local_means.py
  skimage/segmentation/_chan_vese.py
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/morphsnakes.py
  skimage/segmentation/slic_superpixels.py
Labels: type: maintenance, type: infrastructure

#6079 Fix deprecate_kwarg test
  skimage/_shared/tests/test_utils.py
Labels: type: bug

#6081 Backport gh-6073 on v0.19.x (Handle autoupdate of docstrings to mention deprecated parameters in deprecate_kwarg)
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/filters/_median.py
  skimage/filters/rank/_percentile.py
  skimage/filters/rank/bilateral.py
  skimage/filters/rank/generic.py
  skimage/filters/thresholding.py
  skimage/measure/_find_contours.py
  skimage/measure/_label.py
  skimage/morphology/_flood_fill.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/binary.py
  skimage/morphology/extrema.py
  skimage/morphology/footprints.py
  skimage/morphology/gray.py
  skimage/morphology/grayreconstruct.py
  skimage/restoration/_denoise.py
  skimage/restoration/deconvolution.py
  skimage/restoration/non_local_means.py
  skimage/segmentation/_chan_vese.py
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/morphsnakes.py
  skimage/segmentation/slic_superpixels.py
Labels: type: documentation, type: bug fix

#6083 Backport PR #6075 on branch v0.19.x (Fix API docs autogeneration for lazy loaded subpackages)
  doc/tools/apigen.py
Labels: type: documentation, type: bug fix

#6082 forward port gh-6068 (add MacOS arm64 wheels) from branch v0.19.x to main
  .github/workflows/wheel_tests_and_release.yml
Labels: type: maintenance, type: infrastructure

#6084 Update v0.19.0 release notes
  doc/release/release_0.19.rst
Labels: type: documentation

#6085 checkout gh-pages with a shallow clone
  doc/gh-pages.py
Labels: type: documentation, type: infrastructure

#6075 Fix API docs autogeneration for lazy loaded subpackages
  doc/tools/apigen.py
Labels: type: documentation, type: bug fix

#6091 Fix dev doc build
  .github/workflows/build-docs.yml
  .github/workflows/wheel_tests_and_release.yml
Labels: type: bug, type: infrastructure

#6098 Fix two equality comparison bugs in the wheel build script
  .github/workflows/wheel_tests_and_release.yml
Labels: type: bug, type: infrastructure

#6097 restore non-underscore functions in skimage.data
  skimage/data/__init__.py
  skimage/data/tests/test_data.py
Labels: type: bug fix

#6101 forward port of #6098 (fix MacOS arm64 wheels and Windows Python 3.10 AMD64 wheel)
  .github/workflows/wheel_tests_and_release.yml
Labels: type: infrastructure, type: bug fix

#6105 pass a specific random_state into ransac in test_ransac_geometric
  skimage/measure/tests/test_fit.py
Labels: type: maintenance, backport: 0.19.x

#6099 Backport PR #6097 on branch v0.19.x (restore non-underscore functions in skimage.data)
  skimage/data/__init__.py
  skimage/data/tests/test_data.py
Labels: type: bug fix

#6106 Backport PR #6103 on branch v0.19.x (make rank filter test comparisons robust across architectures)
  skimage/filters/rank/tests/test_rank.py
Labels: type: maintenance

#6107 Backport PR #6105 on branch v0.19.x (pass a specific random_state into ransac in test_ransac_geometric)
  skimage/measure/tests/test_fit.py
Labels: type: maintenance

#6109 Add linker flags to strip debug symbols during wheel building
  .github/workflows/wheel_tests_and_release.yml
  MANIFEST.in
  setup.py
  skimage/_build.py
Labels: type: infrastructure, backport: 0.19.x

#6110 Backport of gh-6109 (Add linker flags to strip debug symbols during wheel building)
  .github/workflows/wheel_tests_and_release.yml
  MANIFEST.in
  setup.py
  skimage/_build.py
Labels: type: infrastructure

#6113 avoid circular import of rgb2gray
  skimage/exposure/exposure.py
Labels: type: maintenance, type: bug fix

#6112 Pin setuptools maximum in v0.19.x to avoid breaking on planned distutils API changes
  pyproject.toml
Labels: type: infrastructure

#6089 Skip tests requiring fetched data
  .github/workflows/tests.yml
  skimage/data/_fetchers.py
  skimage/measure/tests/test_blur_effect.py
  tools/github/script.sh
Labels: type: maintenance

#6115 Backport PR #6089 on branch v0.19.x (Skip tests requiring fetched data)
  .github/workflows/tests.yml
  skimage/data/_fetchers.py
  skimage/measure/tests/test_blur_effect.py
  tools/github/script.sh
Labels: type: maintenance

#6046 Transplant the change of scikit-learn into scikit-image for RANSAC
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: type: enhancement

#6114 relax test condition to make it more robust to variable CI load
  skimage/_shared/tests/test_coord.py
Labels: type: maintenance

#6118 respect SKIMAGE_TEST_STRICT_WARNINGS_GLOBAL setting in tests.yml
  .github/workflows/tests.yml
  doc/examples/transform/plot_fundamental_matrix.py
  doc/tools/build_modref_templates.py
  skimage/_shared/lazy.py
  skimage/_shared/testing.py
  skimage/_shared/tests/test_utils.py
  skimage/exposure/exposure.py
  skimage/feature/tests/test_blob.py
  skimage/filters/tests/test_gaussian.py
  skimage/filters/tests/test_median.py
  skimage/filters/tests/test_ridges.py
  skimage/io/tests/test_collection.py
  skimage/registration/tests/test_phase_cross_correlation.py
  skimage/restoration/tests/test_denoise.py
  skimage/util/apply_parallel.py
  tools/github/script.sh
Labels: type: infrastructure

#6128 Backport PR #6114 on branch v0.19.x (relax test condition to make it more robust to variable CI load)
  skimage/_shared/tests/test_coord.py
Labels: type: maintenance

#6127 Backport PR #6118 on branch v0.19.x (Fixes to tests.yml and fixes for expected warnings)
  .github/workflows/tests.yml
  doc/examples/transform/plot_fundamental_matrix.py
  doc/tools/build_modref_templates.py
  skimage/_shared/lazy.py
  skimage/_shared/testing.py
  skimage/_shared/tests/test_utils.py
  skimage/feature/tests/test_blob.py
  skimage/filters/tests/test_gaussian.py
  skimage/filters/tests/test_median.py
  skimage/filters/tests/test_ridges.py
  skimage/io/tests/test_collection.py
  skimage/registration/tests/test_phase_cross_correlation.py
  skimage/restoration/tests/test_denoise.py
  skimage/util/apply_parallel.py
  tools/github/script.sh
Labels: type: infrastructure, type: bug fix

#6116 add release notes for v0.19.1
  doc/release/release_0.19.rst
Labels: type: documentation

#6131 Backport PR #6130 on branch v0.19.x (bump deprecated Azure windows environment)
  azure-pipelines.yml
Labels: type: maintenance, type: infrastructure

#6130 bump deprecated Azure windows environment
  azure-pipelines.yml
Labels: type: maintenance, type: infrastructure

#6139 fix phase_cross_correlation typo
  skimage/registration/_phase_cross_correlation.py
Labels: type: documentation

#6133 Update user warning message for viewer module.
  skimage/_shared/testing.py
  skimage/viewer/__init__.py
Labels: type: documentation

#6087 Add two datasets for use in upcoming scientific tutorials.
  skimage/data/__init__.py
  skimage/data/_fetchers.py
  skimage/data/_registry.py
Labels: action: mrg+1

#6152 specify python version used by mybinder.org for gallery demos
  .binder/runtime.txt
  doc/source/conf.py
Labels: type: documentation, type: infrastructure
