Repository scikit-image/scikit-image, pull requests merged in 2022-07, with the labels that each got.

#6387 Canny: cythonize non-maximum suppression
  skimage/feature/_canny.py
  skimage/feature/_canny_cy.pyx
  skimage/feature/setup.py
Labels: :chart_with_upwards_trend: Performance

#6430 Substitute vertices with simplices in `transform/_geometric.py`
  skimage/transform/_geometric.py
Labels: :robot: Maintenance

#6161 remove deprecated indices kwarg from peak_local_max
  TODO.txt
  skimage/feature/peak.py
  skimage/feature/tests/test_peak.py
Labels: :robot: Maintenance

#6292 Polish the `MultiImage` docstring.
  skimage/io/collection.py
Labels: :page_facing_up: Documentation

#6431 example to render text onto an image
  doc/examples/applications/plot_text.py
Labels: :page_facing_up: Documentation

#6442 removed the completed items in 0.2
  TODO.txt
Labels: :robot: Maintenance

#6445 doc: replaced broken links
  doc/source/skips/3-transition-to-v1.rst
Labels: :page_facing_up: Documentation

#6419 Adding missing copyrights to LICENSE.txt, formatting according to SPDX identifiers
  LICENSE.txt
  skimage/_shared/version_requirements.py
  skimage/exposure/_adapthist.py
  skimage/feature/_canny.py
  skimage/filters/_rank_order.py
  skimage/filters/edges.py
  skimage/graph/_mcp.pyx
  skimage/graph/heap.pyx
  skimage/morphology/_grayreconstruct.pyx
  skimage/morphology/_skeletonize.py
  skimage/morphology/_skeletonize_cy.pyx
  skimage/morphology/grayreconstruct.py
  skimage/morphology/tests/test_reconstruction.py
  skimage/segmentation/_expand_labels.py
  skimage/segmentation/_watershed.py
  skimage/segmentation/_watershed_cy.pyx
  skimage/segmentation/heap_general.pxi
  skimage/segmentation/heap_watershed.pxi
  skimage/segmentation/tests/test_watershed.py
Labels: :page_facing_up: Documentation

#6440 Simplify sort-by-absolute-value in ridge filters.
  skimage/filters/ridges.py
Labels: :+1: OK to merge
