Repository scikit-image/scikit-image, pull requests merged in 2022-11, with the labels that each got.

#6519 Update pyproject.toml for Python 3.11 support and to fix 32-bit Windows pinnings
  pyproject.toml
  tools/github/before_install.sh
Labels: :robot: Infrastructure

#6626 pin setuptools in GHA MacOS workflow and azure-pipelines.yml
  .github/workflows/tests.yml
  azure-pipelines.yml
Labels: :robot: Infrastructure, :adhesive_bandage: Bug fix

#6637 Handle new warnings introduced in NumPy 1.24
  skimage/_shared/testing.py
  skimage/color/tests/test_delta_e.py
  skimage/feature/_cascade.pyx
  skimage/feature/tests/test_cascade.py
  skimage/segmentation/_join.py
  skimage/util/dtype.py
  skimage/util/tests/test_dtype.py
Labels: :robot: Infrastructure, :adhesive_bandage: Bug fix

#6628 Fix lengths of docstring heading underline
  skimage/morphology/isotropic.py
Labels: :page_facing_up: Documentation
