Repository scikit-image/scikit-image, pull requests merged in 2022-06, with the labels that each got.

#6389 derive OBJECT_COLUMNS from COL_DTYPES in regionprops
  skimage/measure/_regionprops.py
Labels: :fast_forward: Enhancement

#6407 Use artifact-redirector
  .circleci/artifact_path
  .circleci/config.yml
  .github/workflows/circleci.yml
Labels: :robot: Maintenance

#6405 In newer PIL, palette may contain <256 entries
  requirements/default.txt
  skimage/io/_plugins/pil_plugin.py
Labels: :robot: Maintenance

#6335 warp/rotate: fixed a bug with clipping when cval is not in the input range
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: :lady_beetle: Bug fix

#6410 backport of gh-6405: In newer PIL, palette may contain <256 entries
  requirements/default.txt
  skimage/io/_plugins/pil_plugin.py
Labels: :lady_beetle: Bug fix

#6411 Backport PR #6335 on branch v0.19.x (warp/rotate: fixed a bug with clipping when cval is not in the input range)
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: :lady_beetle: Bug fix

#6413 Fix computation of histogram bins for multichannel integer-valued images
  skimage/exposure/exposure.py
  skimage/exposure/tests/test_exposure.py
Labels: :lady_beetle: Bug fix

#6414 Backport PR #6413 on branch v0.19.x (Fix computation of histogram bins for multichannel integer-valued images)
  skimage/exposure/exposure.py
  skimage/exposure/tests/test_exposure.py
Labels: :lady_beetle: Bug fix

#6415 update v0.19.3 release notes
  doc/release/release_0.19.rst
Labels: :page_facing_up: Documentation

#6409 Sync numpy minimum version
  requirements/build.txt
Labels: :robot: Maintenance

#6342 add int64 support to `filters.rank_order` and `morphology.reconstruction`
  benchmarks/benchmark_morphology.py
  skimage/filters/_rank_order.py
  skimage/morphology/_grayreconstruct.pyx
  skimage/morphology/grayreconstruct.py
  skimage/morphology/setup.py
  skimage/morphology/tests/test_reconstruction.py
Labels: :+1: OK to merge, :lady_beetle: Bug fix

#6151 Implement 2D ellipse footprint decomposition
  benchmarks/benchmark_morphology.py
  doc/examples/numpy_operations/plot_footprint_decompositions.py
  doc/examples/numpy_operations/plot_structuring_element_decompositions.py
  skimage/filters/rank/generic.py
  skimage/morphology/__init__.py
  skimage/morphology/ball_decompositions.npy
  skimage/morphology/ball_decompositions.npz
  skimage/morphology/binary.py
  skimage/morphology/disk_decompositions.npy
  skimage/morphology/disk_decompositions.npz
  skimage/morphology/footprints.py
  skimage/morphology/gray.py
  skimage/morphology/misc.py
  skimage/morphology/setup.py
  skimage/morphology/tests/test_footprints.py
  tools/precompute/_precompute_nsphere_decompositions.py
Labels: :fast_forward: Enhancement, :+1: OK to merge, :chart_with_upwards_trend: Performance

#6149 Update of Meijering algorithm (resumed)
  skimage/feature/corner.py
  skimage/feature/tests/test_corner.py
  skimage/filters/ridges.py
Labels: :fast_forward: Enhancement, :+1: OK to merge, :lady_beetle: Bug fix

#6251 improve butterworth docstring and add new kwargs and gallery example
  doc/examples/filters/plot_butterworth.py
  skimage/filters/_fft_based.py
  skimage/filters/tests/test_fft_based.py
Labels: :fast_forward: Enhancement
