Repository scikit-image/scikit-image, pull requests merged in 2022-02, with the labels that each got.

#6223 Update filename in testing instructions.
  INSTALL.rst
Labels: type: documentation

#5482 Footprint decomposition for faster morphology (part 1)
  benchmarks/benchmark_morphology.py
  doc/examples/numpy_operations/plot_structuring_element_decompositions.py
  doc/examples/numpy_operations/plot_structuring_elements.py
  skimage/filters/rank/generic.py
  skimage/filters/rank/tests/test_rank.py
  skimage/morphology/__init__.py
  skimage/morphology/binary.py
  skimage/morphology/footprints.py
  skimage/morphology/gray.py
  skimage/morphology/tests/test_binary.py
  skimage/morphology/tests/test_footprints.py
  skimage/morphology/tests/test_gray.py
Labels: type: enhancement, action: mrg+1, type: perfomance

#6225 Backport PR #6223 on branch v0.19.x (Update filename in testing instructions.)
  INSTALL.rst
Labels: type: documentation

#6222 Backport PR #6219 on branch v0.19.x (Allow the output_shape argument to be any iterable for resize and resize_local_mean)
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: type: bug fix

#6229 Remove redundant testing on Appveyor
  .appveyor.yml
Labels: type: infrastructure

#6234 Backport PR #6229 on branch v0.19.x (Remove redundant testing on Appveyor)
  .appveyor.yml
Labels: type: infrastructure

#6183 Fix decorators warnings stacklevel
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
Labels: action: mrg+1, type: bug fix

#6232 Include Cython sources via package_data
  setup.py
  skimage/future/graph/tests/__init__.py
  skimage/future/tests/__init__.py
  skimage/registration/tests/__init__.py
  skimage/registration/tests/test_ilk.py
Labels: type: maintenance, backport: 0.19.x

#6244 Backport PR #6232 on branch v0.19.x (Include Cython sources via package_data)
  setup.py
  skimage/future/graph/tests/__init__.py
  skimage/future/tests/__init__.py
  skimage/registration/tests/__init__.py
  skimage/registration/tests/test_ilk.py
Labels: type: maintenance, backport: 0.19.x

#6245 Backport PR #6227 on branch v0.19.x (Fix calculation of Z normal in marching cubes)
  skimage/measure/_marching_cubes_lewiner_cy.pyx
Labels: type: bug fix

#6242 Fix bug in SLIC superpixels with `enforce_connectivity=True` and `start_label > 0`
  skimage/segmentation/_slic.pyx
  skimage/segmentation/tests/test_slic.py
Labels: type: bug fix, backport: 0.19.x

#6246 Backport PR #6242 on branch v0.19.x (Fix bug in SLIC superpixels with `enforce_connectivity=True` and `start_label > 0`)
  skimage/segmentation/_slic.pyx
  skimage/segmentation/tests/test_slic.py
Labels: type: bug fix, backport: 0.19.x

#6247 Backport PR #6211 on branch v0.19.x (PiecewiseAffineTransform.estimate return should reflect underlying transforms)
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: action: mrg+1, type: bug fix, backport: 0.19.x

#6230 remove deprecated marching_cubes '_lorensen' option
  skimage/measure/__init__.py
  skimage/measure/_marching_cubes_classic.py
  skimage/measure/_marching_cubes_classic_cy.pyx
  skimage/measure/_marching_cubes_lewiner.py
  skimage/measure/setup.py
  skimage/measure/tests/test_marching_cubes.py
Labels: type: maintenance, action: mrg+1

#6249 update MacOS libomp installation in wheel building script
  .github/workflows/wheel_tests_and_release.yml
Labels: type: maintenance, type: infrastructure

#6248 add release notes for v0.19.2
  doc/release/release_0.19.rst
Labels: type: documentation

#6257 implement nD skimage.filters.farid (Farid & Simoncelli filter)
  skimage/filters/edges.py
  skimage/filters/tests/test_edges.py
Labels: type: enhancement

#6263 Fix inpaint_biharmonic for images with Fortran-ordered memory layout
  skimage/restoration/inpaint.py
  skimage/restoration/tests/test_inpaint.py
Labels: action: mrg+1, type: bug fix
