Repository scikit-image/scikit-image, pull requests merged in 2022-01, with the labels that each got.

#6148 deprecate n_iter_max (should be max_num_iter)
  skimage/restoration/_denoise.py
  skimage/restoration/tests/test_denoise.py
Labels: type: maintenance, action: mrg+1, backport: 0.19.x

#6145 Fix channel_axis handling in pyramid_gaussian and pyramid_laplace
  skimage/transform/pyramids.py
  skimage/transform/tests/test_pyramids.py
Labels: action: mrg+1, type: bug fix

#6156 Backport PR #6148 on branch v0.19.x (deprecate n_iter_max (should be max_num_iter))
  skimage/restoration/_denoise.py
  skimage/restoration/tests/test_denoise.py
Labels: type: maintenance, action: mrg+1, backport: 0.19.x

#6155 Backport PR #6145 on branch v0.19.x (Fix channel_axis handling in pyramid_gaussian and pyramid_laplace)
  skimage/transform/pyramids.py
  skimage/transform/tests/test_pyramids.py
Labels: action: mrg+1, type: bug fix

#6157 Backport PR #6152 on branch v0.19.x (specify python version used by mybinder.org for gallery demos)
  .binder/runtime.txt
  doc/source/conf.py
Labels: type: documentation, type: infrastructure

#6158 Backport PR #6139 on branch v0.19.x (fix phase_cross_correlation typo)
  skimage/registration/_phase_cross_correlation.py
Labels: type: documentation

#6159 Backport PR #6133 on branch v0.19.x (Update user warning message for viewer module.)
  skimage/_shared/testing.py
  skimage/viewer/__init__.py
Labels: type: documentation

#5581 Implementation of the Modified Hausdorff Distance (MHD) metric
  benchmarks/benchmark_metrics.py
  skimage/metrics/__init__.py
  skimage/metrics/set_metrics.py
  skimage/metrics/tests/test_set_metrics.py
Labels: type: enhancement, action: mrg+1

#6160 remove skimage.viewer
  INSTALL.rst
  TODO.txt
  doc/source/user_guide.md
  doc/source/user_guide/viewer.rst
  doc/tools/build_modref_templates.py
  skimage/__init__.py
  skimage/_shared/testing.py
  skimage/viewer/__init__.py
  skimage/viewer/canvastools/__init__.py
  skimage/viewer/canvastools/base.py
  skimage/viewer/canvastools/linetool.py
  skimage/viewer/canvastools/painttool.py
  skimage/viewer/canvastools/recttool.py
  skimage/viewer/plugins/__init__.py
  skimage/viewer/plugins/base.py
  skimage/viewer/plugins/canny.py
  skimage/viewer/plugins/color_histogram.py
  skimage/viewer/plugins/crop.py
  skimage/viewer/plugins/labelplugin.py
  skimage/viewer/plugins/lineprofile.py
  skimage/viewer/plugins/measure.py
  skimage/viewer/plugins/overlayplugin.py
  skimage/viewer/plugins/plotplugin.py
  skimage/viewer/qt.py
  skimage/viewer/tests/__init__.py
  skimage/viewer/tests/test_plugins.py
  skimage/viewer/tests/test_tools.py
  skimage/viewer/tests/test_utils.py
  skimage/viewer/tests/test_viewer.py
  skimage/viewer/tests/test_widgets.py
  skimage/viewer/utils/__init__.py
  skimage/viewer/utils/canvas.py
  skimage/viewer/utils/core.py
  skimage/viewer/utils/dialogs.py
  skimage/viewer/viewers/__init__.py
  skimage/viewer/viewers/core.py
  skimage/viewer/widgets/__init__.py
  skimage/viewer/widgets/core.py
  skimage/viewer/widgets/history.py
  tools/check_sdist.py
  tools/github/script.sh
  viewer_examples/plugins/canny.py
  viewer_examples/plugins/canny_simple.py
  viewer_examples/plugins/collection_overlay.py
  viewer_examples/plugins/collection_plugin.py
  viewer_examples/plugins/color_histogram.py
  viewer_examples/plugins/croptool.py
  viewer_examples/plugins/lineprofile.py
  viewer_examples/plugins/lineprofile_rgb.py
  viewer_examples/plugins/measure.py
  viewer_examples/plugins/median_filter.py
  viewer_examples/plugins/probabilistic_hough.py
  viewer_examples/plugins/tv_denoise.py
  viewer_examples/plugins/watershed_demo.py
  viewer_examples/viewers/collection_viewer.py
  viewer_examples/viewers/image_viewer.py
Labels: type: maintenance

#6162 remove structure_tensor_eigvals and change default structure_tensor order
  TODO.txt
  skimage/feature/__init__.py
  skimage/feature/corner.py
  skimage/feature/tests/test_corner.py
Labels: type: maintenance, action: mrg+1

#6169 Fix unintended change to output dtype of match_histograms
  skimage/exposure/histogram_matching.py
  skimage/exposure/tests/test_histogram_matching.py
Labels: action: mrg+1, type: bug fix, backport: 0.19.x

#6172 Backport PR #6169 on branch v0.19.x (Fix unintended change to output dtype of match_histograms)
  skimage/exposure/histogram_matching.py
  skimage/exposure/tests/test_histogram_matching.py
Labels: action: mrg+1, type: bug fix, backport: 0.19.x

#6164 Remove deprecated Qt IO plugin and skivi script
  INSTALL.rst
  MANIFEST.in
  TODO.txt
  doc/source/user_guide/plugins.rst
  requirements/optional.txt
  setup.py
  skimage/io/_plugins/qt_plugin.ini
  skimage/io/_plugins/qt_plugin.py
  skimage/io/_plugins/skivi.py
  skimage/io/manage_plugins.py
  skimage/scripts/__init__.py
  skimage/scripts/skivi
  skimage/scripts/skivi.py
Labels: type: maintenance

#6184 Fix SIFT wrong octave indices + typo
  skimage/feature/sift.py
Labels: action: mrg+1, type: bug fix

#6186 Backport PR #6184 on branch v0.19.x (Fix SIFT wrong octave indices + typo)
  skimage/feature/sift.py
Labels: action: mrg+1, type: bug fix

#6191 Fix issue6190 - inconsistent default parameters in pyramids.py
  skimage/transform/pyramids.py
  skimage/transform/tests/test_pyramids.py
Labels: type: bug fix, backport: 0.19.x

#6193 Backport PR #6191 on branch v0.19.x (Fix issue6190 - inconsistent default parameters in pyramids.py)
  skimage/transform/pyramids.py
  skimage/transform/tests/test_pyramids.py
Labels: type: bug fix, backport: 0.19.x

#6195 Adding CITATION.bib
  CITATION.bib
Labels: type: documentation

#6200 Improve writing for perimeter estimation example.
  doc/examples/segmentation/plot_perimeters.py
Labels: type: documentation

#6208 expand reviewer guidelines in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: documentation, type: infrastructure

#6207 Always set params to nan when ProjectiveTransform.estimate fails
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: backport: 0.19.x

#6210 Backport PR #6207 on branch v0.19.x (Always set params to nan when ProjectiveTransform.estimate fails)
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: backport: 0.19.x

#5262 Add textbook-like tutorial on measuring fluorescence at nuclear envelope.
  doc/examples/applications/plot_fluorescence_nuclear_envelope.py
Labels: type: documentation, action: mrg+1

#6213 Backport PR #5262 on branch v0.19.x (Add textbook-like tutorial on measuring fluorescence at nuclear envelope.)
  doc/examples/applications/plot_fluorescence_nuclear_envelope.py
Labels: type: documentation, action: mrg+1

#6211 PiecewiseAffineTransform.estimate return should reflect underlying transforms
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: action: mrg+1, type: bug fix, backport: 0.19.x

#6215 Backport PR #6087 on branch v0.19.x (Add two datasets for use in upcoming scientific tutorials.)
  skimage/data/__init__.py
  skimage/data/_fetchers.py
  skimage/data/_registry.py
Labels: action: mrg+1

#6214 EuclideanTransform.estimate should return False when NaNs are present
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: type: bug fix, backport: 0.19.x

#6221 Backport PR #6214 on branch v0.19.x (EuclideanTransform.estimate should return False when NaNs are present)
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: type: bug fix, backport: 0.19.x

#6219 Allow the output_shape argument to be any iterable for resize and resize_local_mean
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: type: bug fix
