Repository scikit-image/scikit-image, pull requests merged in 2022-05, with the labels that each got.

#6293 Update plot_pyramid.py demo to work for diversified shaped images and downsample factors
  doc/examples/transform/plot_pyramid.py
Labels: :page_facing_up: type: documentation, :+1: action: mrg+1

#6276 More flexible collections with custom load_func.
  skimage/io/collection.py
  skimage/io/tests/test_collection.py
Labels: :+1: action: mrg+1

#6366 add recently merged PR to the v0.19.3 release notes
  doc/release/release_0.19.rst
Labels: :page_facing_up: type: documentation, :+1: action: OK to merge

#6377 Removing reference to `marching_cubes_lewiner` from `plot_marching_cubes.py`
  doc/examples/edges/plot_marching_cubes.py
Labels: :page_facing_up: Documentation

#6379 pin to pip<22.1
  tools/github/before_install.sh
Labels: :robot: Infrastructure
