Repository scikit-image/scikit-image, pull requests merged in 2022-12, with the labels that each got.

#6639 update primary email address in mailmap entry for grlee77
  .mailmap
Labels: :wrench: Maintenance

#6599 Fix intensity autoscaling in animated imshow.
  doc/examples/applications/plot_fluorescence_nuclear_envelope.py
Labels: :page_facing_up: Documentation

#6597 Reduce memory consumption in blob_* functions with preallocation
  skimage/feature/blob.py
Labels: :chart_with_upwards_trend: Performance

#6543 Start deprecation of inconsistency in phase_cross_correlation output count
  TODO.txt
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: :arrow_down_small: Deprecation, :scroll: API

#6469 Add solidification demo
  doc/examples/applications/plot_solidification_tracking.py
Labels: :page_facing_up: Documentation

#6581 Build Python 3.11 wheels
  .github/workflows/wheel_tests_and_release.yml
  RELEASE.txt
  pyproject.toml
Labels: :robot: Infrastructure

#6644 Fix plot order due to duplicate plot_thresholding
  doc/examples/applications/plot_thresholding_guide.py
  doc/examples/segmentation/plot_thresholding.py
Labels: :page_facing_up: Documentation, :adhesive_bandage: Bug fix

#6650 DOC: Get rid of numpy dep warning in plot_equalize.
  doc/examples/color_exposure/plot_equalize.py
Labels: :page_facing_up: Documentation

#6652 Fix typos in plot_rank_filters.py
  doc/examples/applications/plot_rank_filters.py
Labels: :page_facing_up: Documentation
