Repository scikit-image/scikit-image, pull requests merged in 2022-09, with the labels that each got.

#6501 Support float input to skimage.draw.rectangle() [#4283]
  skimage/draw/draw.py
  skimage/draw/tests/test_draw.py
Labels: :+1: OK to merge, :lady_beetle: Bug fix

#6502 Find peaks at border with `peak_local_max with `exclude_border=0`
  skimage/feature/peak.py
  skimage/feature/tests/test_peak.py
Labels: :+1: OK to merge, :lady_beetle: Bug fix, :runner: Sprint

#6495 Remove references to api_changes
  CONTRIBUTING.rst
  TODO.txt
  doc/source/api_changes.md
  doc/source/conf.py
  doc/source/index.rst
Labels: :page_facing_up: Documentation, :+1: OK to merge

#6511 Update benchmark environment to recent Python and NumPy versions
  asv.conf.json
Labels: :robot: Infrastructure, :bar_chart: run-benchmark

#6488 Document inclusion criteria for new functionality in core developer guide
  doc/source/core_developer.md
Labels: :page_facing_up: Documentation, :+1: OK to merge

#3255 Add benchmarks for morphology.local_maxima
  benchmarks/benchmark_morphology.py
Labels: :chart_with_upwards_trend: Performance, :bar_chart: run-benchmark

#6446 Rewrite the meijering, sato, and frangi ridge filters.
  doc/examples/edges/plot_ridge_filter.py
  doc/release/release_dev.rst
  skimage/filters/ridges.py
  skimage/filters/tests/test_ridges.py
Labels: :fast_forward: Enhancement, :adhesive_bandage: Bug fix

#6522 update plot_euler_number.py for maplotlib 3.6 compatibility
  doc/examples/segmentation/plot_euler_number.py
Labels: :adhesive_bandage: Bug fix

#6520 relax label name comparison in benchmarks.yaml
  .github/workflows/benchmarks.yml
Labels: :+1: OK to merge, :robot: Infrastructure, :bar_chart: run-benchmark

#6528 make non-functional change to build.txt to fix cache issue on CircleCI
  requirements/build.txt
Labels: :robot: Infrastructure

#6515 Add new flag to convex_hull_image and grid_points_in_poly
  skimage/measure/__init__.py
  skimage/measure/_pnpoly.pyx
  skimage/measure/pnpoly.py
  skimage/measure/tests/test_pnpoly.py
  skimage/morphology/convex_hull.py
  skimage/morphology/tests/test_convex_hull.py
Labels: :fast_forward: Enhancement

#6509 Reduce ridge filters memory footprints
  benchmarks/benchmark_filters.py
  skimage/filters/ridges.py
Labels: :+1: OK to merge, :chart_with_upwards_trend: Performance, :bar_chart: run-benchmark

#6508 Clarify header pointing to notes for latest version released.
  doc/source/release_notes.rst
Labels: :page_facing_up: Documentation

#6525 Use mask during rescaling in segmentation.slic and improve handling of error cases
  benchmarks/benchmark_segmentation.py
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_slic.py
Labels: :adhesive_bandage: Bug fix, :bar_chart: run-benchmark

#6506 Add Github actions/stale to label "dormant" issues and PRs
  .github/workflows/dormant-issues-prs.yml
Labels: :+1: OK to merge, :robot: Infrastructure

#6546 Update "Mark dormant issues" workflow
  .github/workflows/dormant-issues-prs.yml
Labels: :robot: Infrastructure

#6539 Ignore codespell fixes with git blame
  .git-blame-ignore-revs
Labels: :robot: Infrastructure

#6529 update setup.cfg field from license_file to license_files
  setup.cfg
Labels: :robot: Infrastructure

#6553 Remove FUNDING.yml in preference of org version
  .github/FUNDING.yml
Labels: :robot: Infrastructure

#6552 Add missing option stale-pr-label for "Mark dormant issues" workflow
  .github/workflows/dormant-issues-prs.yml
Labels: :+1: OK to merge, :robot: Infrastructure, :adhesive_bandage: Bug fix
