Repository scikit-image/scikit-image, pull requests merged in 2022-04, with the labels that each got.

#6306 Fix for error in 'Using Polar and Log-Polar Transformations for Registration' (#6304)
  doc/examples/registration/plot_register_rotation.py
Labels: type: documentation, action: mrg+1, type: bug fix

#6312 Backport PR #6306 on branch v0.19.x (Fix for error in 'Using Polar and Log-Polar Transformations for Registration' (#6304))
  doc/examples/registration/plot_register_rotation.py
Labels: type: documentation, action: mrg+1, type: bug fix

#6271 hough_line_peaks fix for corner case with optimal angle=0
  skimage/transform/hough_transform.py
  skimage/transform/tests/test_hough_transform.py
Labels: action: mrg+1, type: bug fix, backport: 0.19.x

#6307 Remove undefined 'python_to_notebook' in doc/ext/notebook_doc.py
  doc/ext/notebook_doc.py
Labels: type: maintenance

#6313 Backport PR #6271 on branch v0.19.x (hough_line_peaks fix for corner case with optimal angle=0)
  requirements/default.txt
  skimage/transform/hough_transform.py
  skimage/transform/tests/test_hough_transform.py
Labels: action: mrg+1, type: bug fix, backport: 0.19.x

#6315 Fix CI by pinning to Pillow<9.1.0
  requirements/default.txt
Labels: type: maintenance, type: bug fix

#6300 New thumbnail for "Datasets" example by adjusting contrast
  doc/examples/data/plot_3d.py
Labels: type: documentation, action: mrg+1

#6301 New thumbnail for Specific images
  doc/examples/data/plot_specific.py
Labels: type: documentation, action: mrg+1

#6303 Cython style: prefer cnp.float32_t and cnp.float64_t for clarity
  skimage/_shared/fast_exp.pxd
  skimage/draw/_draw.pyx
  skimage/exposure/tests/test_exposure.py
  skimage/feature/_hessian_det_appx_pythran.py
  skimage/feature/_hoghistogram.pyx
  skimage/feature/_sift.pyx
  skimage/feature/_texture.pyx
  skimage/feature/censure.py
  skimage/feature/censure_cy.pyx
  skimage/feature/corner_cy.pyx
  skimage/feature/match.py
  skimage/feature/texture.py
  skimage/filters/_multiotsu.pyx
  skimage/filters/_window.py
  skimage/filters/edges.py
  skimage/filters/rank/bilateral_cy.pyx
  skimage/filters/rank/core_cy.pxd
  skimage/filters/rank/core_cy.pyx
  skimage/filters/rank/core_cy_3d.pxd
  skimage/filters/rank/core_cy_3d.pyx
  skimage/filters/rank/generic.py
  skimage/filters/rank/generic_cy.pyx
  skimage/filters/rank/percentile_cy.pyx
  skimage/filters/rank/tests/test_rank.py
  skimage/future/graph/_ncut_cy.pyx
  skimage/future/graph/rag.py
  skimage/graph/heap.pxd
  skimage/graph/heap.pyx
  skimage/io/_plugins/_colormixer.pyx
  skimage/io/_plugins/_histograms.pyx
  skimage/measure/_find_contours.py
  skimage/measure/_find_contours_cy.pyx
  skimage/measure/_marching_cubes_lewiner_cy.pyx
  skimage/measure/_moments.py
  skimage/measure/_pnpoly.pyx
  skimage/measure/_regionprops.py
  skimage/measure/_regionprops_utils.py
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
  skimage/measure/tests/test_moments.py
  skimage/measure/tests/test_regionprops.py
  skimage/metrics/tests/test_structural_similarity.py
  skimage/restoration/_denoise_cy.pyx
  skimage/restoration/_nl_means_denoising.pyx
  skimage/restoration/_unwrap_1d.pyx
  skimage/restoration/_unwrap_2d.pyx
  skimage/restoration/_unwrap_3d.pyx
  skimage/restoration/tests/test_denoise.py
  skimage/restoration/unwrap.py
  skimage/segmentation/_felzenszwalb_cy.pyx
  skimage/segmentation/_slic.pyx
  skimage/segmentation/_watershed_cy.pyx
  skimage/transform/_geometric.py
  skimage/transform/_hough_transform.pyx
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
  skimage/util/tests/test_dtype.py
Labels: type: maintenance, action: mrg+1

#6296 Add spacing to regionprops and moments.
  skimage/measure/_moments.py
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_moments.py
  skimage/measure/tests/test_regionprops.py
Labels: type: enhancement

#6323 parameterize moments tests
  skimage/measure/tests/test_moments.py
Labels: type: maintenance, action: mrg+1

#6322 Fix skeletonize behavior
  skimage/morphology/_skeletonize.py
  skimage/morphology/_skeletonize_cy.pyx
  skimage/morphology/tests/test_skeletonize.py
Labels: type: documentation, type: maintenance

#6334 backport PR 6328: Fix issue with newer versions of matplotlib in manual segmentation
  skimage/future/manual_segmentation.py
Labels: type: bug fix

#6343 avoid warnings about change to v3 API from imageio
  skimage/io/_plugins/imageio_plugin.py
Labels: type: maintenance, action: mrg+1, backport: 0.19.x

#6327 skeletonize maintenance
  skimage/morphology/_skeletonize.py
  skimage/morphology/_skeletonize_cy.pyx
Labels: type: maintenance

#6344 Backport PR #6343 on branch v0.19.x (avoid warnings about change to v3 API from imageio)
  skimage/io/_plugins/imageio_plugin.py
Labels: type: maintenance, action: mrg+1, backport: 0.19.x

#6339 Add skip-4 draft
  doc/source/skips/4-transition-to-v2.rst
  doc/source/skips/index.md
Labels: type: documentation

#6355 remove use of deprecated kwargs from `test_tifffile_kwarg_passthrough`
  skimage/io/tests/test_tifffile.py
Labels: type: maintenance, backport: 0.19.x

#6357 Backport PR #6355 on branch v0.19.x (remove use of deprecated kwargs from `test_tifffile_kwarg_passthrough`)
  skimage/io/tests/test_tifffile.py
Labels: type: maintenance, backport: 0.19.x

#6354 Improve histogram matching performance on unsigned integer data (resume #6209)
  benchmarks/benchmark_exposure.py
  skimage/exposure/histogram_matching.py
  skimage/exposure/tests/test_histogram_matching.py
Labels: action: mrg+1, type: perfomance

#6352 Fix channel_axis default for cycle_spin
  skimage/restoration/_cycle_spin.py
  skimage/restoration/tests/test_denoise.py
Labels: action: mrg+1, type: bug fix

#6348 Fix smoothed image computation when mask is None in canny
  skimage/feature/_canny.py
  skimage/feature/tests/test_canny.py
Labels: type: bug fix, backport: 0.19.x

#6358 Backport PR #6352 on branch v0.19.x (Fix channel_axis default for cycle_spin)
  skimage/restoration/_cycle_spin.py
  skimage/restoration/tests/test_denoise.py
Labels: action: mrg+1, type: bug fix

#6359 Backport PR #6348 on branch v0.19.x (Fix smoothed image computation when mask is None in canny)
  skimage/feature/_canny.py
  skimage/feature/tests/test_canny.py
Labels: :fire_extinguisher: :bug: type: bug fix, backport: 0.19.x

#6362 v0.19.3 release notes
  doc/release/release_0.19.rst
Labels: :page_facing_up: type: documentation

#6369 Fix windows wheels: use `vsdevcmd.bat` to make sure `rc.exe` is on the path
  .github/workflows/wheel_tests_and_release.yml
Labels: :robot: type: infrastructure
