Repository scikit-image/scikit-image, pull requests merged in 2022-08, with the labels that each got.

#6457 Remove repeated import in canny_py
  skimage/feature/_canny.py
Labels: :robot: Maintenance

#6454 Make Wiener restoration N-d
  skimage/restoration/deconvolution.py
  skimage/restoration/tests/test_restoration.py
Labels: :fast_forward: Enhancement, :+1: OK to merge

#6476 Use broadcast_to instead of as_strided to generate broadcasted arrays.
  skimage/future/graph/rag.py
Labels: :fast_forward: Enhancement, :+1: OK to merge

#6272 add warning on non-integer image inputs to local_binary_pattern
  skimage/feature/tests/test_texture.py
  skimage/feature/texture.py
Labels: :robot: Maintenance

#6483 Use matplotlib.colormaps instead of deprecated cm.get_cmap in show_rag
  skimage/future/graph/rag.py
Labels: :robot: Maintenance

#6458 Refactor occurences of `f = open(...)` using `with open(...) as f` instead
  doc/tools/apigen.py
  skimage/io/tests/test_sift.py
Labels: :robot: Maintenance, :fast_forward: Enhancement, :+1: OK to merge

#6490 Use pyplot.get_cmap for compatiblity with matplotlib 3.3 to 3.6 in in show_rag
  skimage/future/graph/rag.py
Labels: :robot: Maintenance, :+1: OK to merge

#6484 Use context manager when possible
  doc/source/random_gallery.py
  skimage/_shared/_tempfile.py
  skimage/_shared/testing.py
  skimage/io/_plugins/fits_plugin.py
  skimage/io/tests/test_imageio.py
  skimage/io/tests/test_imread.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_sift.py
  skimage/io/tests/test_simpleitk.py
  skimage/io/tests/test_tifffile.py
Labels: :robot: Maintenance, :+1: OK to merge

#6453 No valueerror for underdetermined
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: :robot: Maintenance, :scroll: API

#6478 Update Ubuntu LTS version on Actions workflows
  .github/workflows/benchmarks.yml
  .github/workflows/build-docs.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
Labels: :robot: Maintenance, :+1: OK to merge, :robot: Infrastructure

#6472 Add `alpha` argument to `adapted_rand_error`
  skimage/metrics/_adapted_rand_error.py
  skimage/metrics/tests/test_segmentation_metrics.py
Labels: :fast_forward: Enhancement, :+1: OK to merge
