Repository scikit-image/scikit-image, pull requests merged in 2023-06, with the labels that each got.

#6976 Ignore tight layout warning from matplotlib pre-release
  skimage/io/tests/test_mpl_imshow.py
Labels: :wrench: type: Maintenance

#6978 Add Lazy loader to skimage.exposure
  skimage/exposure/__init__.py
  skimage/exposure/__init__.pyi
  skimage/exposure/_adapthist.py
  skimage/exposure/meson.build
Labels: :chart_with_upwards_trend: type: Performance, :wave: Outreachy

#6975 Fix sparse index type casting in `skimage.graph._ncut`
  skimage/graph/_ncut.py
  skimage/graph/_ncut_cy.pyx
Labels: :adhesive_bandage: type: Bug fix

#6980 Remove temporary constraint <2.28 for imageio
  TODO.txt
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance

#6981 Add lazy loading to skimage.future module
  skimage/future/__init__.py
  skimage/future/__init__.pyi
  skimage/future/meson.build
Labels: :chart_with_upwards_trend: type: Performance

#6949 Add missing PRs to release notes
  doc/source/release_notes/release_0.21.rst
Labels: :page_facing_up: type: Documentation

#6982 Pin milestone labeler to v0.1.0 SHA
  .github/workflows/milestone-merged-prs.yaml
Labels: :robot: type: Infrastructure

#6989 Use a more descriptive title for current inpainting example.
  doc/examples/filters/plot_inpaint.py
Labels: :page_facing_up: type: Documentation

#6858 Add image sequence of in-vivo human cornea to data registry.
  skimage/data/__init__.pyi
  skimage/data/_fetchers.py
  skimage/data/_registry.py
Labels: :baby: type: New feature

#6996 Don't test numpy prerelease on azure
  azure-pipelines.yml
Labels: :wrench: type: Maintenance

#6998 Fix URLs to the install page
  skimage/__init__.py
  skimage/data/_fetchers.py
Labels: :page_facing_up: type: Documentation

#7002 Upper pin imageio
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance

#6983 Add lazy loading to skimage.feature module
  LICENSE.txt
  skimage/feature/__init__.py
  skimage/feature/__init__.pyi
  skimage/feature/_fisher_vector.py
  skimage/feature/censure.py
  skimage/feature/meson.build
  skimage/feature/orb.py
  skimage/feature/tests/test_fisher_vector.py
Labels: :chart_with_upwards_trend: type: Performance

#6985 Add lazy loading to graph submodule
  skimage/graph/__init__.py
  skimage/graph/__init__.pyi
  skimage/graph/meson.build
Labels: :chart_with_upwards_trend: type: Performance

#6987 Fix equation for Wiener filter in `restoration.wiener`'s docstring
  skimage/restoration/deconvolution.py
Labels: :page_facing_up: type: Documentation

#6999 Add lazy loading to measure submodule
  skimage/measure/__init__.py
  skimage/measure/__init__.pyi
  skimage/measure/meson.build
Labels: :chart_with_upwards_trend: type: Performance

#6984 Fix missing links in INSTALL.rst and simplify language
  INSTALL.rst
Labels: :page_facing_up: type: Documentation

#7003 meson: allow proper selection of NumPy, Pythran in cross builds
  skimage/meson.build
Labels: :wrench: type: Maintenance

#6991 Edit installation and contributor guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
  INSTALL.rst
Labels: :page_facing_up: type: Documentation

#7008 Fix URLs that lead to 404 page
  doc/source/development/core_developer.md
  doc/source/release_notes/release_0.18.rst
Labels: :page_facing_up: type: Documentation

#7009 Add lazy loading to skimage.transform module.
  skimage/transform/__init__.py
  skimage/transform/__init__.pyi
  skimage/transform/meson.build
  skimage/transform/pyramids.py
Labels: :chart_with_upwards_trend: type: Performance

#7006 Unpin imageio and add warningfilter
  TODO.txt
  pyproject.toml
  requirements/default.txt
  skimage/_shared/testing.py
Labels: :wrench: type: Maintenance

#7014 Update to latest attach-next-milestone action
  .github/workflows/milestone-merged-prs.yaml
Labels: :wrench: type: Maintenance

#7017 [dev-tps-warping] Apply PEP08 guidelines
  skimage/transform/_thin_plate_splines.py
Labels: :wrench: type: Maintenance

#7015 Ensure existing target directory for `random.js`
  doc/ext/skimage_extensions.py
Labels: :wrench: type: Maintenance, :robot: type: Infrastructure

#7018 Assign next milestone only for PRs targeting `main` branch
  .github/workflows/milestone-merged-prs.yaml
Labels: :robot: type: Infrastructure

#7019 Add missing directories to `spin docs --clean` command
  .spin/cmds.py
Labels: :robot: type: Infrastructure

#7025 [dev-tps-warping] Replace `_interpoint_distances` with SciPy's `cdist`
  skimage/transform/_thin_plate_splines.py
Labels: :wrench: type: Maintenance, :wave: Outreachy

#7034 DOC: fix ridge detection docstrings.
  skimage/filters/ridges.py
Labels: :page_facing_up: type: Documentation

#7043 Update lazy_loader
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance
