Repository scikit-image/scikit-image, pull requests merged in 2023-05, with the labels that each got.

#6764 Use imageio v3 API
  pyproject.toml
  requirements/default.txt
  skimage/data/_registry.py
  skimage/io/_plugins/imageio_plugin.py
Labels: :wrench: Maintenance

#6925 Add 0.21 release notes
  TODO.txt
  doc/source/conf.py
  doc/source/release_notes/release_0.21.rst
  doc/source/release_notes/release_dev.rst
  doc/source/release_notes/release_template.rst
  tools/generate_release_notes.py
Labels: :page_facing_up: Documentation

#6935 Fix inclusion of `random.js` in HTML output
  doc/ext/skimage_extensions.py
Labels: :robot: Infrastructure, :adhesive_bandage: Bug fix

#6938 Skip unstable test in `ransac`'s docstring
  skimage/measure/fit.py
Labels: :wrench: Maintenance

#6907 Check if `spacing` parameter is tuple in `regionprops`
  skimage/measure/_regionprops.py
  skimage/measure/_regionprops_utils.py
  skimage/measure/tests/test_regionprops.py
Labels: :fast_forward: Enhancement

#6942 Use context manager to ensure urlopen buffer is closed
  skimage/io/collection.py
  skimage/io/tests/test_collection.py
  skimage/io/tests/test_io.py
  skimage/io/util.py
Labels: :adhesive_bandage: Bug fix

#6926 Change geometric transform inverse to property
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: :scroll: API

#6900 apply spacing rescaling when computing centroid_weighted
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :adhesive_bandage: Bug fix

#6940 Respect SPHINXOPTS and add --install-deps flags to `spin docs`
  .spin/cmds.py
Labels: :robot: Infrastructure

#6947 Point logo in generated HTML docs at scikit-image.org
  doc/source/conf.py
Labels: :page_facing_up: Documentation, :wrench: Maintenance

#6956 Enable testing against nightly upstream wheels
  .github/workflows/tests.yml
  skimage/io/tests/test_histograms.py
  skimage/io/tests/test_imageio.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_simpleitk.py
Labels: :robot: Infrastructure

#6957 Add nightly wheel builder
  .github/workflows/build_wheels.yml
  .github/workflows/cron_weekly.yml
  .github/workflows/nightly-wheel-build.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
Labels: :robot: Infrastructure

#6959 Run weekly tests on nightly wheels
  .github/workflows/build_docs.yml
  .github/workflows/cron_weekly.yml
  .github/workflows/dormant_issues_prs.yml
  .github/workflows/nightly_wheel_build.yml
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/wheel_tests_and_release.yml
  .github/workflows/wheels_recipe.yml
Labels: :robot: Infrastructure

#6960 CI: ensure that a "type: " label is present on each PR
  .github/workflows/label-check.yaml
Labels: :robot: type: Infrastructure

#6969 Fix NumPy 1.25 deprecation warnings
  skimage/exposure/exposure.py
  skimage/measure/_regionprops.py
  skimage/transform/tests/test_warps.py
  tools/github/before_install.sh
Labels: :wrench: type: Maintenance

#6968 Expose `GeometricTransform.residuals` in HTML doc
  doc/tools/apigen.py
  skimage/transform/_geometric.py
  skimage/transform/tests/test_geometric.py
Labels: :page_facing_up: type: Documentation, :wrench: type: Maintenance

#6972 Revert jupyterlite
  doc/examples/applications/plot_3d_image_processing.py
  doc/examples/applications/plot_3d_interaction.py
  doc/examples/applications/plot_3d_structure_tensor.py
  doc/examples/color_exposure/plot_adapt_hist_eq_3d.py
  doc/examples/data/plot_3d.py
  doc/examples/data/plot_scientific.py
  doc/examples/segmentation/plot_rolling_ball.py
  doc/source/conf.py
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance

#6971 Add Lazy loading to skimage.draw submodule
  skimage/draw/__init__.py
  skimage/draw/__init__.pyi
  skimage/draw/_random_shapes.py
  skimage/draw/meson.build
Labels: :chart_with_upwards_trend: type: Performance, :wave: Outreachy

#6973 Don't test numpy nightlies due to transcendental functions issue
  .github/workflows/test_nightlies_on_main.yml
Labels: :wrench: type: Maintenance
