Repository scikit-image/scikit-image, pull requests merged in 2023-01, with the labels that each got.

#6646 Fix doc build on CircleCI and add ccache
  .circleci/config.yml
Labels: :robot: Infrastructure, :adhesive_bandage: Bug fix

#6556 Prepare release notes for v0.20.0
  doc/release/release_dev.rst
Labels: :page_facing_up: Documentation

#6624 Fix the order of return values for `hessian_matrix`
  skimage/feature/corner.py
  skimage/feature/tests/test_corner.py
Labels: :+1: OK to merge, :adhesive_bandage: Bug fix

#6674 Move `future.graph` to `skimage.graph`
  TODO.txt
  doc/examples/segmentation/plot_boundary_merge.py
  doc/examples/segmentation/plot_ncut.py
  doc/examples/segmentation/plot_rag.py
  doc/examples/segmentation/plot_rag_boundary.py
  doc/examples/segmentation/plot_rag_draw.py
  doc/examples/segmentation/plot_rag_mean_color.py
  doc/examples/segmentation/plot_rag_merge.py
  doc/tools/build_modref_templates.py
  skimage/conftest.py
  skimage/future/__init__.py
  skimage/future/graph/__init__.py
  skimage/future/graph/meson.build
  skimage/future/graph/setup.py
  skimage/future/graph/tests/__init__.py
  skimage/future/graph/tests/meson.build
  skimage/future/setup.py
  skimage/future/tests/test_graph.py
  skimage/graph/__init__.py
  skimage/graph/_graph_cut.py
  skimage/graph/_graph_merge.py
  skimage/graph/_ncut.py
  skimage/graph/_ncut_cy.pyx
  skimage/graph/_rag.py
  skimage/graph/meson.build
  skimage/graph/setup.py
  skimage/graph/tests/meson.build
  skimage/graph/tests/test_rag.py
Labels: :scroll: API

#6686 Remove leftover `gtk_plugin.ini`
  skimage/io/_plugins/gtk_plugin.ini
  skimage/io/_plugins/meson.build
Labels: :wrench: Maintenance

#6685 Advise users about removal of `future.graph.ncut`
  skimage/future/graph/__init__.py
  skimage/future/tests/test_graph.py
Labels: :page_facing_up: Documentation

#6692 Fix `graph.RAG.merge_nodes` for in-place merging
  skimage/graph/_rag.py
  skimage/graph/tests/test_rag.py
Labels: :adhesive_bandage: Bug fix

#6688 Document L*a*b* range in two colorspace conversion functions.
  skimage/color/colorconv.py
Labels: :page_facing_up: Documentation

#6189 Add colocalization metrics
  doc/examples/applications/plot_colocalization_metrics.py
  skimage/_shared/utils.py
  skimage/measure/__init__.py
  skimage/measure/_colocalization.py
  skimage/measure/meson.build
  skimage/measure/tests/meson.build
  skimage/measure/tests/test_colocalization.py
Labels: :fast_forward: Enhancement

#6656 remove warnings and unnecessary messages
  doc/examples/color_exposure/plot_tinting_grayscale_images.py
Labels: :+1: OK to merge

#3706 Add offset to regionprops
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :fast_forward: Enhancement

#4953 Add (interactive) slice explorer in plotly.
  doc/examples/applications/plot_3d_image_processing.py
Labels: :page_facing_up: Documentation, :fast_forward: Enhancement

#6701 Keep deprecated functions available in `skimage.filters`
  skimage/filters/__init__.pyi
  skimage/filters/ridges.py
Labels: :adhesive_bandage: Bug fix, :arrow_down_small: Deprecation

#6666 Add verification to image argument dimension on skimage.filters.rank module
  skimage/filters/rank/generic.py
  skimage/filters/rank/tests/test_rank.py
Labels: :adhesive_bandage: Bug fix
