Repository scikit-image/scikit-image, pull requests merged in 2023-09, with the labels that each got.

#7098 For uniform intensity images, return intensity value as threshold
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: :adhesive_bandage: type: Bug fix

#7118 MNT: Remove np.float_ alias; it is removed in NumPy 2.0
  skimage/util/dtype.py
Labels: :wrench: type: Maintenance

#7101 Fix for NumPy 1.26
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/wheels_recipe.yml
  azure-pipelines.yml
  tools/github/before_install.sh
Labels: :wrench: type: Maintenance, :arrow_up: Upstream

#7121 Update minimum sklearn (SPEC 0)
  pyproject.toml
  requirements/docs.txt
  requirements/optional.txt
Labels: :wrench: type: Maintenance

#7119 Update for NumPy 2 namespace cleanup
  skimage/util/dtype.py
Labels: :wrench: type: Maintenance

#7123 DOC: minor numpydoc syntax update
  doc/examples/registration/plot_stitching.py
  skimage/registration/tests/test_tvl1.py
  skimage/restoration/inpaint.py
Labels: :wrench: type: Maintenance

#7116 Fix color conversion error
  skimage/color/colorconv.py
Labels: :adhesive_bandage: type: Bug fix

#7122 Update for NumPy 2 namespace cleanup
  benchmarks/benchmark_restoration.py
  skimage/color/colorconv.py
  skimage/color/tests/test_colorconv.py
  skimage/io/tests/test_imageio.py
  skimage/io/tests/test_imread.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_simpleitk.py
  skimage/measure/_blur_effect.py
  skimage/measure/tests/test_moments.py
  skimage/restoration/_rolling_ball.py
  skimage/restoration/deconvolution.py
  skimage/restoration/tests/test_denoise.py
  skimage/segmentation/_clear_border.py
  skimage/segmentation/tests/test_slic.py
  skimage/transform/_geometric.py
  skimage/transform/_hough_transform.pyx
  skimage/transform/tests/test_warps.py
  skimage/util/tests/test_montage.py
  tools/precompute/_precompute_nsphere_decompositions.py
Labels: :wrench: type: Maintenance

#7125 Temporary work-around for NEP 51 numpy scalar reprs + doctests
  TODO.txt
  skimage/conftest.py
Labels: :wrench: type: Maintenance

#7126 Update lazy loader
  pyproject.toml
Labels: :wrench: type: Maintenance

#7063 Update pytest config in `pyproject.toml` with repo-review recommendations
  pyproject.toml
Labels: :robot: type: Infrastructure

#7092 Avoid unnecessary padding in `skimage.measure.block_resize`
  skimage/measure/block.py
Labels: :chart_with_upwards_trend: type: Performance

#7112 Make phase_cross_correlation return ndarray when disambiguate=True
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: :adhesive_bandage: type: Bug fix

#7142 Fix PEP 8 issues in `test_phase_cross_correlation.py`
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: :wrench: type: Maintenance

#7141 Remove parallelism in face detection gallery example
  doc/examples/applications/plot_haar_extraction_selection_classification.py
Labels: :wrench: type: Maintenance

#7136 in check_dtype let masks be different sizes
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :adhesive_bandage: type: Bug fix

#7139 Enable version warning banners for docs
  RELEASE.txt
  doc/source/_static/version_switcher.json
  doc/source/conf.py
  pyproject.toml
  requirements/docs.txt
Labels: :page_facing_up: type: Documentation, :arrow_up: Upstream

#7150 Update spin version to 0.6
  pyproject.toml
  requirements/build.txt
Labels: :wrench: type: Maintenance

#7148 Match pep8speaks and ruff line lengths to 88
  .pep8speaks.yml
Labels: :wrench: type: Maintenance

#7145 Include Plausible analytics from Scientific Python in our HTML docs
  doc/source/conf.py
Labels: :page_facing_up: type: Documentation

#7131 Update _polygon2mask.py
  skimage/draw/_polygon2mask.py
Labels: :page_facing_up: type: Documentation

#7137 Remove last reference to distutils in `_build_utils/tempita.py`
  skimage/_build_utils/tempita.py
Labels: :wrench: type: Maintenance

#7155 Update doc requirements
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance

#7106 Update minimal version of numpydoc to 1.6
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance

#7156 Make PyWavelets an optional dependency
  pyproject.toml
  requirements/default.txt
  requirements/docs.txt
  requirements/optional.txt
  skimage/restoration/_cycle_spin.py
  skimage/restoration/_denoise.py
  skimage/restoration/j_invariant.py
  skimage/restoration/tests/test_denoise.py
  skimage/restoration/tests/test_j_invariant.py
Labels: :scroll: type: API

#7082 Build wheels for py3.12
  .github/workflows/wheels_recipe.yml
Labels: :wrench: type: Maintenance

#7161 Remove deprecated inverse function
  TODO.txt
  skimage/filters/__init__.pyi
  skimage/filters/lpi_filter.py
Labels: :scroll: type: API

#7162 Remove deprecated compute_hessian_eigenvalues
  TODO.txt
  skimage/filters/__init__.pyi
  skimage/filters/ridges.py
Labels: :scroll: type: API

#7164 Handle gaussian filter deprecation
  TODO.txt
  skimage/_shared/filters.py
  skimage/filters/tests/test_gaussian.py
Labels: :wrench: type: Maintenance

#7165 Update TODO (see #6899)
  TODO.txt
Labels: :wrench: type: Maintenance

#7167 Announce Python 3.12 support
  .github/workflows/tests.yml
  pyproject.toml
Labels: :wrench: type: Maintenance

#7172 Remove pep8speaks config
  .pep8speaks.yml
Labels: :wrench: type: Maintenance

#7147 In registration.phase_cross_correlation: catch expected runtime warning when disambiguate=True
  skimage/registration/_phase_cross_correlation.py
Labels: :wrench: type: Maintenance

#7171 Use pre-commit bot
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: :wrench: type: Maintenance

#7174 Deprecate `return_error` in `phase_cross_correlation` only in 0.23
  TODO.txt
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: :scroll: type: API

#7175 Fix missing warnings import in `phase_cross_correlation`
  skimage/registration/_phase_cross_correlation.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: :wrench: type: Maintenance

#7177 Fix release notes error
  doc/source/release_notes/release_dev.rst
Labels: :wrench: type: Maintenance

#7178 Use trusted publisher
  .github/workflows/wheel_tests_and_release.yml
Labels: :wrench: type: Maintenance
