Repository scikit-image/scikit-image, pull requests merged in 2023-03, with the labels that each got.

#6745 Fix threshold_li(): prevent log(0) on single-value background.
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
Labels: :+1: OK to merge, :adhesive_bandage: Bug fix

#6703 shift and normalize data before fitting circle or ellipse
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: :adhesive_bandage: Bug fix

#6756 Fix duplicate gray morphology test case
  skimage/morphology/tests/test_gray.py
Labels: :adhesive_bandage: Bug fix

#6779 Link full license to README
  README.md
Labels: :page_facing_up: Documentation

#6789 Update .devpy/cmds.py to match latest devpy
  .devpy/cmds.py
Labels: :wrench: Maintenance, :adhesive_bandage: Bug fix

#6792 Avoid error when using conda.
  INSTALL.rst
Labels: :adhesive_bandage: Bug fix

#6786 Make join_segmentations return array maps from output to input labels
  skimage/segmentation/_join.py
  skimage/segmentation/tests/test_join.py
Labels: :+1: OK to merge

#6825 Relax reproduce section in bug issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: :wrench: Maintenance, :robot: Infrastructure

#6805 Resolved the misleading error message on passing an invalid method
  skimage/morphology/_skeletonize.py
  skimage/morphology/tests/test_skeletonize.py
Labels: :+1: OK to merge

#6836 Sign error fix in measure.regionprops for orientations of 45 degrees
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :+1: OK to merge

#6839 segmentation.watershed returns wrong data type bug fix
  skimage/segmentation/_watershed.py
  skimage/segmentation/_watershed_cy.pyx
  skimage/segmentation/tests/test_watershed.py
Labels: :page_facing_up: Documentation, :+1: OK to merge, :adhesive_bandage: Bug fix, :wave: Outreachy

#6842 Rename devpy to spin
  .gitattributes
  .spin/cmds.py
  dev.py
  pyproject.toml
  requirements/build.txt
  tools/generate_pyproject.toml.py
  tools/pyproject.toml.in
Labels: :wrench: Maintenance, :robot: Infrastructure

#6852 Handle NaNs when clipping in `transform.resize`
  skimage/transform/_warps.py
  skimage/transform/tests/test_warps.py
Labels: :+1: OK to merge, :adhesive_bandage: Bug fix

#6856 Update references to outdated dev.py with spin
  CONTRIBUTING.rst
  INSTALL.rst
  meson.md
Labels: :page_facing_up: Documentation, :wrench: Maintenance

#6788 Remove outdated build instructions from README
  README.md
Labels: :page_facing_up: Documentation

#6847 Speed up threshold_local function by fixing call to _supported_float_type
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
  skimage/color/delta_e.py
  skimage/filters/thresholding.py
  skimage/metrics/simple_metrics.py
  skimage/registration/_masked_phase_cross_correlation.py
  skimage/restoration/tests/test_denoise.py
  skimage/restoration/tests/test_inpaint.py
  skimage/restoration/uft.py
Labels: :wrench: Maintenance, :+1: OK to merge, :chart_with_upwards_trend: Performance
