Repository scikit-image/scikit-image, pull requests merged in 2023-07, with the labels that each got.

#7045 Remove conflicting setuptools upper pin
  tools/github/before_install.sh
Labels: :wrench: type: Maintenance

#6899 Remove future.graph after v0.21 release
  doc/tools/build_modref_templates.py
  skimage/conftest.py
  skimage/future/graph/__init__.py
  skimage/future/graph/meson.build
  skimage/future/meson.build
  skimage/future/tests/test_graph.py
Labels: :wrench: type: Maintenance

#7044 Cleanup from move to pyproject.toml
  .codecov.yml
  .github/workflows/tests.yml
  MANIFEST.in
Labels: :wrench: type: Maintenance

#6961 Rework `generate_release_notes.py` and add PR summary parsing
  .github/PULL_REQUEST_TEMPLATE.md
  tools/generate_release_notes.py
Labels: :robot: type: Infrastructure

#6853 Add inpainting example to gallery
  doc/examples/applications/plot_cornea_spot_inpainting.py
Labels: :page_facing_up: type: Documentation, :wave: Outreachy

#7021 Add lazy loading to skimage.restoration
  benchmarks/benchmark_restoration.py
  skimage/restoration/__init__.py
  skimage/restoration/__init__.pyi
  skimage/restoration/_rolling_ball.py
  skimage/restoration/meson.build
  skimage/restoration/tests/test_rolling_ball.py
Labels: :chart_with_upwards_trend: type: Performance

#7056 Ignore new matplotlib warning
  skimage/_shared/testing.py
Labels: :wrench: type: Maintenance

#7054 Update spin
  pyproject.toml
  requirements/build.txt
Labels: :wrench: type: Maintenance

#7049 Use packaged version of `generate_release_notes.py` (`changelist`)
  RELEASE.txt
  requirements/_release_tools.txt
  tools/generate_release_notes.py
Labels: :page_facing_up: type: Documentation

#7057 Ignore SciPy 1.12.dev0 deprecation warning
  skimage/_shared/testing.py
Labels: :wrench: type: Maintenance

#7058 Include expected warning for SciPy 1.12
  skimage/segmentation/tests/test_random_walker.py
Labels: :wrench: type: Maintenance

#7052 Mark NaN-related deprecation warning from `np.clip` as optional in tests
  TODO.txt
  skimage/exposure/tests/test_exposure.py
Labels: :wrench: type: Maintenance

#7010 Fix abs value function warnings
  skimage/transform/_hough_transform.pyx
Labels: :wrench: type: Maintenance

#7059 Temporary fix for wheel recipe
  .github/workflows/wheels_recipe.yml
  azure-pipelines.yml
  pyproject.toml
  requirements/build.txt
  tools/github/before_install.sh
Labels: :wrench: type: Maintenance

#7039 Add num_pixels and coords_scaled to regionprops_table
  pyproject.toml
  requirements/test.txt
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :adhesive_bandage: type: Bug fix

#7060 Temporary fix for wheel building
  .github/workflows/wheels_recipe.yml
Labels: :wrench: type: Maintenance

#7032 Add lazy loading to skimage.registration
  skimage/registration/__init__.py
  skimage/registration/__init__.pyi
  skimage/registration/meson.build
Labels: :chart_with_upwards_trend: type: Performance

#7076 Update video.rst
  doc/source/user_guide/video.rst
Labels: :adhesive_bandage: type: Bug fix

#7077 Remove outdated comment
  skimage/data/_binary_blobs.py
Labels: :wrench: type: Maintenance
