Repository scikit-image/scikit-image, pull requests merged in 2023-10, with the labels that each got.

#7180 Use checkout action version 4
  .github/workflows/benchmarks.yml
  .github/workflows/build_docs.yml
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
  .github/workflows/wheels_recipe.yml
Labels: :robot: type: Infrastructure

#7182 Update 0.22.0 release notes
  doc/source/release_notes/release_dev.rst
  requirements/_release_tools.txt
Labels: :page_facing_up: type: Documentation

#7160 Update instructions for updating dev environment.
  INSTALL.rst
  pyproject.toml
  requirements/developer.txt
Labels: :page_facing_up: type: Documentation

#7186 Do not compare types, use isinstance
  skimage/io/_plugins/fits_plugin.py
  skimage/io/collection.py
  skimage/segmentation/_chan_vese.py
Labels: :wrench: type: Maintenance

#7188 Increase tolerance for moments test for 32 bit floats
  skimage/measure/tests/test_moments.py
Labels: :wrench: type: Maintenance

#7189 Temporarily pin Cython to <3.0.3 until CI is fixed
  pyproject.toml
  requirements/build.txt
Labels: :wrench: type: Maintenance, :arrow_up: Upstream

#7193 Remove obsolete meson instructions
  meson.md
Labels: :wrench: type: Maintenance

#7196 Update wording on stalebot to assume core devs dropped the ball
  .github/workflows/dormant_issues_prs.yml
Labels: :robot: type: Infrastructure

#7201 Temporarily pin Cython to <3.0.3 until CI is fixed, take 2
  pyproject.toml
Labels: :wrench: type: Maintenance

#7200 Fix chocolatey
  azure-pipelines.yml
Labels: :wrench: type: Maintenance

#7202 Make titles in RAG gallery examples more explicit
  doc/examples/segmentation/plot_rag.py
  doc/examples/segmentation/plot_rag_boundary.py
  doc/examples/segmentation/plot_rag_mean_color.py
  doc/examples/segmentation/plot_rag_merge.py
Labels: :page_facing_up: type: Documentation

#7208 Pin Pillow to <10.1.0 until incompatibility with imageio is fixed
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance

#7153 Exception raised for hog surprising result
  skimage/feature/_hog.py
  skimage/feature/tests/test_hog.py
Labels: :adhesive_bandage: type: Bug fix

#7215 Apply black to `_hog.py` after previous merge lacking black
  skimage/feature/_hog.py
  skimage/feature/tests/test_hog.py
Labels: :wrench: type: Maintenance

#7214 Unpin Cython after release of Cython 3.0.4
  pyproject.toml
  requirements/build.txt
Labels: :wrench: type: Maintenance, :arrow_up: Upstream

#7217 Drop Python 3.9 support
  .binder/runtime.txt
  .github/workflows/build_docs.yml
  .github/workflows/tests.yml
  .github/workflows/wheels_recipe.yml
  INSTALL.rst
  azure-pipelines.yml
  doc/tools/apigen.py
  pyproject.toml
  skimage/feature/_fisher_vector.py
  skimage/filters/thresholding.py
  skimage/io/collection.py
  skimage/measure/fit.py
  skimage/segmentation/_watershed.py
  skimage/transform/tests/test_geometric.py
Labels: :wrench: type: Maintenance

#7218 Update Azure job name following the drop of Python 3.9
  azure-pipelines.yml
Labels: :robot: type: Infrastructure

#7211 Added Lazy Loader to skimage.metrics module
  skimage/metrics/__init__.py
  skimage/metrics/__init__.pyi
  skimage/metrics/meson.build
Labels: :chart_with_upwards_trend: type: Performance

#7154 Specify default markers in watershed docstring.
  skimage/segmentation/_watershed.py
Labels: :page_facing_up: type: Documentation

#7226 Silence PyData theme warning about new default for "navigation_with_keys"
  TODO.txt
  doc/source/conf.py
Labels: :page_facing_up: type: Documentation

#7228 Fix reference formatting for nitpicky sphinx
  CONTRIBUTING.rst
  doc/examples/applications/plot_3d_interaction.py
  doc/examples/segmentation/plot_compact_watershed.py
  doc/examples/segmentation/plot_metrics.py
  doc/examples/segmentation/plot_rag.py
  doc/examples/segmentation/plot_regionprops_table.py
  doc/source/conf.py
  doc/source/release_notes/release_0.14.rst
  doc/source/release_notes/release_0.16.rst
  doc/source/release_notes/release_0.17.rst
  doc/source/release_notes/release_0.20.rst
  doc/source/release_notes/release_0.21.rst
  doc/source/skips/3-transition-to-v1.rst
  doc/source/skips/4-transition-to-v2.rst
  doc/source/user_guide/geometrical_transform.rst
  doc/source/user_guide/glossary.md
  doc/source/user_guide/numpy_images.rst
  doc/tools/apigen.py
  skimage/_shared/filters.py
  skimage/color/colorlabel.py
  skimage/data/_fetchers.py
  skimage/feature/_fisher_vector.py
  skimage/feature/_hog.py
  skimage/feature/orb.py
  skimage/filters/rank/bilateral.py
  skimage/future/trainable_segmentation.py
  skimage/graph/_rag.py
  skimage/io/_io.py
  skimage/io/collection.py
  skimage/io/manage_plugins.py
  skimage/io/sift.py
  skimage/measure/_label.py
  skimage/morphology/extrema.py
  skimage/morphology/footprints.py
  skimage/segmentation/morphsnakes.py
  skimage/segmentation/random_walker_segmentation.py
Labels: :page_facing_up: type: Documentation
