Repository scikit-image/scikit-image, pull requests merged in 2024-05, with the labels that each got.

#7408 Use macos-12 runner
  .github/workflows/tests.yml
  .github/workflows/wheels_recipe.yml
Labels: :wrench: type: Maintenance

#7411 Fix typos in `skimage.measure.find_contours`
  skimage/measure/_find_contours.py
Labels: :page_facing_up: type: Documentation, :rocket: Quick win

#7414 Fix NumPy2 dtype promotion issues in pywt dependent code
  TODO.txt
  pyproject.toml
  skimage/metrics/simple_metrics.py
  skimage/restoration/_denoise.py
  skimage/segmentation/random_walker_segmentation.py
Labels: :wrench: type: Maintenance

#7415 Escape user-controlled variables in GA workflow
  .github/workflows/benchmarks.yml
Labels: :robot: type: Infrastructure

#7322 Standardize function signature of compare_images.
  TODO.txt
  skimage/util/compare.py
  skimage/util/tests/test_compare.py
Labels: :wrench: type: Maintenance, :hiking_boot: Path to skimage2

#7424 Caution about rolling ball performance
  skimage/restoration/_rolling_ball.py
Labels: :page_facing_up: type: Documentation
