Repository scikit-image/scikit-image, pull requests merged in 2024-08, with the labels that each got.

#7482 FIX Use python3 in Meson version script shebang
  skimage/_build_utils/version.py
Labels: :wrench: type: Maintenance

#7483 Fixup conda development installation instructions
  INSTALL.rst
Labels: :page_facing_up: type: Documentation

#7486 Address autosummary.import_cycle warning
  doc/source/conf.py
  doc/tools/apigen.py
Labels: :robot: type: Infrastructure

#7493 Temporarily exclude Dask 2024.8.0 to fix CI
  TODO.txt
  pyproject.toml
  requirements/optional.txt
Labels: :robot: type: Infrastructure, :rocket: Quick win

#7492 Uncomment `currentmodule` directive again
  doc/tools/apigen.py
Labels: :robot: type: Infrastructure, :rocket: Quick win

#7065 Fix dynamic max trials of RANSAC
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: :adhesive_bandage: type: Bug fix, :+1: 1st approval

#7481 Add CI to release nightly free-threaded wheels
  .github/workflows/wheels_recipe.yml
  skimage/segmentation/tests/test_clear_border.py
Labels: :robot: type: Infrastructure, :+1: 1st approval

#7459 Refactored tests for skeletonize
  .gitignore
  LICENSE.txt
  benchmarks/benchmark_morphology.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/_skeletonize_lee_cy.pyx.in
  skimage/morphology/_skeletonize_various_cy.pyx
  skimage/morphology/meson.build
  skimage/morphology/tests/meson.build
  skimage/morphology/tests/test_skeletonize.py
  skimage/morphology/tests/test_skeletonize_3d.py
Labels: :wrench: type: Maintenance, :+1: 1st approval

#7487 Complete deprecation of `plot_matches`
  TODO.txt
  doc/examples/features_detection/plot_brief.py
  doc/examples/features_detection/plot_orb.py
  doc/examples/features_detection/plot_sift.py
  doc/examples/transform/plot_fundamental_matrix.py
  doc/examples/transform/plot_matching.py
  skimage/feature/__init__.pyi
  skimage/feature/tests/test_util.py
  skimage/feature/util.py
Labels: :wrench: type: Maintenance, :adhesive_bandage: type: Bug fix, :+1: 1st approval

#7495 Remove unused and deprecated dependency pytest-runner
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance

#7502 Depend on imageio that does not force numpy downgrade
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance

#7505 Move from CITATION.bib to CITATION.cff
  CITATION.bib
  CITATION.cff
Labels: :page_facing_up: type: Documentation

#7496 Fix dynamic max trials of RANSAC (follow up)
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: :adhesive_bandage: type: Bug fix

#7501 Update deprecated configuration
  doc/source/conf.py
Labels: :robot: type: Infrastructure

#7507 Bump spin version to 0.11
  requirements/build.txt
Labels: :wrench: type: Maintenance

#7509 We do not guarantee dask compatibility, so do not test for it
  skimage/filters/tests/test_thresholding.py
Labels: :wrench: type: Maintenance

#7510 Fix build dependency
  pyproject.toml
Labels: :wrench: type: Maintenance

#7512 Ensure only a single label is present
  .github/workflows/label-check.yaml
Labels: :robot: type: Infrastructure

#7511 Update pydata-sphinx-theme
  pyproject.toml
  requirements/docs.txt
Labels: :robot: type: Infrastructure

#7438 Add sdist check to `spin sdist`
  .github/workflows/wheel_tests_and_release.yml
  .spin/cmds.py
  pyproject.toml
  tools/check_sdist.py
Labels: :wrench: type: Maintenance

#7508 Deprecate io.{imshow,imshow_collection,show}
  TODO.txt
  skimage/io/_io.py
  skimage/io/tests/test_mpl_imshow.py
Labels: :wrench: type: Maintenance, :arrow_down_small: Deprecation

#7519 Reorder items in TODO list.
  TODO.txt
Labels: :wrench: type: Maintenance
