Repository scikit-image/scikit-image, pull requests merged in 2024-07, with the labels that each got.

#7453 Account for np.bincount expecting arch-specific np.intp
  skimage/morphology/misc.py
Labels: :computer: Specific arch failure, :adhesive_bandage: type: Bug fix

#7456 Improved docstring in skeletonize
  skimage/morphology/_skeletonize.py
Labels: :page_facing_up: type: Documentation

#7451 Use NumPy 2.0 now that it is out
  pyproject.toml
  requirements/build.txt
Labels: :wrench: type: Maintenance

#7375 New GLCM properties to graycoprops
  skimage/feature/tests/test_texture.py
  skimage/feature/texture.py
Labels: :baby: type: New feature

#7462 Fix CI tests with minimal dependencies and make dependency resolution more robust
  tools/github/before_install.sh
  tools/github/script.sh
Labels: :robot: type: Infrastructure

#7297 Fixed skimage.feature.graycomatrix example documentation.
  skimage/feature/texture.py
Labels: :page_facing_up: type: Documentation

#7473 Handle degeneracy in spheroid surface area formula
  skimage/draw/draw3d.py
  skimage/draw/tests/test_draw3d.py
Labels: :adhesive_bandage: type: Bug fix

#7469 Fix morphology.thin from modifying input array
  skimage/morphology/_skeletonize.py
  skimage/morphology/tests/test_skeletonize.py
Labels: :adhesive_bandage: type: Bug fix

#7463 Add CI to test scikit-image against free-threaded Python 3.13
  .github/workflows/tests.yml
  TODO.txt
  meson.build
  skimage/measure/_regionprops.py
  skimage/meson.build
  skimage/transform/_geometric.py
  skimage/util/_map_array.py
  tools/github/before_install.sh
Labels: :robot: type: Infrastructure
