Repository scikit-image/scikit-image, pull requests merged in 2024-06, with the labels that each got.

#7429 Remove ineffective PR contribution clause.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :page_facing_up: type: Documentation

#7412 Add back support for python 3.9 for numpy 2 compatibility woes
  .github/workflows/tests.yml
  .github/workflows/wheels_recipe.yml
  azure-pipelines.yml
  doc/tools/apigen.py
  pyproject.toml
  skimage/feature/_fisher_vector.py
  skimage/filters/thresholding.py
  skimage/io/collection.py
  skimage/measure/fit.py
  skimage/segmentation/_watershed.py
  skimage/transform/tests/test_geometric.py
Labels: :wrench: type: Maintenance

#7427 CI: Add GitHub artifact attestations to package distribution
  .github/workflows/wheel_tests_and_release.yml
Labels: :robot: type: Infrastructure

#7430 Disable ruff/pyupgrade rule UP038
  pyproject.toml
Labels: :wrench: type: Maintenance

#7433 CI: Use full length commit SHA for PyPI publishing
  .github/workflows/wheel_tests_and_release.yml
Labels: :robot: type: Infrastructure

#7436 Be mindful of resources by canceling in-progress workflows
  .github/workflows/benchmarks.yml
  .github/workflows/nightly_wheel_build.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
Labels: :robot: type: Infrastructure

#7020 Clarify objection period for lazy consensus in SKIP 1
  doc/source/skips/1-governance.rst
Labels: :page_facing_up: type: Documentation

#7350 Add out-of-tree Pyodide builds in CI for `scikit-image`
  .github/workflows/emscripten.yml
  LICENSE.txt
  skimage/__init__.py
  skimage/_shared/_dependency_checks.py
  skimage/_shared/testing.py
  skimage/_shared/tests/test_testing.py
  skimage/feature/_basic_features.py
  skimage/feature/tests/test_util.py
  skimage/io/tests/test_io.py
  skimage/io/tests/test_mpl_imshow.py
  tools/emscripten/patches/0001-fix-npy-file-access.patch
  tools/emscripten/pytest_scikit_image_pyodide.js
Labels: :robot: type: Infrastructure

#7040 Add thin-plate splines warping
  LICENSE.txt
  doc/examples/transform/plot_tps_deformation.py
  skimage/future/__init__.pyi
  skimage/transform/__init__.pyi
  skimage/transform/_thin_plate_splines.py
  skimage/transform/meson.build
  skimage/transform/tests/meson.build
  skimage/transform/tests/test_thin_plate_splines.py
Labels: :baby: type: New feature, :wave: Outreachy

#4165 Add function to remove near objects in nd-image
  benchmarks/benchmark_morphology.py
  doc/examples/features_detection/plot_remove_objects.py
  skimage/morphology/__init__.py
  skimage/morphology/_misc_cy.pyx
  skimage/morphology/meson.build
  skimage/morphology/misc.py
  skimage/morphology/tests/test_misc.py
Labels: :pray: Feature request, :baby: type: New feature

#7444 Stop verifying wheel attestations temporarily
  .github/workflows/wheel_tests_and_release.yml
Labels: :wrench: type: Maintenance

#7447 CI: Verify each artifact attestation in a loop
  .github/workflows/wheel_tests_and_release.yml
Labels: :wrench: type: Maintenance

#7446 Update circleci-artifacts-redirector-action that moved to the Scientific Python org
  .github/workflows/circleci.yml
Labels: :wrench: type: Maintenance
