Repository scikit-image/scikit-image, pull requests merged in 2024-03, with the labels that each got.

#7335 Update dependencies (spec 0)
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance

#7255 Deprecate function `plot_matches` in favor of `plot_matched_features`
  TODO.txt
  skimage/feature/tests/test_util.py
  skimage/feature/util.py
Labels: :scroll: type: API, :hiking_boot: Path to skimage2

#7080 segmentation.expand_labels sampling argument for anisotropic resolution
  skimage/segmentation/_expand_labels.py
  skimage/segmentation/tests/test_expand_labels.py
Labels: :baby: type: New feature

#7267 Update how to document changes in contribution guide & PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.rst
Labels: :page_facing_up: type: Documentation

#7326 Follow-up cleaning & fixes for compatibility with NumPy 1 & 2
  TODO.txt
  doc/source/user_guide/getting_help.rst
  skimage/morphology/_flood_fill.py
  skimage/morphology/tests/test_flood_fill.py
  skimage/transform/_geometric.py
  skimage/util/__init__.py
  skimage/util/lookfor.py
  skimage/util/tests/meson.build
  skimage/util/tests/test_lookfor.py
Labels: :wrench: type: Maintenance

#7340 Replace ignored teardown with autouse fixture in `test_fits.py`
  skimage/io/tests/test_fits.py
Labels: :wrench: type: Maintenance

#7094 Deprecate `skimage.morphology.skeletonize_3d` in favor of just `skeletonize`
  TODO.txt
  skimage/morphology/__init__.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/tests/test_skeletonize.py
  skimage/morphology/tests/test_skeletonize_3d.py
Labels: :scroll: type: API

#7341 Address new copy semantics & broadcasting in `np.solve` in NumPy 2
  TODO.txt
  skimage/_shared/compat.py
  skimage/_shared/meson.build
  skimage/draw/draw.py
  skimage/feature/orb.py
  skimage/registration/_optical_flow.py
  skimage/transform/_geometric.py
Labels: :wrench: type: Maintenance

#7225 Deprecate output and positional args in `filters.gaussian`
  TODO.txt
  benchmarks/benchmark_measure.py
  doc/examples/edges/plot_active_contours.py
  doc/examples/registration/plot_stitching.py
  skimage/_shared/filters.py
  skimage/color/tests/test_adapt_rgb.py
  skimage/feature/_basic_features.py
  skimage/feature/blob.py
  skimage/feature/brief.py
  skimage/feature/corner.py
  skimage/feature/sift.py
  skimage/feature/tests/test_hog.py
  skimage/filters/_gaussian.py
  skimage/filters/tests/test_gaussian.py
  skimage/filters/thresholding.py
  skimage/segmentation/_quickshift.py
  skimage/segmentation/active_contour_model.py
  skimage/segmentation/slic_superpixels.py
  skimage/segmentation/tests/test_active_contour_model.py
  skimage/segmentation/tests/test_watershed.py
  skimage/transform/pyramids.py
  skimage/util/tests/test_apply_parallel.py
Labels: :arrow_down_small: Deprecation, :scroll: type: API, :hiking_boot: Path to skimage2

#7333 Remove use of cache when cache_active is False
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :adhesive_bandage: type: Bug fix

#7327 Ignore table of execution times by Sphinx gallery
  .gitignore
Labels: :wrench: type: Maintenance, :rocket: Quick win

#7345 Clarify slightly description of data_range parameter.
  skimage/metrics/_structural_similarity.py
Labels: :page_facing_up: type: Documentation

#7320 Don't use boolean shift as default in `skimage.filters.rank` functions
  skimage/filters/rank/_percentile.py
  skimage/filters/rank/bilateral.py
  skimage/filters/rank/generic.py
  skimage/filters/rank/tests/test_rank.py
Labels: :scroll: type: API

#7346 Examples in doc/examples/applications edited using object-oriented Matplotlib style
  doc/examples/applications/plot_3d_image_processing.py
  doc/examples/applications/plot_coins_segmentation.py
  doc/examples/applications/plot_colocalization_metrics.py
  doc/examples/applications/plot_cornea_spot_inpainting.py
  doc/examples/applications/plot_face_detection.py
  doc/examples/applications/plot_human_mitosis.py
  doc/examples/applications/plot_image_comparison.py
  doc/examples/applications/plot_morphology.py
  doc/examples/applications/plot_pixel_graphs.py
  doc/examples/applications/plot_rank_filters.py
  doc/examples/applications/plot_solidification_tracking.py
  doc/examples/applications/plot_thresholding_guide.py
Labels: :page_facing_up: type: Documentation

#7356 Allow a very small floating point tolerance for pearson test
  skimage/measure/_colocalization.py
  skimage/measure/tests/test_colocalization.py
Labels: :wrench: type: Maintenance

#7358 Exclude `pre-commit[bot]` from changelist's contributor list
  pyproject.toml
Labels: :robot: type: Infrastructure

#7355 Update numpydoc to version 1.7
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance
