Repository scikit-image/scikit-image, pull requests merged in 2024-11, with the labels that each got.

#7594 Don't check test coverage in CI
  azure-pipelines.yml
  tools/github/script.sh
Labels: :robot: type: Infrastructure

#7601 Bump `changelist` to v0.5
  requirements/_release_tools.txt
Labels: :wrench: type: Maintenance

#7608 Explicitly setup conda on macos for wheel building
  .github/workflows/wheels_recipe.yml
Labels: :robot: type: Infrastructure

#7612 Pin kaleido to 0.2.1
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance

#7609 Update upload-nightly-action
  .github/workflows/nightly_wheel_build.yml
Labels: :wrench: type: Maintenance

#7615 Update pillow
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance

#7606 Fix typo in morphology doc
  doc/examples/applications/plot_morphology.py
Labels: :page_facing_up: type: Documentation

#7616 Remove Python 2.7 cruft
  skimage/io/tests/test_mpl_imshow.py
Labels: :wrench: type: Maintenance

#7611 Use `intersphinx_registry` to keep intersphinx urls up to date.
  doc/source/conf.py
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance

#7576 Use scipy.sparse arrays
  .github/workflows/emscripten.yml
  TODO.txt
  pyproject.toml
  requirements/default.txt
  skimage/graph/_graph.py
  skimage/graph/_graph_cut.py
  skimage/graph/_ncut.py
  skimage/graph/_rag.py
  skimage/graph/tests/test_pixel_graph.py
  skimage/metrics/_adapted_rand_error.py
  skimage/metrics/_contingency_table.py
  skimage/metrics/_variation_of_information.py
  skimage/metrics/tests/test_segmentation_metrics.py
  skimage/restoration/inpaint.py
  skimage/segmentation/random_walker_segmentation.py
  skimage/segmentation/tests/test_random_walker.py
Labels: :scroll: type: API

#7548 Improve performance of `peak_local_max` and feature detectors that rely on it
  skimage/_shared/coord.py
  skimage/feature/peak.py
Labels: :chart_with_upwards_trend: type: Performance

#7617 Update file extension and reformat Markdown file.
  CONTRIBUTORS.md
Labels: :wrench: type: Maintenance
