Repository scikit-image/scikit-image, pull requests merged in 2024-10, with the labels that each got.

#7560 Update pre-commit versions
  .pre-commit-config.yaml
  doc/examples/filters/plot_denoise_wavelet.py
  pyproject.toml
  skimage/_vendored/numpy_lookfor.py
Labels: :wrench: type: Maintenance

#7561 Drop Python 3.9 support
  .github/workflows/tests.yml
  .github/workflows/wheels_recipe.yml
  azure-pipelines.yml
  pyproject.toml
Labels: :wrench: type: Maintenance

#7551 Account for empty arrays when counting segments per contour level.
  doc/examples/applications/plot_human_mitosis.py
Labels: :page_facing_up: type: Documentation

#7557 Remove unused PYX files in io/_plugins
  skimage/io/_plugins/_colormixer.pyx
  skimage/io/_plugins/_histograms.pyx
  skimage/io/_plugins/meson.build
  skimage/io/tests/meson.build
  skimage/io/tests/test_histograms.py
Labels: :wrench: type: Maintenance, :rocket: Quick win

#7565 Support Python 3.13
  .github/workflows/tests.yml
  pyproject.toml
Labels: :wrench: type: Maintenance

#7552 Preserve value of deprecated parameters without replacement
  skimage/_shared/tests/test_utils.py
  skimage/_shared/utils.py
Labels: :wrench: type: Maintenance, :+1: 1st approval

#7567 Fix missing minigalleries by using full names in directives
  doc/tools/apigen.py
Labels: :wrench: type: Maintenance, :warning: Priority

#7571 Build Python 3.13 wheels
  .github/workflows/wheels_recipe.yml
Labels: :wrench: type: Maintenance

#7573 Update TODO
  TODO.txt
Labels: :wrench: type: Maintenance

#7572 Remove deprecated skeletonize_3d
  TODO.txt
  skimage/morphology/__init__.py
  skimage/morphology/_skeletonize.py
  skimage/morphology/tests/test_skeletonize.py
Labels: :wrench: type: Maintenance

#7574 Remove deprecated gaussian output parameter
  TODO.txt
  skimage/_shared/filters.py
  skimage/filters/tests/test_gaussian.py
Labels: :wrench: type: Maintenance

#7569 Ensure that `RegionProperties` can be deserialized with pickle
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :adhesive_bandage: type: Bug fix

#7549 Render paragraphs in dormant message
  .github/workflows/dormant_issues_prs.yml
Labels: :robot: type: Infrastructure, :rocket: Quick win

#7578 Test Py3.13 on windows
  azure-pipelines.yml
Labels: :wrench: type: Maintenance

#7071 Fix several watershed issues (off-center markers, watershed_line)
  skimage/segmentation/_watershed_cy.pyx
  skimage/segmentation/tests/test_watershed.py
Labels: :adhesive_bandage: type: Bug fix, :+1: 1st approval

#7581 Fix formatting issues
  benchmarks/benchmark_exposure.py
  benchmarks/benchmark_interpolation.py
  benchmarks/benchmark_measure.py
  benchmarks/benchmark_morphology.py
  benchmarks/benchmark_segmentation.py
  doc/Makefile
  doc/examples/applications/plot_morphology.py
  doc/examples/filters/plot_nonlocal_means.py
  doc/gh-pages.py
  skimage/__init__.py
  skimage/_vendored/numpy_lookfor.py
  skimage/color/colorconv.py
  skimage/data/_fetchers.py
  skimage/data/_registry.py
  skimage/feature/blob.py
  skimage/feature/corner.py
  skimage/feature/util.py
  skimage/io/tests/test_io.py
  skimage/measure/_colocalization.py
  skimage/measure/_regionprops.py
  tools/precompute/mc_meta/visual_test.py
Labels: :wrench: type: Maintenance

#7353 Deprecate `skimage.io` plugin infrastructure
  TODO.txt
  pyproject.toml
  skimage/io/__init__.py
  skimage/io/_io.py
  skimage/io/manage_plugins.py
  skimage/io/tests/test_io.py
  skimage/io/tests/test_mpl_imshow.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_plugin.py
  skimage/io/tests/test_simpleitk.py
Labels: :arrow_down_small: Deprecation, :scroll: type: API, :hiking_boot: Path to skimage2

#7587 Update build dependencies
  pyproject.toml
  requirements/build.txt
Labels: :wrench: type: Maintenance

#7586 Update minimum supported pyamg
  TODO.txt
  pyproject.toml
  requirements/default.txt
  requirements/optional.txt
  skimage/segmentation/random_walker_segmentation.py
Labels: :wrench: type: Maintenance

#7590 Update documentation dependencies
  pyproject.toml
  requirements/docs.txt
Labels: :wrench: type: Maintenance

#7541 Feature/enhance plot matched features
  skimage/feature/tests/test_util.py
  skimage/feature/util.py
Labels: :fast_forward: type: Enhancement, :+1: 1st approval
