Repository scikit-image/scikit-image, pull requests merged in 2024-04, with the labels that each got.

#7349 Simplify warning filters in test suite
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/tests.yml
  TODO.txt
  pyproject.toml
  skimage/_shared/compat.py
  skimage/_shared/testing.py
  skimage/conftest.py
  skimage/filters/rank/tests/__init__.py
  skimage/io/tests/test_simpleitk.py
  skimage/segmentation/random_walker_segmentation.py
Labels: :wrench: type: Maintenance

#7367 Build against NumPy 2
  pyproject.toml
  requirements/build.txt
  requirements/test.txt
Labels: :wrench: type: Maintenance

#7370 Remove ensure_python_version function
  skimage/__init__.py
  skimage/_shared/version_requirements.py
Labels: :wrench: type: Maintenance

#7368 Update GH actions
  .github/workflows/benchmarks.yml
  .github/workflows/build_docs.yml
  .github/workflows/nightly_wheel_build.yml
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
  .github/workflows/wheels_recipe.yml
Labels: :wrench: type: Maintenance

#7362 Include border when generating basin markers for watershed.
  doc/examples/applications/plot_human_mitosis.py
Labels: :page_facing_up: type: Documentation

#7373 Update lazyloader
  pyproject.toml
  requirements/default.txt
Labels: :wrench: type: Maintenance

#7097 Fix docstring (missing minus sign) for `EuclideanTransform`.
  skimage/transform/_geometric.py
Labels: :page_facing_up: type: Documentation

#7386 Use `numpy.inf` instead of deprecated `numpy.infty`
  doc/examples/features_detection/plot_windowed_histogram.py
  tools/mailmap.py
Labels: :wrench: type: Maintenance, :rocket: Quick win

#7384 Add date to 0.23.1 release notes
  RELEASE.txt
  doc/source/release_notes/release_0.23.1.rst
Labels: :page_facing_up: type: Documentation, :rocket: Quick win

#7360 Fix docstring for connectivity parameter in watershed function.
  skimage/segmentation/_watershed.py
Labels: :page_facing_up: type: Documentation, :rocket: Quick win

#7387 Update Ruff config
  pyproject.toml
Labels: :wrench: type: Maintenance

#7390 Update azure pipelines
  azure-pipelines.yml
Labels: :wrench: type: Maintenance

#7389 Use upload- and download-artifact v4
  .github/workflows/benchmarks.yml
  .github/workflows/build_docs.yml
  .github/workflows/nightly_wheel_build.yml
  .github/workflows/wheel_tests_and_release.yml
  .github/workflows/wheels_recipe.yml
Labels: :wrench: type: Maintenance

#7392 Use more complete list of `_integer_types` for convert
  skimage/util/dtype.py
  skimage/util/tests/test_dtype.py
Labels: :adhesive_bandage: type: Bug fix

#7393 Ignore arch specific cast warnings originating from `astype` in tests
  skimage/filters/tests/test_unsharp_mask.py
  skimage/transform/tests/test_pyramids.py
Labels: :wrench: type: Maintenance, :computer: Specific arch failure

#7395 Update link to numpydoc example.py
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :wrench: type: Maintenance

#7400 Ignore Sphinx warning about unpickable cache
  doc/source/conf.py
  pyproject.toml
  requirements/docs.txt
Labels: :robot: type: Infrastructure

#7401 Simplify instructions on changelist in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :robot: type: Infrastructure, :rocket: Quick win

#7402 Update release process notes
  RELEASE.txt
Labels: :page_facing_up: type: Documentation

#7405 Fix typo in docstring of `skimage.measure.regionprops`
  skimage/measure/_regionprops.py
Labels: :page_facing_up: type: Documentation

#7394 improved speed of fast corner detect
  skimage/feature/corner_cy.pyx
Labels: :chart_with_upwards_trend: type: Performance
