Repository scikit-image/scikit-image, pull requests merged in 2024-02, with the labels that each got.

#7314 Use theta for tightness in the docstring of optical_flow_tvl1
  skimage/registration/_optical_flow.py
Labels: :page_facing_up: type: Documentation

#7321 Remove obsolete instruction about documenting changes.
  TODO.txt
Labels: :page_facing_up: type: Documentation

#7324 Issue 7313 dt comment + copyediting grayscale
  skimage/registration/_optical_flow.py
  skimage/registration/_optical_flow_utils.py
Labels: :page_facing_up: type: Documentation

#7288 Test nightly wheel build with NumPy 2.0
  .github/workflows/nightly_wheel_build.yml
  .github/workflows/wheels_recipe.yml
  LICENSE.txt
  TODO.txt
  doc/source/user_guide/getting_help.rst
  pyproject.toml
  requirements/test.txt
  skimage/_shared/dtype.py
  skimage/_shared/meson.build
  skimage/_shared/tests/meson.build
  skimage/_shared/tests/test_dtype.py
  skimage/_vendored/__init__.py
  skimage/_vendored/meson.build
  skimage/_vendored/numpy_lookfor.py
  skimage/color/colorconv.py
  skimage/color/colorlabel.py
  skimage/color/tests/test_colorconv.py
  skimage/data/tests/test_data.py
  skimage/draw/draw.py
  skimage/feature/sift.py
  skimage/feature/tests/test_blob.py
  skimage/feature/tests/test_corner.py
  skimage/filters/edges.py
  skimage/filters/ridges.py
  skimage/filters/tests/test_thresholding.py
  skimage/filters/thresholding.py
  skimage/graph/_rag.py
  skimage/io/_io.py
  skimage/io/_plugins/pil_plugin.py
  skimage/io/tests/test_imageio.py
  skimage/io/tests/test_imread.py
  skimage/io/tests/test_pil.py
  skimage/io/tests/test_simpleitk.py
  skimage/io/tests/test_tifffile.py
  skimage/measure/_moments.py
  skimage/measure/tests/test_regionprops.py
  skimage/meson.build
  skimage/metrics/tests/test_simple_metrics.py
  skimage/morphology/_flood_fill.py
  skimage/morphology/tests/test_flood_fill.py
  skimage/segmentation/_chan_vese.py
  skimage/transform/_geometric.py
  skimage/transform/integral.py
  skimage/transform/tests/test_pyramids.py
  skimage/util/dtype.py
  skimage/util/lookfor.py
  tools/github/script.sh
Labels: :wrench: type: Maintenance, :arrow_up: Upstream

#7325 CI: Update scientific-python/upload-nightly-action to 0.5.0
  .github/workflows/nightly_wheel_build.yml
Labels: :robot: type: Infrastructure

#7310 Addressing the input check bug for pixel_graph (#7233)
  skimage/graph/_graph.py
  skimage/graph/tests/test_pixel_graph.py
Labels: :adhesive_bandage: type: Bug fix

#7294 Add `assert_stacklevel` helper to check stacklevel of captured warnings
  skimage/_shared/testing.py
  skimage/_shared/tests/test_testing.py
  skimage/_shared/tests/test_utils.py
  skimage/color/tests/test_colorconv.py
  skimage/filters/_median.py
  skimage/filters/tests/test_median.py
  skimage/io/tests/test_imageio.py
  skimage/measure/tests/test_fit.py
  skimage/morphology/tests/test_gray.py
  skimage/registration/tests/test_phase_cross_correlation.py
Labels: :robot: type: Infrastructure

#7329 Removed missing (previously deprecated) arg from docstring example for active_contour
  skimage/segmentation/active_contour_model.py
Labels: :page_facing_up: type: Documentation

#7269 Include dates in release note headings
  doc/source/release_notes/release_0.10.rst
  doc/source/release_notes/release_0.11.rst
  doc/source/release_notes/release_0.12.rst
  doc/source/release_notes/release_0.13.rst
  doc/source/release_notes/release_0.14.rst
  doc/source/release_notes/release_0.15.rst
  doc/source/release_notes/release_0.16.rst
  doc/source/release_notes/release_0.17.rst
  doc/source/release_notes/release_0.18.rst
  doc/source/release_notes/release_0.19.rst
  doc/source/release_notes/release_0.20.rst
  doc/source/release_notes/release_0.21.rst
  doc/source/release_notes/release_0.22.rst
  doc/source/release_notes/release_0.3.rst
  doc/source/release_notes/release_0.4.rst
  doc/source/release_notes/release_0.5.rst
  doc/source/release_notes/release_0.6.rst
  doc/source/release_notes/release_0.7.rst
  doc/source/release_notes/release_0.8.rst
  doc/source/release_notes/release_0.9.rst
  doc/source/release_notes/release_dev.rst
  doc/source/release_notes/release_template.rst
Labels: :page_facing_up: type: Documentation
