Repository scikit-image/scikit-image, pull requests merged in 2025-09, with the labels that each got.

#7891 Remove np.testing from skimage._shared.utils
  src/skimage/_shared/utils.py
Labels: :wrench: type: Maintenance

#7894 MAINT: some dependency version consistency cleanups
  .binder/requirements.txt
  .github/workflows/emscripten.yaml
  environment.yml
  pyproject.toml
  requirements/optional.txt
  tools/generate_requirements.py
Labels: :wrench: type: Maintenance

#7774 update docs for `blob_log` and `blob_doh`
  src/skimage/feature/blob.py
Labels: :page_facing_up: type: Documentation, :rocket: Quick win

#7887 Add `__repr__` to `RegionProperties` class
  src/skimage/measure/_regionprops.py
Labels: :fast_forward: type: Enhancement, :rocket: Quick win
