Repository scikit-image/scikit-image, pull requests merged in 2025-05, with the labels that each got.

#7752 Report failures on main via issue
  .github/MAIN_FAIL_TEMPLATE.md
  .github/workflows/test-docs.yaml
  .github/workflows/test-linux.yaml
  .github/workflows/test-macos.yaml
  .github/workflows/test-nightlies-on-main.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/wheels-recipe.yaml
Labels: :robot: type: Infrastructure

#7786 Make doctest-plus work with spin
  .spin/cmds.py
  CONTRIBUTING.rst
  pyproject.toml
Labels: :robot: type: Infrastructure

#7787 Pin JasonEtco/create-an-issue action to SHA for v2.9.2
  .github/workflows/test-docs.yaml
  .github/workflows/test-linux.yaml
  .github/workflows/test-macos.yaml
  .github/workflows/test-nightlies-on-main.yaml
  .github/workflows/test-windows.yaml
  .github/workflows/wheels-recipe.yaml
Labels: :wrench: type: Maintenance

#7788 Temporarily pin to `pyodide-build==0.30.0`, and ensure that the correct xbuildenvs are used
  .github/workflows/emscripten.yaml
Labels: :robot: type: Infrastructure

#7763 DOC: Include missing gain parameter in adjust_gamma equation
  skimage/exposure/exposure.py
Labels: :page_facing_up: type: Documentation

#7792 Document output dtype for transform.resize.
  skimage/transform/_warps.py
Labels: :page_facing_up: type: Documentation

#7793 CI: Update pypa/gh-action-pypi-publish to v1.12.4 for attestations on PyPI
  .github/workflows/wheels-test-and-release.yaml
Labels: :robot: type: Infrastructure, :rocket: Quick win

#7745 Add intensity_median to regionprops
  skimage/measure/_regionprops.py
  skimage/measure/tests/test_regionprops.py
Labels: :pray: Feature request, :baby: type: New feature, :+1: 1st approval
