Repository scikit-image/scikit-image, pull requests merged in 2025-01, with the labels that each got.

#7630 Change old import convention in the gallery examples
  doc/examples/applications/plot_3d_image_processing.py
  doc/examples/applications/plot_3d_interaction.py
  doc/examples/applications/plot_3d_structure_tensor.py
  doc/examples/applications/plot_coins_segmentation.py
  doc/examples/applications/plot_colocalization_metrics.py
  doc/examples/applications/plot_face_detection.py
  doc/examples/applications/plot_fluorescence_nuclear_envelope.py
  doc/examples/applications/plot_haar_extraction_selection_classification.py
  doc/examples/applications/plot_image_comparison.py
  doc/examples/applications/plot_morphology.py
  doc/examples/applications/plot_pixel_graphs.py
  doc/examples/applications/plot_rank_filters.py
  doc/examples/applications/plot_solidification_tracking.py
  doc/examples/applications/plot_text.py
  doc/examples/applications/plot_thresholding_guide.py
Labels: :page_facing_up: type: Documentation

#7652 Add `centroid` to `__all__` in PYI
  skimage/measure/__init__.pyi
Labels: :adhesive_bandage: type: Bug fix, :rocket: Quick win

#7647 Make apigen.py work with editable hooks
  doc/tools/apigen.py
  doc/tools/build_modref_templates.py
Labels: :robot: type: Infrastructure

#7645 Change type of default `active_contour` argument `w_line` literal to indicate it is a float
  skimage/segmentation/active_contour_model.py
Labels: :wrench: type: Maintenance

#7643 Feature/improve stability blur effect
  skimage/measure/_blur_effect.py
  skimage/measure/tests/test_blur_effect.py
Labels: :adhesive_bandage: type: Bug fix

#7656 Temporarily disable parallel building of gallery
  doc/source/conf.py
Labels: :wrench: type: Maintenance

#7648 Require at least 5 data points for ellipse estimation
  skimage/measure/fit.py
  skimage/measure/tests/test_fit.py
Labels: :adhesive_bandage: type: Bug fix

#7664 Build Linux ARM wheels natively
  .github/workflows/wheels_recipe.yml
Labels: :robot: type: Infrastructure

#7669 Skip flaky test on azure
  skimage/graph/tests/test_rag.py
Labels: :wrench: type: Maintenance

#7655 Explicitly upcast float16 to float32 in random_walker
  skimage/segmentation/random_walker_segmentation.py
  skimage/segmentation/tests/test_random_walker.py
Labels: :adhesive_bandage: type: Bug fix

#7660 Add missing images to legacy dataset in registry and meson.build
  skimage/data/_registry.py
  skimage/data/meson.build
Labels: :adhesive_bandage: type: Bug fix

#7675 Arpack eigenvector for zero A
  skimage/graph/_graph_cut.py
Labels: :warning: Priority, :adhesive_bandage: type: Bug fix

#7672 Refactor gh scripts
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
  .github/workflows/wheels_recipe.yml
  azure-pipelines.yml
  pyproject.toml
  requirements/build.txt
  tools/github/script.sh
  tools/github/setup_build_env.sh
  tools/github/setup_docs_env.sh
  tools/github/setup_test_env.sh
Labels: :robot: type: Infrastructure

#7682 Improve docstring for rolling_ball function.
  skimage/restoration/_rolling_ball.py
Labels: :page_facing_up: type: Documentation

#7555 Use pytest config in pyproject.toml in CI
  .github/workflows/emscripten.yml
  .github/workflows/nightly_wheel_build.yml
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/tests.yml
  pyproject.toml
  requirements/default.txt
  requirements/docs.txt
  requirements/optional.txt
  requirements/test.txt
  skimage/data/tests/test_data.py
  skimage/io/tests/test_simpleitk.py
  skimage/restoration/_cycle_spin.py
  skimage/segmentation/tests/test_random_walker.py
Labels: :robot: type: Infrastructure

#7688 Lower CI build verbosity
  .github/workflows/build_docs.yml
  .github/workflows/test_nightlies_on_main.yml
  .github/workflows/tests.yml
Labels: :robot: type: Infrastructure

#7687 Port azure to gh
  .github/workflows/tests-windows.yaml
  azure-pipelines.yml
  skimage/graph/_graph_cut.py
  skimage/metrics/tests/test_simple_metrics.py
  skimage/metrics/tests/test_structural_similarity.py
Labels: :robot: type: Infrastructure
